// Code generated by ent, DO NOT EDIT.

package aicreditsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aicreditsnapshot type in the database.
	Label = "ai_credit_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldCreditType holds the string denoting the credit_type field in the database.
	FieldCreditType = "credit_type"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// Table holds the table name of the aicreditsnapshot in the database.
	Table = "ai_credit_snapshots"
)

// Columns holds all SQL columns for aicreditsnapshot fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldCreditType,
	FieldAmount,
	FieldCapturedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// CreditTypeValidator is a validator for the "credit_type" field. It is called by the builders before save.
	CreditTypeValidator func(string) error
	// DefaultCapturedAt holds the default value on creation for the "captured_at" field.
	DefaultCapturedAt func() time.Time
)

// OrderOption defines the ordering options for the AICreditSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByCreditType orders the results by the credit_type field.
func ByCreditType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditType, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}
