// Code generated by ent, DO NOT EDIT.

package usersmartscheduleaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldAccountID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldPlatform, v))
}

// MaxConcurrency applies equality check predicate on the "max_concurrency" field. It's identical to MaxConcurrencyEQ.
func MaxConcurrency(v int) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldMaxConcurrency, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNotIn(FieldAccountID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNotIn(FieldUserID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldContainsFold(FieldPlatform, v))
}

// MaxConcurrencyEQ applies the EQ predicate on the "max_concurrency" field.
func MaxConcurrencyEQ(v int) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyNEQ applies the NEQ predicate on the "max_concurrency" field.
func MaxConcurrencyNEQ(v int) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyIn applies the In predicate on the "max_concurrency" field.
func MaxConcurrencyIn(vs ...int) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyNotIn applies the NotIn predicate on the "max_concurrency" field.
func MaxConcurrencyNotIn(vs ...int) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNotIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyGT applies the GT predicate on the "max_concurrency" field.
func MaxConcurrencyGT(v int) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldGT(FieldMaxConcurrency, v))
}

// MaxConcurrencyGTE applies the GTE predicate on the "max_concurrency" field.
func MaxConcurrencyGTE(v int) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldGTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyLT applies the LT predicate on the "max_concurrency" field.
func MaxConcurrencyLT(v int) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldLT(FieldMaxConcurrency, v))
}

// MaxConcurrencyLTE applies the LTE predicate on the "max_concurrency" field.
func MaxConcurrencyLTE(v int) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldLTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyIsNil applies the IsNil predicate on the "max_concurrency" field.
func MaxConcurrencyIsNil() predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldIsNull(FieldMaxConcurrency))
}

// MaxConcurrencyNotNil applies the NotNil predicate on the "max_concurrency" field.
func MaxConcurrencyNotNil() predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.FieldNotNull(FieldMaxConcurrency))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, UserColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, AccountColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserSmartScheduleAccount) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserSmartScheduleAccount) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserSmartScheduleAccount) predicate.UserSmartScheduleAccount {
	return predicate.UserSmartScheduleAccount(sql.NotPredicates(p))
}
