// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountscheduleuser"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountScheduleUserCreate is the builder for creating a AccountScheduleUser entity.
type AccountScheduleUserCreate struct {
	config
	mutation *AccountScheduleUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountScheduleUserCreate) SetAccountID(v int64) *AccountScheduleUserCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountScheduleUserCreate) SetUserID(v int64) *AccountScheduleUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountScheduleUserCreate) SetCreatedAt(v time.Time) *AccountScheduleUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableCreatedAt(v *time.Time) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAllow sets the "allow" field.
func (_c *AccountScheduleUserCreate) SetAllow(v bool) *AccountScheduleUserCreate {
	_c.mutation.SetAllow(v)
	return _c
}

// SetNillableAllow sets the "allow" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableAllow(v *bool) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetAllow(*v)
	}
	return _c
}

// SetDeny sets the "deny" field.
func (_c *AccountScheduleUserCreate) SetDeny(v bool) *AccountScheduleUserCreate {
	_c.mutation.SetDeny(v)
	return _c
}

// SetNillableDeny sets the "deny" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableDeny(v *bool) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetDeny(*v)
	}
	return _c
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (_c *AccountScheduleUserCreate) SetMaxConcurrency(v int) *AccountScheduleUserCreate {
	_c.mutation.SetMaxConcurrency(v)
	return _c
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableMaxConcurrency(v *int) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetMaxConcurrency(*v)
	}
	return _c
}

// SetQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field.
func (_c *AccountScheduleUserCreate) SetQualityMaxP50TtftMs(v int) *AccountScheduleUserCreate {
	_c.mutation.SetQualityMaxP50TtftMs(v)
	return _c
}

// SetNillableQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableQualityMaxP50TtftMs(v *int) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetQualityMaxP50TtftMs(*v)
	}
	return _c
}

// SetQualityMinSuccessRate sets the "quality_min_success_rate" field.
func (_c *AccountScheduleUserCreate) SetQualityMinSuccessRate(v float64) *AccountScheduleUserCreate {
	_c.mutation.SetQualityMinSuccessRate(v)
	return _c
}

// SetNillableQualityMinSuccessRate sets the "quality_min_success_rate" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableQualityMinSuccessRate(v *float64) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetQualityMinSuccessRate(*v)
	}
	return _c
}

// SetQualityMinSuccessSamples sets the "quality_min_success_samples" field.
func (_c *AccountScheduleUserCreate) SetQualityMinSuccessSamples(v int) *AccountScheduleUserCreate {
	_c.mutation.SetQualityMinSuccessSamples(v)
	return _c
}

// SetNillableQualityMinSuccessSamples sets the "quality_min_success_samples" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableQualityMinSuccessSamples(v *int) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetQualityMinSuccessSamples(*v)
	}
	return _c
}

// SetQualityMinTtftSamples sets the "quality_min_ttft_samples" field.
func (_c *AccountScheduleUserCreate) SetQualityMinTtftSamples(v int) *AccountScheduleUserCreate {
	_c.mutation.SetQualityMinTtftSamples(v)
	return _c
}

// SetNillableQualityMinTtftSamples sets the "quality_min_ttft_samples" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableQualityMinTtftSamples(v *int) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetQualityMinTtftSamples(*v)
	}
	return _c
}

// SetQualityCondition sets the "quality_condition" field.
func (_c *AccountScheduleUserCreate) SetQualityCondition(v string) *AccountScheduleUserCreate {
	_c.mutation.SetQualityCondition(v)
	return _c
}

// SetNillableQualityCondition sets the "quality_condition" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableQualityCondition(v *string) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetQualityCondition(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountScheduleUserCreate) SetAccount(v *Account) *AccountScheduleUserCreate {
	return _c.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccountScheduleUserCreate) SetUser(v *User) *AccountScheduleUserCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AccountScheduleUserMutation object of the builder.
func (_c *AccountScheduleUserCreate) Mutation() *AccountScheduleUserMutation {
	return _c.mutation
}

// Save creates the AccountScheduleUser in the database.
func (_c *AccountScheduleUserCreate) Save(ctx context.Context) (*AccountScheduleUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountScheduleUserCreate) SaveX(ctx context.Context) *AccountScheduleUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountScheduleUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountScheduleUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountScheduleUserCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountscheduleuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Allow(); !ok {
		v := accountscheduleuser.DefaultAllow
		_c.mutation.SetAllow(v)
	}
	if _, ok := _c.mutation.Deny(); !ok {
		v := accountscheduleuser.DefaultDeny
		_c.mutation.SetDeny(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountScheduleUserCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountScheduleUser.account_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AccountScheduleUser.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountScheduleUser.created_at"`)}
	}
	if _, ok := _c.mutation.Allow(); !ok {
		return &ValidationError{Name: "allow", err: errors.New(`ent: missing required field "AccountScheduleUser.allow"`)}
	}
	if _, ok := _c.mutation.Deny(); !ok {
		return &ValidationError{Name: "deny", err: errors.New(`ent: missing required field "AccountScheduleUser.deny"`)}
	}
	if v, ok := _c.mutation.QualityCondition(); ok {
		if err := accountscheduleuser.QualityConditionValidator(v); err != nil {
			return &ValidationError{Name: "quality_condition", err: fmt.Errorf(`ent: validator failed for field "AccountScheduleUser.quality_condition": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountScheduleUser.account"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AccountScheduleUser.user"`)}
	}
	return nil
}

func (_c *AccountScheduleUserCreate) sqlSave(ctx context.Context) (*AccountScheduleUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *AccountScheduleUserCreate) createSpec() (*AccountScheduleUser, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountScheduleUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountscheduleuser.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountscheduleuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Allow(); ok {
		_spec.SetField(accountscheduleuser.FieldAllow, field.TypeBool, value)
		_node.Allow = value
	}
	if value, ok := _c.mutation.Deny(); ok {
		_spec.SetField(accountscheduleuser.FieldDeny, field.TypeBool, value)
		_node.Deny = value
	}
	if value, ok := _c.mutation.MaxConcurrency(); ok {
		_spec.SetField(accountscheduleuser.FieldMaxConcurrency, field.TypeInt, value)
		_node.MaxConcurrency = &value
	}
	if value, ok := _c.mutation.QualityMaxP50TtftMs(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMaxP50TtftMs, field.TypeInt, value)
		_node.QualityMaxP50TtftMs = &value
	}
	if value, ok := _c.mutation.QualityMinSuccessRate(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMinSuccessRate, field.TypeFloat64, value)
		_node.QualityMinSuccessRate = &value
	}
	if value, ok := _c.mutation.QualityMinSuccessSamples(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMinSuccessSamples, field.TypeInt, value)
		_node.QualityMinSuccessSamples = &value
	}
	if value, ok := _c.mutation.QualityMinTtftSamples(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMinTtftSamples, field.TypeInt, value)
		_node.QualityMinTtftSamples = &value
	}
	if value, ok := _c.mutation.QualityCondition(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityCondition, field.TypeString, value)
		_node.QualityCondition = &value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.AccountTable,
			Columns: []string{accountscheduleuser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.UserTable,
			Columns: []string{accountscheduleuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountScheduleUser.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountScheduleUserUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountScheduleUserCreate) OnConflict(opts ...sql.ConflictOption) *AccountScheduleUserUpsertOne {
	_c.conflict = opts
	return &AccountScheduleUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountScheduleUserCreate) OnConflictColumns(columns ...string) *AccountScheduleUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountScheduleUserUpsertOne{
		create: _c,
	}
}

type (
	// AccountScheduleUserUpsertOne is the builder for "upsert"-ing
	//  one AccountScheduleUser node.
	AccountScheduleUserUpsertOne struct {
		create *AccountScheduleUserCreate
	}

	// AccountScheduleUserUpsert is the "OnConflict" setter.
	AccountScheduleUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountScheduleUserUpsert) SetAccountID(v int64) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateAccountID() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldAccountID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountScheduleUserUpsert) SetUserID(v int64) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateUserID() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldUserID)
	return u
}

// SetAllow sets the "allow" field.
func (u *AccountScheduleUserUpsert) SetAllow(v bool) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldAllow, v)
	return u
}

// UpdateAllow sets the "allow" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateAllow() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldAllow)
	return u
}

// SetDeny sets the "deny" field.
func (u *AccountScheduleUserUpsert) SetDeny(v bool) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldDeny, v)
	return u
}

// UpdateDeny sets the "deny" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateDeny() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldDeny)
	return u
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *AccountScheduleUserUpsert) SetMaxConcurrency(v int) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldMaxConcurrency, v)
	return u
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateMaxConcurrency() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldMaxConcurrency)
	return u
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *AccountScheduleUserUpsert) AddMaxConcurrency(v int) *AccountScheduleUserUpsert {
	u.Add(accountscheduleuser.FieldMaxConcurrency, v)
	return u
}

// ClearMaxConcurrency clears the value of the "max_concurrency" field.
func (u *AccountScheduleUserUpsert) ClearMaxConcurrency() *AccountScheduleUserUpsert {
	u.SetNull(accountscheduleuser.FieldMaxConcurrency)
	return u
}

// SetQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field.
func (u *AccountScheduleUserUpsert) SetQualityMaxP50TtftMs(v int) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldQualityMaxP50TtftMs, v)
	return u
}

// UpdateQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateQualityMaxP50TtftMs() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldQualityMaxP50TtftMs)
	return u
}

// AddQualityMaxP50TtftMs adds v to the "quality_max_p50_ttft_ms" field.
func (u *AccountScheduleUserUpsert) AddQualityMaxP50TtftMs(v int) *AccountScheduleUserUpsert {
	u.Add(accountscheduleuser.FieldQualityMaxP50TtftMs, v)
	return u
}

// ClearQualityMaxP50TtftMs clears the value of the "quality_max_p50_ttft_ms" field.
func (u *AccountScheduleUserUpsert) ClearQualityMaxP50TtftMs() *AccountScheduleUserUpsert {
	u.SetNull(accountscheduleuser.FieldQualityMaxP50TtftMs)
	return u
}

// SetQualityMinSuccessRate sets the "quality_min_success_rate" field.
func (u *AccountScheduleUserUpsert) SetQualityMinSuccessRate(v float64) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldQualityMinSuccessRate, v)
	return u
}

// UpdateQualityMinSuccessRate sets the "quality_min_success_rate" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateQualityMinSuccessRate() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldQualityMinSuccessRate)
	return u
}

// AddQualityMinSuccessRate adds v to the "quality_min_success_rate" field.
func (u *AccountScheduleUserUpsert) AddQualityMinSuccessRate(v float64) *AccountScheduleUserUpsert {
	u.Add(accountscheduleuser.FieldQualityMinSuccessRate, v)
	return u
}

// ClearQualityMinSuccessRate clears the value of the "quality_min_success_rate" field.
func (u *AccountScheduleUserUpsert) ClearQualityMinSuccessRate() *AccountScheduleUserUpsert {
	u.SetNull(accountscheduleuser.FieldQualityMinSuccessRate)
	return u
}

// SetQualityMinSuccessSamples sets the "quality_min_success_samples" field.
func (u *AccountScheduleUserUpsert) SetQualityMinSuccessSamples(v int) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldQualityMinSuccessSamples, v)
	return u
}

// UpdateQualityMinSuccessSamples sets the "quality_min_success_samples" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateQualityMinSuccessSamples() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldQualityMinSuccessSamples)
	return u
}

// AddQualityMinSuccessSamples adds v to the "quality_min_success_samples" field.
func (u *AccountScheduleUserUpsert) AddQualityMinSuccessSamples(v int) *AccountScheduleUserUpsert {
	u.Add(accountscheduleuser.FieldQualityMinSuccessSamples, v)
	return u
}

// ClearQualityMinSuccessSamples clears the value of the "quality_min_success_samples" field.
func (u *AccountScheduleUserUpsert) ClearQualityMinSuccessSamples() *AccountScheduleUserUpsert {
	u.SetNull(accountscheduleuser.FieldQualityMinSuccessSamples)
	return u
}

// SetQualityMinTtftSamples sets the "quality_min_ttft_samples" field.
func (u *AccountScheduleUserUpsert) SetQualityMinTtftSamples(v int) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldQualityMinTtftSamples, v)
	return u
}

// UpdateQualityMinTtftSamples sets the "quality_min_ttft_samples" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateQualityMinTtftSamples() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldQualityMinTtftSamples)
	return u
}

// AddQualityMinTtftSamples adds v to the "quality_min_ttft_samples" field.
func (u *AccountScheduleUserUpsert) AddQualityMinTtftSamples(v int) *AccountScheduleUserUpsert {
	u.Add(accountscheduleuser.FieldQualityMinTtftSamples, v)
	return u
}

// ClearQualityMinTtftSamples clears the value of the "quality_min_ttft_samples" field.
func (u *AccountScheduleUserUpsert) ClearQualityMinTtftSamples() *AccountScheduleUserUpsert {
	u.SetNull(accountscheduleuser.FieldQualityMinTtftSamples)
	return u
}

// SetQualityCondition sets the "quality_condition" field.
func (u *AccountScheduleUserUpsert) SetQualityCondition(v string) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldQualityCondition, v)
	return u
}

// UpdateQualityCondition sets the "quality_condition" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateQualityCondition() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldQualityCondition)
	return u
}

// ClearQualityCondition clears the value of the "quality_condition" field.
func (u *AccountScheduleUserUpsert) ClearQualityCondition() *AccountScheduleUserUpsert {
	u.SetNull(accountscheduleuser.FieldQualityCondition)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountScheduleUserUpsertOne) UpdateNewValues() *AccountScheduleUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountscheduleuser.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountScheduleUserUpsertOne) Ignore() *AccountScheduleUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountScheduleUserUpsertOne) DoNothing() *AccountScheduleUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountScheduleUserCreate.OnConflict
// documentation for more info.
func (u *AccountScheduleUserUpsertOne) Update(set func(*AccountScheduleUserUpsert)) *AccountScheduleUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountScheduleUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountScheduleUserUpsertOne) SetAccountID(v int64) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateAccountID() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountScheduleUserUpsertOne) SetUserID(v int64) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateUserID() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateUserID()
	})
}

// SetAllow sets the "allow" field.
func (u *AccountScheduleUserUpsertOne) SetAllow(v bool) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetAllow(v)
	})
}

// UpdateAllow sets the "allow" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateAllow() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateAllow()
	})
}

// SetDeny sets the "deny" field.
func (u *AccountScheduleUserUpsertOne) SetDeny(v bool) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetDeny(v)
	})
}

// UpdateDeny sets the "deny" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateDeny() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateDeny()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *AccountScheduleUserUpsertOne) SetMaxConcurrency(v int) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *AccountScheduleUserUpsertOne) AddMaxConcurrency(v int) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateMaxConcurrency() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// ClearMaxConcurrency clears the value of the "max_concurrency" field.
func (u *AccountScheduleUserUpsertOne) ClearMaxConcurrency() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearMaxConcurrency()
	})
}

// SetQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field.
func (u *AccountScheduleUserUpsertOne) SetQualityMaxP50TtftMs(v int) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityMaxP50TtftMs(v)
	})
}

// AddQualityMaxP50TtftMs adds v to the "quality_max_p50_ttft_ms" field.
func (u *AccountScheduleUserUpsertOne) AddQualityMaxP50TtftMs(v int) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddQualityMaxP50TtftMs(v)
	})
}

// UpdateQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateQualityMaxP50TtftMs() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityMaxP50TtftMs()
	})
}

// ClearQualityMaxP50TtftMs clears the value of the "quality_max_p50_ttft_ms" field.
func (u *AccountScheduleUserUpsertOne) ClearQualityMaxP50TtftMs() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityMaxP50TtftMs()
	})
}

// SetQualityMinSuccessRate sets the "quality_min_success_rate" field.
func (u *AccountScheduleUserUpsertOne) SetQualityMinSuccessRate(v float64) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityMinSuccessRate(v)
	})
}

// AddQualityMinSuccessRate adds v to the "quality_min_success_rate" field.
func (u *AccountScheduleUserUpsertOne) AddQualityMinSuccessRate(v float64) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddQualityMinSuccessRate(v)
	})
}

// UpdateQualityMinSuccessRate sets the "quality_min_success_rate" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateQualityMinSuccessRate() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityMinSuccessRate()
	})
}

// ClearQualityMinSuccessRate clears the value of the "quality_min_success_rate" field.
func (u *AccountScheduleUserUpsertOne) ClearQualityMinSuccessRate() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityMinSuccessRate()
	})
}

// SetQualityMinSuccessSamples sets the "quality_min_success_samples" field.
func (u *AccountScheduleUserUpsertOne) SetQualityMinSuccessSamples(v int) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityMinSuccessSamples(v)
	})
}

// AddQualityMinSuccessSamples adds v to the "quality_min_success_samples" field.
func (u *AccountScheduleUserUpsertOne) AddQualityMinSuccessSamples(v int) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddQualityMinSuccessSamples(v)
	})
}

// UpdateQualityMinSuccessSamples sets the "quality_min_success_samples" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateQualityMinSuccessSamples() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityMinSuccessSamples()
	})
}

// ClearQualityMinSuccessSamples clears the value of the "quality_min_success_samples" field.
func (u *AccountScheduleUserUpsertOne) ClearQualityMinSuccessSamples() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityMinSuccessSamples()
	})
}

// SetQualityMinTtftSamples sets the "quality_min_ttft_samples" field.
func (u *AccountScheduleUserUpsertOne) SetQualityMinTtftSamples(v int) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityMinTtftSamples(v)
	})
}

// AddQualityMinTtftSamples adds v to the "quality_min_ttft_samples" field.
func (u *AccountScheduleUserUpsertOne) AddQualityMinTtftSamples(v int) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddQualityMinTtftSamples(v)
	})
}

// UpdateQualityMinTtftSamples sets the "quality_min_ttft_samples" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateQualityMinTtftSamples() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityMinTtftSamples()
	})
}

// ClearQualityMinTtftSamples clears the value of the "quality_min_ttft_samples" field.
func (u *AccountScheduleUserUpsertOne) ClearQualityMinTtftSamples() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityMinTtftSamples()
	})
}

// SetQualityCondition sets the "quality_condition" field.
func (u *AccountScheduleUserUpsertOne) SetQualityCondition(v string) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityCondition(v)
	})
}

// UpdateQualityCondition sets the "quality_condition" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateQualityCondition() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityCondition()
	})
}

// ClearQualityCondition clears the value of the "quality_condition" field.
func (u *AccountScheduleUserUpsertOne) ClearQualityCondition() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityCondition()
	})
}

// Exec executes the query.
func (u *AccountScheduleUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountScheduleUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountScheduleUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// AccountScheduleUserCreateBulk is the builder for creating many AccountScheduleUser entities in bulk.
type AccountScheduleUserCreateBulk struct {
	config
	err      error
	builders []*AccountScheduleUserCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountScheduleUser entities in the database.
func (_c *AccountScheduleUserCreateBulk) Save(ctx context.Context) ([]*AccountScheduleUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountScheduleUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountScheduleUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountScheduleUserCreateBulk) SaveX(ctx context.Context) []*AccountScheduleUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountScheduleUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountScheduleUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountScheduleUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountScheduleUserUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountScheduleUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountScheduleUserUpsertBulk {
	_c.conflict = opts
	return &AccountScheduleUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountScheduleUserCreateBulk) OnConflictColumns(columns ...string) *AccountScheduleUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountScheduleUserUpsertBulk{
		create: _c,
	}
}

// AccountScheduleUserUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountScheduleUser nodes.
type AccountScheduleUserUpsertBulk struct {
	create *AccountScheduleUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountScheduleUserUpsertBulk) UpdateNewValues() *AccountScheduleUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountscheduleuser.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountScheduleUserUpsertBulk) Ignore() *AccountScheduleUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountScheduleUserUpsertBulk) DoNothing() *AccountScheduleUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountScheduleUserCreateBulk.OnConflict
// documentation for more info.
func (u *AccountScheduleUserUpsertBulk) Update(set func(*AccountScheduleUserUpsert)) *AccountScheduleUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountScheduleUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountScheduleUserUpsertBulk) SetAccountID(v int64) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateAccountID() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountScheduleUserUpsertBulk) SetUserID(v int64) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateUserID() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateUserID()
	})
}

// SetAllow sets the "allow" field.
func (u *AccountScheduleUserUpsertBulk) SetAllow(v bool) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetAllow(v)
	})
}

// UpdateAllow sets the "allow" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateAllow() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateAllow()
	})
}

// SetDeny sets the "deny" field.
func (u *AccountScheduleUserUpsertBulk) SetDeny(v bool) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetDeny(v)
	})
}

// UpdateDeny sets the "deny" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateDeny() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateDeny()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *AccountScheduleUserUpsertBulk) SetMaxConcurrency(v int) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *AccountScheduleUserUpsertBulk) AddMaxConcurrency(v int) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateMaxConcurrency() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// ClearMaxConcurrency clears the value of the "max_concurrency" field.
func (u *AccountScheduleUserUpsertBulk) ClearMaxConcurrency() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearMaxConcurrency()
	})
}

// SetQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field.
func (u *AccountScheduleUserUpsertBulk) SetQualityMaxP50TtftMs(v int) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityMaxP50TtftMs(v)
	})
}

// AddQualityMaxP50TtftMs adds v to the "quality_max_p50_ttft_ms" field.
func (u *AccountScheduleUserUpsertBulk) AddQualityMaxP50TtftMs(v int) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddQualityMaxP50TtftMs(v)
	})
}

// UpdateQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateQualityMaxP50TtftMs() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityMaxP50TtftMs()
	})
}

// ClearQualityMaxP50TtftMs clears the value of the "quality_max_p50_ttft_ms" field.
func (u *AccountScheduleUserUpsertBulk) ClearQualityMaxP50TtftMs() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityMaxP50TtftMs()
	})
}

// SetQualityMinSuccessRate sets the "quality_min_success_rate" field.
func (u *AccountScheduleUserUpsertBulk) SetQualityMinSuccessRate(v float64) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityMinSuccessRate(v)
	})
}

// AddQualityMinSuccessRate adds v to the "quality_min_success_rate" field.
func (u *AccountScheduleUserUpsertBulk) AddQualityMinSuccessRate(v float64) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddQualityMinSuccessRate(v)
	})
}

// UpdateQualityMinSuccessRate sets the "quality_min_success_rate" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateQualityMinSuccessRate() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityMinSuccessRate()
	})
}

// ClearQualityMinSuccessRate clears the value of the "quality_min_success_rate" field.
func (u *AccountScheduleUserUpsertBulk) ClearQualityMinSuccessRate() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityMinSuccessRate()
	})
}

// SetQualityMinSuccessSamples sets the "quality_min_success_samples" field.
func (u *AccountScheduleUserUpsertBulk) SetQualityMinSuccessSamples(v int) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityMinSuccessSamples(v)
	})
}

// AddQualityMinSuccessSamples adds v to the "quality_min_success_samples" field.
func (u *AccountScheduleUserUpsertBulk) AddQualityMinSuccessSamples(v int) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddQualityMinSuccessSamples(v)
	})
}

// UpdateQualityMinSuccessSamples sets the "quality_min_success_samples" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateQualityMinSuccessSamples() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityMinSuccessSamples()
	})
}

// ClearQualityMinSuccessSamples clears the value of the "quality_min_success_samples" field.
func (u *AccountScheduleUserUpsertBulk) ClearQualityMinSuccessSamples() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityMinSuccessSamples()
	})
}

// SetQualityMinTtftSamples sets the "quality_min_ttft_samples" field.
func (u *AccountScheduleUserUpsertBulk) SetQualityMinTtftSamples(v int) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityMinTtftSamples(v)
	})
}

// AddQualityMinTtftSamples adds v to the "quality_min_ttft_samples" field.
func (u *AccountScheduleUserUpsertBulk) AddQualityMinTtftSamples(v int) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.AddQualityMinTtftSamples(v)
	})
}

// UpdateQualityMinTtftSamples sets the "quality_min_ttft_samples" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateQualityMinTtftSamples() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityMinTtftSamples()
	})
}

// ClearQualityMinTtftSamples clears the value of the "quality_min_ttft_samples" field.
func (u *AccountScheduleUserUpsertBulk) ClearQualityMinTtftSamples() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityMinTtftSamples()
	})
}

// SetQualityCondition sets the "quality_condition" field.
func (u *AccountScheduleUserUpsertBulk) SetQualityCondition(v string) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetQualityCondition(v)
	})
}

// UpdateQualityCondition sets the "quality_condition" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateQualityCondition() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateQualityCondition()
	})
}

// ClearQualityCondition clears the value of the "quality_condition" field.
func (u *AccountScheduleUserUpsertBulk) ClearQualityCondition() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.ClearQualityCondition()
	})
}

// Exec executes the query.
func (u *AccountScheduleUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountScheduleUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountScheduleUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountScheduleUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
