// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountscheduleuser"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountScheduleUserCreate is the builder for creating a AccountScheduleUser entity.
type AccountScheduleUserCreate struct {
	config
	mutation *AccountScheduleUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountScheduleUserCreate) SetAccountID(v int64) *AccountScheduleUserCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountScheduleUserCreate) SetUserID(v int64) *AccountScheduleUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountScheduleUserCreate) SetCreatedAt(v time.Time) *AccountScheduleUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountScheduleUserCreate) SetNillableCreatedAt(v *time.Time) *AccountScheduleUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountScheduleUserCreate) SetAccount(v *Account) *AccountScheduleUserCreate {
	return _c.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccountScheduleUserCreate) SetUser(v *User) *AccountScheduleUserCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AccountScheduleUserMutation object of the builder.
func (_c *AccountScheduleUserCreate) Mutation() *AccountScheduleUserMutation {
	return _c.mutation
}

// Save creates the AccountScheduleUser in the database.
func (_c *AccountScheduleUserCreate) Save(ctx context.Context) (*AccountScheduleUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountScheduleUserCreate) SaveX(ctx context.Context) *AccountScheduleUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountScheduleUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountScheduleUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountScheduleUserCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountscheduleuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountScheduleUserCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountScheduleUser.account_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AccountScheduleUser.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountScheduleUser.created_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountScheduleUser.account"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AccountScheduleUser.user"`)}
	}
	return nil
}

func (_c *AccountScheduleUserCreate) sqlSave(ctx context.Context) (*AccountScheduleUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *AccountScheduleUserCreate) createSpec() (*AccountScheduleUser, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountScheduleUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountscheduleuser.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountscheduleuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.AccountTable,
			Columns: []string{accountscheduleuser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.UserTable,
			Columns: []string{accountscheduleuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountScheduleUser.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountScheduleUserUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountScheduleUserCreate) OnConflict(opts ...sql.ConflictOption) *AccountScheduleUserUpsertOne {
	_c.conflict = opts
	return &AccountScheduleUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountScheduleUserCreate) OnConflictColumns(columns ...string) *AccountScheduleUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountScheduleUserUpsertOne{
		create: _c,
	}
}

type (
	// AccountScheduleUserUpsertOne is the builder for "upsert"-ing
	//  one AccountScheduleUser node.
	AccountScheduleUserUpsertOne struct {
		create *AccountScheduleUserCreate
	}

	// AccountScheduleUserUpsert is the "OnConflict" setter.
	AccountScheduleUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountScheduleUserUpsert) SetAccountID(v int64) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateAccountID() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldAccountID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountScheduleUserUpsert) SetUserID(v int64) *AccountScheduleUserUpsert {
	u.Set(accountscheduleuser.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsert) UpdateUserID() *AccountScheduleUserUpsert {
	u.SetExcluded(accountscheduleuser.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountScheduleUserUpsertOne) UpdateNewValues() *AccountScheduleUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountscheduleuser.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountScheduleUserUpsertOne) Ignore() *AccountScheduleUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountScheduleUserUpsertOne) DoNothing() *AccountScheduleUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountScheduleUserCreate.OnConflict
// documentation for more info.
func (u *AccountScheduleUserUpsertOne) Update(set func(*AccountScheduleUserUpsert)) *AccountScheduleUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountScheduleUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountScheduleUserUpsertOne) SetAccountID(v int64) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateAccountID() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountScheduleUserUpsertOne) SetUserID(v int64) *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertOne) UpdateUserID() *AccountScheduleUserUpsertOne {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *AccountScheduleUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountScheduleUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountScheduleUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// AccountScheduleUserCreateBulk is the builder for creating many AccountScheduleUser entities in bulk.
type AccountScheduleUserCreateBulk struct {
	config
	err      error
	builders []*AccountScheduleUserCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountScheduleUser entities in the database.
func (_c *AccountScheduleUserCreateBulk) Save(ctx context.Context) ([]*AccountScheduleUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountScheduleUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountScheduleUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountScheduleUserCreateBulk) SaveX(ctx context.Context) []*AccountScheduleUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountScheduleUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountScheduleUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountScheduleUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountScheduleUserUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountScheduleUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountScheduleUserUpsertBulk {
	_c.conflict = opts
	return &AccountScheduleUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountScheduleUserCreateBulk) OnConflictColumns(columns ...string) *AccountScheduleUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountScheduleUserUpsertBulk{
		create: _c,
	}
}

// AccountScheduleUserUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountScheduleUser nodes.
type AccountScheduleUserUpsertBulk struct {
	create *AccountScheduleUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountScheduleUserUpsertBulk) UpdateNewValues() *AccountScheduleUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountscheduleuser.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountScheduleUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountScheduleUserUpsertBulk) Ignore() *AccountScheduleUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountScheduleUserUpsertBulk) DoNothing() *AccountScheduleUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountScheduleUserCreateBulk.OnConflict
// documentation for more info.
func (u *AccountScheduleUserUpsertBulk) Update(set func(*AccountScheduleUserUpsert)) *AccountScheduleUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountScheduleUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountScheduleUserUpsertBulk) SetAccountID(v int64) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateAccountID() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountScheduleUserUpsertBulk) SetUserID(v int64) *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountScheduleUserUpsertBulk) UpdateUserID() *AccountScheduleUserUpsertBulk {
	return u.Update(func(s *AccountScheduleUserUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *AccountScheduleUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountScheduleUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountScheduleUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountScheduleUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
