// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountscheduleuser"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountScheduleUserUpdate is the builder for updating AccountScheduleUser entities.
type AccountScheduleUserUpdate struct {
	config
	hooks    []Hook
	mutation *AccountScheduleUserMutation
}

// Where appends a list predicates to the AccountScheduleUserUpdate builder.
func (_u *AccountScheduleUserUpdate) Where(ps ...predicate.AccountScheduleUser) *AccountScheduleUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountScheduleUserUpdate) SetAccountID(v int64) *AccountScheduleUserUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableAccountID(v *int64) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountScheduleUserUpdate) SetUserID(v int64) *AccountScheduleUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableUserID(v *int64) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAllow sets the "allow" field.
func (_u *AccountScheduleUserUpdate) SetAllow(v bool) *AccountScheduleUserUpdate {
	_u.mutation.SetAllow(v)
	return _u
}

// SetNillableAllow sets the "allow" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableAllow(v *bool) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetAllow(*v)
	}
	return _u
}

// SetDeny sets the "deny" field.
func (_u *AccountScheduleUserUpdate) SetDeny(v bool) *AccountScheduleUserUpdate {
	_u.mutation.SetDeny(v)
	return _u
}

// SetNillableDeny sets the "deny" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableDeny(v *bool) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetDeny(*v)
	}
	return _u
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (_u *AccountScheduleUserUpdate) SetMaxConcurrency(v int) *AccountScheduleUserUpdate {
	_u.mutation.ResetMaxConcurrency()
	_u.mutation.SetMaxConcurrency(v)
	return _u
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableMaxConcurrency(v *int) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetMaxConcurrency(*v)
	}
	return _u
}

// AddMaxConcurrency adds value to the "max_concurrency" field.
func (_u *AccountScheduleUserUpdate) AddMaxConcurrency(v int) *AccountScheduleUserUpdate {
	_u.mutation.AddMaxConcurrency(v)
	return _u
}

// ClearMaxConcurrency clears the value of the "max_concurrency" field.
func (_u *AccountScheduleUserUpdate) ClearMaxConcurrency() *AccountScheduleUserUpdate {
	_u.mutation.ClearMaxConcurrency()
	return _u
}

// SetQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field.
func (_u *AccountScheduleUserUpdate) SetQualityMaxP50TtftMs(v int) *AccountScheduleUserUpdate {
	_u.mutation.ResetQualityMaxP50TtftMs()
	_u.mutation.SetQualityMaxP50TtftMs(v)
	return _u
}

// SetNillableQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableQualityMaxP50TtftMs(v *int) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetQualityMaxP50TtftMs(*v)
	}
	return _u
}

// AddQualityMaxP50TtftMs adds value to the "quality_max_p50_ttft_ms" field.
func (_u *AccountScheduleUserUpdate) AddQualityMaxP50TtftMs(v int) *AccountScheduleUserUpdate {
	_u.mutation.AddQualityMaxP50TtftMs(v)
	return _u
}

// ClearQualityMaxP50TtftMs clears the value of the "quality_max_p50_ttft_ms" field.
func (_u *AccountScheduleUserUpdate) ClearQualityMaxP50TtftMs() *AccountScheduleUserUpdate {
	_u.mutation.ClearQualityMaxP50TtftMs()
	return _u
}

// SetQualityMinSuccessRate sets the "quality_min_success_rate" field.
func (_u *AccountScheduleUserUpdate) SetQualityMinSuccessRate(v float64) *AccountScheduleUserUpdate {
	_u.mutation.ResetQualityMinSuccessRate()
	_u.mutation.SetQualityMinSuccessRate(v)
	return _u
}

// SetNillableQualityMinSuccessRate sets the "quality_min_success_rate" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableQualityMinSuccessRate(v *float64) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetQualityMinSuccessRate(*v)
	}
	return _u
}

// AddQualityMinSuccessRate adds value to the "quality_min_success_rate" field.
func (_u *AccountScheduleUserUpdate) AddQualityMinSuccessRate(v float64) *AccountScheduleUserUpdate {
	_u.mutation.AddQualityMinSuccessRate(v)
	return _u
}

// ClearQualityMinSuccessRate clears the value of the "quality_min_success_rate" field.
func (_u *AccountScheduleUserUpdate) ClearQualityMinSuccessRate() *AccountScheduleUserUpdate {
	_u.mutation.ClearQualityMinSuccessRate()
	return _u
}

// SetQualityMinSuccessSamples sets the "quality_min_success_samples" field.
func (_u *AccountScheduleUserUpdate) SetQualityMinSuccessSamples(v int) *AccountScheduleUserUpdate {
	_u.mutation.ResetQualityMinSuccessSamples()
	_u.mutation.SetQualityMinSuccessSamples(v)
	return _u
}

// SetNillableQualityMinSuccessSamples sets the "quality_min_success_samples" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableQualityMinSuccessSamples(v *int) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetQualityMinSuccessSamples(*v)
	}
	return _u
}

// AddQualityMinSuccessSamples adds value to the "quality_min_success_samples" field.
func (_u *AccountScheduleUserUpdate) AddQualityMinSuccessSamples(v int) *AccountScheduleUserUpdate {
	_u.mutation.AddQualityMinSuccessSamples(v)
	return _u
}

// ClearQualityMinSuccessSamples clears the value of the "quality_min_success_samples" field.
func (_u *AccountScheduleUserUpdate) ClearQualityMinSuccessSamples() *AccountScheduleUserUpdate {
	_u.mutation.ClearQualityMinSuccessSamples()
	return _u
}

// SetQualityMinTtftSamples sets the "quality_min_ttft_samples" field.
func (_u *AccountScheduleUserUpdate) SetQualityMinTtftSamples(v int) *AccountScheduleUserUpdate {
	_u.mutation.ResetQualityMinTtftSamples()
	_u.mutation.SetQualityMinTtftSamples(v)
	return _u
}

// SetNillableQualityMinTtftSamples sets the "quality_min_ttft_samples" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableQualityMinTtftSamples(v *int) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetQualityMinTtftSamples(*v)
	}
	return _u
}

// AddQualityMinTtftSamples adds value to the "quality_min_ttft_samples" field.
func (_u *AccountScheduleUserUpdate) AddQualityMinTtftSamples(v int) *AccountScheduleUserUpdate {
	_u.mutation.AddQualityMinTtftSamples(v)
	return _u
}

// ClearQualityMinTtftSamples clears the value of the "quality_min_ttft_samples" field.
func (_u *AccountScheduleUserUpdate) ClearQualityMinTtftSamples() *AccountScheduleUserUpdate {
	_u.mutation.ClearQualityMinTtftSamples()
	return _u
}

// SetQualityCondition sets the "quality_condition" field.
func (_u *AccountScheduleUserUpdate) SetQualityCondition(v string) *AccountScheduleUserUpdate {
	_u.mutation.SetQualityCondition(v)
	return _u
}

// SetNillableQualityCondition sets the "quality_condition" field if the given value is not nil.
func (_u *AccountScheduleUserUpdate) SetNillableQualityCondition(v *string) *AccountScheduleUserUpdate {
	if v != nil {
		_u.SetQualityCondition(*v)
	}
	return _u
}

// ClearQualityCondition clears the value of the "quality_condition" field.
func (_u *AccountScheduleUserUpdate) ClearQualityCondition() *AccountScheduleUserUpdate {
	_u.mutation.ClearQualityCondition()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountScheduleUserUpdate) SetAccount(v *Account) *AccountScheduleUserUpdate {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountScheduleUserUpdate) SetUser(v *User) *AccountScheduleUserUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountScheduleUserMutation object of the builder.
func (_u *AccountScheduleUserUpdate) Mutation() *AccountScheduleUserMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountScheduleUserUpdate) ClearAccount() *AccountScheduleUserUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountScheduleUserUpdate) ClearUser() *AccountScheduleUserUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountScheduleUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountScheduleUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountScheduleUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountScheduleUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountScheduleUserUpdate) check() error {
	if v, ok := _u.mutation.QualityCondition(); ok {
		if err := accountscheduleuser.QualityConditionValidator(v); err != nil {
			return &ValidationError{Name: "quality_condition", err: fmt.Errorf(`ent: validator failed for field "AccountScheduleUser.quality_condition": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountScheduleUser.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountScheduleUser.user"`)
	}
	return nil
}

func (_u *AccountScheduleUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountscheduleuser.Table, accountscheduleuser.Columns, sqlgraph.NewFieldSpec(accountscheduleuser.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accountscheduleuser.FieldUserID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Allow(); ok {
		_spec.SetField(accountscheduleuser.FieldAllow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Deny(); ok {
		_spec.SetField(accountscheduleuser.FieldDeny, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxConcurrency(); ok {
		_spec.SetField(accountscheduleuser.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrency(); ok {
		_spec.AddField(accountscheduleuser.FieldMaxConcurrency, field.TypeInt, value)
	}
	if _u.mutation.MaxConcurrencyCleared() {
		_spec.ClearField(accountscheduleuser.FieldMaxConcurrency, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMaxP50TtftMs(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMaxP50TtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMaxP50TtftMs(); ok {
		_spec.AddField(accountscheduleuser.FieldQualityMaxP50TtftMs, field.TypeInt, value)
	}
	if _u.mutation.QualityMaxP50TtftMsCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityMaxP50TtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMinSuccessRate(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMinSuccessRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQualityMinSuccessRate(); ok {
		_spec.AddField(accountscheduleuser.FieldQualityMinSuccessRate, field.TypeFloat64, value)
	}
	if _u.mutation.QualityMinSuccessRateCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityMinSuccessRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QualityMinSuccessSamples(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMinSuccessSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMinSuccessSamples(); ok {
		_spec.AddField(accountscheduleuser.FieldQualityMinSuccessSamples, field.TypeInt, value)
	}
	if _u.mutation.QualityMinSuccessSamplesCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityMinSuccessSamples, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMinTtftSamples(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMinTtftSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMinTtftSamples(); ok {
		_spec.AddField(accountscheduleuser.FieldQualityMinTtftSamples, field.TypeInt, value)
	}
	if _u.mutation.QualityMinTtftSamplesCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityMinTtftSamples, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityCondition(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityCondition, field.TypeString, value)
	}
	if _u.mutation.QualityConditionCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityCondition, field.TypeString)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.AccountTable,
			Columns: []string{accountscheduleuser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.AccountTable,
			Columns: []string{accountscheduleuser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.UserTable,
			Columns: []string{accountscheduleuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.UserTable,
			Columns: []string{accountscheduleuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountscheduleuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountScheduleUserUpdateOne is the builder for updating a single AccountScheduleUser entity.
type AccountScheduleUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountScheduleUserMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountScheduleUserUpdateOne) SetAccountID(v int64) *AccountScheduleUserUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableAccountID(v *int64) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountScheduleUserUpdateOne) SetUserID(v int64) *AccountScheduleUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableUserID(v *int64) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAllow sets the "allow" field.
func (_u *AccountScheduleUserUpdateOne) SetAllow(v bool) *AccountScheduleUserUpdateOne {
	_u.mutation.SetAllow(v)
	return _u
}

// SetNillableAllow sets the "allow" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableAllow(v *bool) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetAllow(*v)
	}
	return _u
}

// SetDeny sets the "deny" field.
func (_u *AccountScheduleUserUpdateOne) SetDeny(v bool) *AccountScheduleUserUpdateOne {
	_u.mutation.SetDeny(v)
	return _u
}

// SetNillableDeny sets the "deny" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableDeny(v *bool) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetDeny(*v)
	}
	return _u
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (_u *AccountScheduleUserUpdateOne) SetMaxConcurrency(v int) *AccountScheduleUserUpdateOne {
	_u.mutation.ResetMaxConcurrency()
	_u.mutation.SetMaxConcurrency(v)
	return _u
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableMaxConcurrency(v *int) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetMaxConcurrency(*v)
	}
	return _u
}

// AddMaxConcurrency adds value to the "max_concurrency" field.
func (_u *AccountScheduleUserUpdateOne) AddMaxConcurrency(v int) *AccountScheduleUserUpdateOne {
	_u.mutation.AddMaxConcurrency(v)
	return _u
}

// ClearMaxConcurrency clears the value of the "max_concurrency" field.
func (_u *AccountScheduleUserUpdateOne) ClearMaxConcurrency() *AccountScheduleUserUpdateOne {
	_u.mutation.ClearMaxConcurrency()
	return _u
}

// SetQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field.
func (_u *AccountScheduleUserUpdateOne) SetQualityMaxP50TtftMs(v int) *AccountScheduleUserUpdateOne {
	_u.mutation.ResetQualityMaxP50TtftMs()
	_u.mutation.SetQualityMaxP50TtftMs(v)
	return _u
}

// SetNillableQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableQualityMaxP50TtftMs(v *int) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetQualityMaxP50TtftMs(*v)
	}
	return _u
}

// AddQualityMaxP50TtftMs adds value to the "quality_max_p50_ttft_ms" field.
func (_u *AccountScheduleUserUpdateOne) AddQualityMaxP50TtftMs(v int) *AccountScheduleUserUpdateOne {
	_u.mutation.AddQualityMaxP50TtftMs(v)
	return _u
}

// ClearQualityMaxP50TtftMs clears the value of the "quality_max_p50_ttft_ms" field.
func (_u *AccountScheduleUserUpdateOne) ClearQualityMaxP50TtftMs() *AccountScheduleUserUpdateOne {
	_u.mutation.ClearQualityMaxP50TtftMs()
	return _u
}

// SetQualityMinSuccessRate sets the "quality_min_success_rate" field.
func (_u *AccountScheduleUserUpdateOne) SetQualityMinSuccessRate(v float64) *AccountScheduleUserUpdateOne {
	_u.mutation.ResetQualityMinSuccessRate()
	_u.mutation.SetQualityMinSuccessRate(v)
	return _u
}

// SetNillableQualityMinSuccessRate sets the "quality_min_success_rate" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableQualityMinSuccessRate(v *float64) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetQualityMinSuccessRate(*v)
	}
	return _u
}

// AddQualityMinSuccessRate adds value to the "quality_min_success_rate" field.
func (_u *AccountScheduleUserUpdateOne) AddQualityMinSuccessRate(v float64) *AccountScheduleUserUpdateOne {
	_u.mutation.AddQualityMinSuccessRate(v)
	return _u
}

// ClearQualityMinSuccessRate clears the value of the "quality_min_success_rate" field.
func (_u *AccountScheduleUserUpdateOne) ClearQualityMinSuccessRate() *AccountScheduleUserUpdateOne {
	_u.mutation.ClearQualityMinSuccessRate()
	return _u
}

// SetQualityMinSuccessSamples sets the "quality_min_success_samples" field.
func (_u *AccountScheduleUserUpdateOne) SetQualityMinSuccessSamples(v int) *AccountScheduleUserUpdateOne {
	_u.mutation.ResetQualityMinSuccessSamples()
	_u.mutation.SetQualityMinSuccessSamples(v)
	return _u
}

// SetNillableQualityMinSuccessSamples sets the "quality_min_success_samples" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableQualityMinSuccessSamples(v *int) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetQualityMinSuccessSamples(*v)
	}
	return _u
}

// AddQualityMinSuccessSamples adds value to the "quality_min_success_samples" field.
func (_u *AccountScheduleUserUpdateOne) AddQualityMinSuccessSamples(v int) *AccountScheduleUserUpdateOne {
	_u.mutation.AddQualityMinSuccessSamples(v)
	return _u
}

// ClearQualityMinSuccessSamples clears the value of the "quality_min_success_samples" field.
func (_u *AccountScheduleUserUpdateOne) ClearQualityMinSuccessSamples() *AccountScheduleUserUpdateOne {
	_u.mutation.ClearQualityMinSuccessSamples()
	return _u
}

// SetQualityMinTtftSamples sets the "quality_min_ttft_samples" field.
func (_u *AccountScheduleUserUpdateOne) SetQualityMinTtftSamples(v int) *AccountScheduleUserUpdateOne {
	_u.mutation.ResetQualityMinTtftSamples()
	_u.mutation.SetQualityMinTtftSamples(v)
	return _u
}

// SetNillableQualityMinTtftSamples sets the "quality_min_ttft_samples" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableQualityMinTtftSamples(v *int) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetQualityMinTtftSamples(*v)
	}
	return _u
}

// AddQualityMinTtftSamples adds value to the "quality_min_ttft_samples" field.
func (_u *AccountScheduleUserUpdateOne) AddQualityMinTtftSamples(v int) *AccountScheduleUserUpdateOne {
	_u.mutation.AddQualityMinTtftSamples(v)
	return _u
}

// ClearQualityMinTtftSamples clears the value of the "quality_min_ttft_samples" field.
func (_u *AccountScheduleUserUpdateOne) ClearQualityMinTtftSamples() *AccountScheduleUserUpdateOne {
	_u.mutation.ClearQualityMinTtftSamples()
	return _u
}

// SetQualityCondition sets the "quality_condition" field.
func (_u *AccountScheduleUserUpdateOne) SetQualityCondition(v string) *AccountScheduleUserUpdateOne {
	_u.mutation.SetQualityCondition(v)
	return _u
}

// SetNillableQualityCondition sets the "quality_condition" field if the given value is not nil.
func (_u *AccountScheduleUserUpdateOne) SetNillableQualityCondition(v *string) *AccountScheduleUserUpdateOne {
	if v != nil {
		_u.SetQualityCondition(*v)
	}
	return _u
}

// ClearQualityCondition clears the value of the "quality_condition" field.
func (_u *AccountScheduleUserUpdateOne) ClearQualityCondition() *AccountScheduleUserUpdateOne {
	_u.mutation.ClearQualityCondition()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountScheduleUserUpdateOne) SetAccount(v *Account) *AccountScheduleUserUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountScheduleUserUpdateOne) SetUser(v *User) *AccountScheduleUserUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountScheduleUserMutation object of the builder.
func (_u *AccountScheduleUserUpdateOne) Mutation() *AccountScheduleUserMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountScheduleUserUpdateOne) ClearAccount() *AccountScheduleUserUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountScheduleUserUpdateOne) ClearUser() *AccountScheduleUserUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AccountScheduleUserUpdate builder.
func (_u *AccountScheduleUserUpdateOne) Where(ps ...predicate.AccountScheduleUser) *AccountScheduleUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountScheduleUserUpdateOne) Select(field string, fields ...string) *AccountScheduleUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountScheduleUser entity.
func (_u *AccountScheduleUserUpdateOne) Save(ctx context.Context) (*AccountScheduleUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountScheduleUserUpdateOne) SaveX(ctx context.Context) *AccountScheduleUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountScheduleUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountScheduleUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountScheduleUserUpdateOne) check() error {
	if v, ok := _u.mutation.QualityCondition(); ok {
		if err := accountscheduleuser.QualityConditionValidator(v); err != nil {
			return &ValidationError{Name: "quality_condition", err: fmt.Errorf(`ent: validator failed for field "AccountScheduleUser.quality_condition": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountScheduleUser.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountScheduleUser.user"`)
	}
	return nil
}

func (_u *AccountScheduleUserUpdateOne) sqlSave(ctx context.Context) (_node *AccountScheduleUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountscheduleuser.Table, accountscheduleuser.Columns, sqlgraph.NewFieldSpec(accountscheduleuser.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accountscheduleuser.FieldUserID, field.TypeInt64))
	if id, ok := _u.mutation.AccountID(); !ok {
		return nil, &ValidationError{Name: "account_id", err: errors.New(`ent: missing "AccountScheduleUser.account_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "AccountScheduleUser.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !accountscheduleuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Allow(); ok {
		_spec.SetField(accountscheduleuser.FieldAllow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Deny(); ok {
		_spec.SetField(accountscheduleuser.FieldDeny, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxConcurrency(); ok {
		_spec.SetField(accountscheduleuser.FieldMaxConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrency(); ok {
		_spec.AddField(accountscheduleuser.FieldMaxConcurrency, field.TypeInt, value)
	}
	if _u.mutation.MaxConcurrencyCleared() {
		_spec.ClearField(accountscheduleuser.FieldMaxConcurrency, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMaxP50TtftMs(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMaxP50TtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMaxP50TtftMs(); ok {
		_spec.AddField(accountscheduleuser.FieldQualityMaxP50TtftMs, field.TypeInt, value)
	}
	if _u.mutation.QualityMaxP50TtftMsCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityMaxP50TtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMinSuccessRate(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMinSuccessRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQualityMinSuccessRate(); ok {
		_spec.AddField(accountscheduleuser.FieldQualityMinSuccessRate, field.TypeFloat64, value)
	}
	if _u.mutation.QualityMinSuccessRateCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityMinSuccessRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QualityMinSuccessSamples(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMinSuccessSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMinSuccessSamples(); ok {
		_spec.AddField(accountscheduleuser.FieldQualityMinSuccessSamples, field.TypeInt, value)
	}
	if _u.mutation.QualityMinSuccessSamplesCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityMinSuccessSamples, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMinTtftSamples(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityMinTtftSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMinTtftSamples(); ok {
		_spec.AddField(accountscheduleuser.FieldQualityMinTtftSamples, field.TypeInt, value)
	}
	if _u.mutation.QualityMinTtftSamplesCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityMinTtftSamples, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityCondition(); ok {
		_spec.SetField(accountscheduleuser.FieldQualityCondition, field.TypeString, value)
	}
	if _u.mutation.QualityConditionCleared() {
		_spec.ClearField(accountscheduleuser.FieldQualityCondition, field.TypeString)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.AccountTable,
			Columns: []string{accountscheduleuser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.AccountTable,
			Columns: []string{accountscheduleuser.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.UserTable,
			Columns: []string{accountscheduleuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountscheduleuser.UserTable,
			Columns: []string{accountscheduleuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountScheduleUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountscheduleuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
