// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountqualitysnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountQualitySnapshotUpdate is the builder for updating AccountQualitySnapshot entities.
type AccountQualitySnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *AccountQualitySnapshotMutation
}

// Where appends a list predicates to the AccountQualitySnapshotUpdate builder.
func (_u *AccountQualitySnapshotUpdate) Where(ps ...predicate.AccountQualitySnapshot) *AccountQualitySnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountQualitySnapshotUpdate) SetAccountID(v int64) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableAccountID(v *int64) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountQualitySnapshotUpdate) AddAccountID(v int64) *AccountQualitySnapshotUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *AccountQualitySnapshotUpdate) SetCapturedAt(v time.Time) *AccountQualitySnapshotUpdate {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableCapturedAt(v *time.Time) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// SetWindowSeconds sets the "window_seconds" field.
func (_u *AccountQualitySnapshotUpdate) SetWindowSeconds(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetWindowSeconds()
	_u.mutation.SetWindowSeconds(v)
	return _u
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableWindowSeconds(v *int) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetWindowSeconds(*v)
	}
	return _u
}

// AddWindowSeconds adds value to the "window_seconds" field.
func (_u *AccountQualitySnapshotUpdate) AddWindowSeconds(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.AddWindowSeconds(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *AccountQualitySnapshotUpdate) SetSuccessCount(v int64) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableSuccessCount(v *int64) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *AccountQualitySnapshotUpdate) AddSuccessCount(v int64) *AccountQualitySnapshotUpdate {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *AccountQualitySnapshotUpdate) SetErrorCount(v int64) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableErrorCount(v *int64) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *AccountQualitySnapshotUpdate) AddErrorCount(v int64) *AccountQualitySnapshotUpdate {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetTtftSamples sets the "ttft_samples" field.
func (_u *AccountQualitySnapshotUpdate) SetTtftSamples(v int64) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetTtftSamples()
	_u.mutation.SetTtftSamples(v)
	return _u
}

// SetNillableTtftSamples sets the "ttft_samples" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableTtftSamples(v *int64) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetTtftSamples(*v)
	}
	return _u
}

// AddTtftSamples adds value to the "ttft_samples" field.
func (_u *AccountQualitySnapshotUpdate) AddTtftSamples(v int64) *AccountQualitySnapshotUpdate {
	_u.mutation.AddTtftSamples(v)
	return _u
}

// SetSuccessRate sets the "success_rate" field.
func (_u *AccountQualitySnapshotUpdate) SetSuccessRate(v float64) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetSuccessRate()
	_u.mutation.SetSuccessRate(v)
	return _u
}

// SetNillableSuccessRate sets the "success_rate" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableSuccessRate(v *float64) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetSuccessRate(*v)
	}
	return _u
}

// AddSuccessRate adds value to the "success_rate" field.
func (_u *AccountQualitySnapshotUpdate) AddSuccessRate(v float64) *AccountQualitySnapshotUpdate {
	_u.mutation.AddSuccessRate(v)
	return _u
}

// ClearSuccessRate clears the value of the "success_rate" field.
func (_u *AccountQualitySnapshotUpdate) ClearSuccessRate() *AccountQualitySnapshotUpdate {
	_u.mutation.ClearSuccessRate()
	return _u
}

// SetAvgTtftMs sets the "avg_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) SetAvgTtftMs(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetAvgTtftMs()
	_u.mutation.SetAvgTtftMs(v)
	return _u
}

// SetNillableAvgTtftMs sets the "avg_ttft_ms" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableAvgTtftMs(v *int) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetAvgTtftMs(*v)
	}
	return _u
}

// AddAvgTtftMs adds value to the "avg_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) AddAvgTtftMs(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.AddAvgTtftMs(v)
	return _u
}

// ClearAvgTtftMs clears the value of the "avg_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) ClearAvgTtftMs() *AccountQualitySnapshotUpdate {
	_u.mutation.ClearAvgTtftMs()
	return _u
}

// SetP50TtftMs sets the "p50_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) SetP50TtftMs(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetP50TtftMs()
	_u.mutation.SetP50TtftMs(v)
	return _u
}

// SetNillableP50TtftMs sets the "p50_ttft_ms" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableP50TtftMs(v *int) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetP50TtftMs(*v)
	}
	return _u
}

// AddP50TtftMs adds value to the "p50_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) AddP50TtftMs(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.AddP50TtftMs(v)
	return _u
}

// ClearP50TtftMs clears the value of the "p50_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) ClearP50TtftMs() *AccountQualitySnapshotUpdate {
	_u.mutation.ClearP50TtftMs()
	return _u
}

// SetP95TtftMs sets the "p95_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) SetP95TtftMs(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetP95TtftMs()
	_u.mutation.SetP95TtftMs(v)
	return _u
}

// SetNillableP95TtftMs sets the "p95_ttft_ms" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableP95TtftMs(v *int) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetP95TtftMs(*v)
	}
	return _u
}

// AddP95TtftMs adds value to the "p95_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) AddP95TtftMs(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.AddP95TtftMs(v)
	return _u
}

// ClearP95TtftMs clears the value of the "p95_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) ClearP95TtftMs() *AccountQualitySnapshotUpdate {
	_u.mutation.ClearP95TtftMs()
	return _u
}

// SetMaxTtftMs sets the "max_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) SetMaxTtftMs(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.ResetMaxTtftMs()
	_u.mutation.SetMaxTtftMs(v)
	return _u
}

// SetNillableMaxTtftMs sets the "max_ttft_ms" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdate) SetNillableMaxTtftMs(v *int) *AccountQualitySnapshotUpdate {
	if v != nil {
		_u.SetMaxTtftMs(*v)
	}
	return _u
}

// AddMaxTtftMs adds value to the "max_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) AddMaxTtftMs(v int) *AccountQualitySnapshotUpdate {
	_u.mutation.AddMaxTtftMs(v)
	return _u
}

// ClearMaxTtftMs clears the value of the "max_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdate) ClearMaxTtftMs() *AccountQualitySnapshotUpdate {
	_u.mutation.ClearMaxTtftMs()
	return _u
}

// Mutation returns the AccountQualitySnapshotMutation object of the builder.
func (_u *AccountQualitySnapshotUpdate) Mutation() *AccountQualitySnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountQualitySnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountQualitySnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountQualitySnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountQualitySnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AccountQualitySnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(accountqualitysnapshot.Table, accountqualitysnapshot.Columns, sqlgraph.NewFieldSpec(accountqualitysnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountqualitysnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountqualitysnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(accountqualitysnapshot.FieldCapturedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WindowSeconds(); ok {
		_spec.SetField(accountqualitysnapshot.FieldWindowSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWindowSeconds(); ok {
		_spec.AddField(accountqualitysnapshot.FieldWindowSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(accountqualitysnapshot.FieldSuccessCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(accountqualitysnapshot.FieldSuccessCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(accountqualitysnapshot.FieldErrorCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(accountqualitysnapshot.FieldErrorCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtftSamples(); ok {
		_spec.SetField(accountqualitysnapshot.FieldTtftSamples, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtftSamples(); ok {
		_spec.AddField(accountqualitysnapshot.FieldTtftSamples, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SuccessRate(); ok {
		_spec.SetField(accountqualitysnapshot.FieldSuccessRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSuccessRate(); ok {
		_spec.AddField(accountqualitysnapshot.FieldSuccessRate, field.TypeFloat64, value)
	}
	if _u.mutation.SuccessRateCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldSuccessRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AvgTtftMs(); ok {
		_spec.SetField(accountqualitysnapshot.FieldAvgTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvgTtftMs(); ok {
		_spec.AddField(accountqualitysnapshot.FieldAvgTtftMs, field.TypeInt, value)
	}
	if _u.mutation.AvgTtftMsCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldAvgTtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.P50TtftMs(); ok {
		_spec.SetField(accountqualitysnapshot.FieldP50TtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedP50TtftMs(); ok {
		_spec.AddField(accountqualitysnapshot.FieldP50TtftMs, field.TypeInt, value)
	}
	if _u.mutation.P50TtftMsCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldP50TtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.P95TtftMs(); ok {
		_spec.SetField(accountqualitysnapshot.FieldP95TtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedP95TtftMs(); ok {
		_spec.AddField(accountqualitysnapshot.FieldP95TtftMs, field.TypeInt, value)
	}
	if _u.mutation.P95TtftMsCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldP95TtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxTtftMs(); ok {
		_spec.SetField(accountqualitysnapshot.FieldMaxTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTtftMs(); ok {
		_spec.AddField(accountqualitysnapshot.FieldMaxTtftMs, field.TypeInt, value)
	}
	if _u.mutation.MaxTtftMsCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldMaxTtftMs, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountqualitysnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountQualitySnapshotUpdateOne is the builder for updating a single AccountQualitySnapshot entity.
type AccountQualitySnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountQualitySnapshotMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountQualitySnapshotUpdateOne) SetAccountID(v int64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableAccountID(v *int64) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountQualitySnapshotUpdateOne) AddAccountID(v int64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *AccountQualitySnapshotUpdateOne) SetCapturedAt(v time.Time) *AccountQualitySnapshotUpdateOne {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableCapturedAt(v *time.Time) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// SetWindowSeconds sets the "window_seconds" field.
func (_u *AccountQualitySnapshotUpdateOne) SetWindowSeconds(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetWindowSeconds()
	_u.mutation.SetWindowSeconds(v)
	return _u
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableWindowSeconds(v *int) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetWindowSeconds(*v)
	}
	return _u
}

// AddWindowSeconds adds value to the "window_seconds" field.
func (_u *AccountQualitySnapshotUpdateOne) AddWindowSeconds(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddWindowSeconds(v)
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *AccountQualitySnapshotUpdateOne) SetSuccessCount(v int64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableSuccessCount(v *int64) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *AccountQualitySnapshotUpdateOne) AddSuccessCount(v int64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *AccountQualitySnapshotUpdateOne) SetErrorCount(v int64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableErrorCount(v *int64) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *AccountQualitySnapshotUpdateOne) AddErrorCount(v int64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetTtftSamples sets the "ttft_samples" field.
func (_u *AccountQualitySnapshotUpdateOne) SetTtftSamples(v int64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetTtftSamples()
	_u.mutation.SetTtftSamples(v)
	return _u
}

// SetNillableTtftSamples sets the "ttft_samples" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableTtftSamples(v *int64) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetTtftSamples(*v)
	}
	return _u
}

// AddTtftSamples adds value to the "ttft_samples" field.
func (_u *AccountQualitySnapshotUpdateOne) AddTtftSamples(v int64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddTtftSamples(v)
	return _u
}

// SetSuccessRate sets the "success_rate" field.
func (_u *AccountQualitySnapshotUpdateOne) SetSuccessRate(v float64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetSuccessRate()
	_u.mutation.SetSuccessRate(v)
	return _u
}

// SetNillableSuccessRate sets the "success_rate" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableSuccessRate(v *float64) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetSuccessRate(*v)
	}
	return _u
}

// AddSuccessRate adds value to the "success_rate" field.
func (_u *AccountQualitySnapshotUpdateOne) AddSuccessRate(v float64) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddSuccessRate(v)
	return _u
}

// ClearSuccessRate clears the value of the "success_rate" field.
func (_u *AccountQualitySnapshotUpdateOne) ClearSuccessRate() *AccountQualitySnapshotUpdateOne {
	_u.mutation.ClearSuccessRate()
	return _u
}

// SetAvgTtftMs sets the "avg_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) SetAvgTtftMs(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetAvgTtftMs()
	_u.mutation.SetAvgTtftMs(v)
	return _u
}

// SetNillableAvgTtftMs sets the "avg_ttft_ms" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableAvgTtftMs(v *int) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetAvgTtftMs(*v)
	}
	return _u
}

// AddAvgTtftMs adds value to the "avg_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) AddAvgTtftMs(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddAvgTtftMs(v)
	return _u
}

// ClearAvgTtftMs clears the value of the "avg_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) ClearAvgTtftMs() *AccountQualitySnapshotUpdateOne {
	_u.mutation.ClearAvgTtftMs()
	return _u
}

// SetP50TtftMs sets the "p50_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) SetP50TtftMs(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetP50TtftMs()
	_u.mutation.SetP50TtftMs(v)
	return _u
}

// SetNillableP50TtftMs sets the "p50_ttft_ms" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableP50TtftMs(v *int) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetP50TtftMs(*v)
	}
	return _u
}

// AddP50TtftMs adds value to the "p50_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) AddP50TtftMs(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddP50TtftMs(v)
	return _u
}

// ClearP50TtftMs clears the value of the "p50_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) ClearP50TtftMs() *AccountQualitySnapshotUpdateOne {
	_u.mutation.ClearP50TtftMs()
	return _u
}

// SetP95TtftMs sets the "p95_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) SetP95TtftMs(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetP95TtftMs()
	_u.mutation.SetP95TtftMs(v)
	return _u
}

// SetNillableP95TtftMs sets the "p95_ttft_ms" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableP95TtftMs(v *int) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetP95TtftMs(*v)
	}
	return _u
}

// AddP95TtftMs adds value to the "p95_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) AddP95TtftMs(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddP95TtftMs(v)
	return _u
}

// ClearP95TtftMs clears the value of the "p95_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) ClearP95TtftMs() *AccountQualitySnapshotUpdateOne {
	_u.mutation.ClearP95TtftMs()
	return _u
}

// SetMaxTtftMs sets the "max_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) SetMaxTtftMs(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.ResetMaxTtftMs()
	_u.mutation.SetMaxTtftMs(v)
	return _u
}

// SetNillableMaxTtftMs sets the "max_ttft_ms" field if the given value is not nil.
func (_u *AccountQualitySnapshotUpdateOne) SetNillableMaxTtftMs(v *int) *AccountQualitySnapshotUpdateOne {
	if v != nil {
		_u.SetMaxTtftMs(*v)
	}
	return _u
}

// AddMaxTtftMs adds value to the "max_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) AddMaxTtftMs(v int) *AccountQualitySnapshotUpdateOne {
	_u.mutation.AddMaxTtftMs(v)
	return _u
}

// ClearMaxTtftMs clears the value of the "max_ttft_ms" field.
func (_u *AccountQualitySnapshotUpdateOne) ClearMaxTtftMs() *AccountQualitySnapshotUpdateOne {
	_u.mutation.ClearMaxTtftMs()
	return _u
}

// Mutation returns the AccountQualitySnapshotMutation object of the builder.
func (_u *AccountQualitySnapshotUpdateOne) Mutation() *AccountQualitySnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountQualitySnapshotUpdate builder.
func (_u *AccountQualitySnapshotUpdateOne) Where(ps ...predicate.AccountQualitySnapshot) *AccountQualitySnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountQualitySnapshotUpdateOne) Select(field string, fields ...string) *AccountQualitySnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountQualitySnapshot entity.
func (_u *AccountQualitySnapshotUpdateOne) Save(ctx context.Context) (*AccountQualitySnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountQualitySnapshotUpdateOne) SaveX(ctx context.Context) *AccountQualitySnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountQualitySnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountQualitySnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AccountQualitySnapshotUpdateOne) sqlSave(ctx context.Context) (_node *AccountQualitySnapshot, err error) {
	_spec := sqlgraph.NewUpdateSpec(accountqualitysnapshot.Table, accountqualitysnapshot.Columns, sqlgraph.NewFieldSpec(accountqualitysnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountQualitySnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountqualitysnapshot.FieldID)
		for _, f := range fields {
			if !accountqualitysnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountqualitysnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountqualitysnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountqualitysnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(accountqualitysnapshot.FieldCapturedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WindowSeconds(); ok {
		_spec.SetField(accountqualitysnapshot.FieldWindowSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWindowSeconds(); ok {
		_spec.AddField(accountqualitysnapshot.FieldWindowSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(accountqualitysnapshot.FieldSuccessCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(accountqualitysnapshot.FieldSuccessCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(accountqualitysnapshot.FieldErrorCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(accountqualitysnapshot.FieldErrorCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TtftSamples(); ok {
		_spec.SetField(accountqualitysnapshot.FieldTtftSamples, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTtftSamples(); ok {
		_spec.AddField(accountqualitysnapshot.FieldTtftSamples, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SuccessRate(); ok {
		_spec.SetField(accountqualitysnapshot.FieldSuccessRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSuccessRate(); ok {
		_spec.AddField(accountqualitysnapshot.FieldSuccessRate, field.TypeFloat64, value)
	}
	if _u.mutation.SuccessRateCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldSuccessRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AvgTtftMs(); ok {
		_spec.SetField(accountqualitysnapshot.FieldAvgTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvgTtftMs(); ok {
		_spec.AddField(accountqualitysnapshot.FieldAvgTtftMs, field.TypeInt, value)
	}
	if _u.mutation.AvgTtftMsCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldAvgTtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.P50TtftMs(); ok {
		_spec.SetField(accountqualitysnapshot.FieldP50TtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedP50TtftMs(); ok {
		_spec.AddField(accountqualitysnapshot.FieldP50TtftMs, field.TypeInt, value)
	}
	if _u.mutation.P50TtftMsCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldP50TtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.P95TtftMs(); ok {
		_spec.SetField(accountqualitysnapshot.FieldP95TtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedP95TtftMs(); ok {
		_spec.AddField(accountqualitysnapshot.FieldP95TtftMs, field.TypeInt, value)
	}
	if _u.mutation.P95TtftMsCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldP95TtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxTtftMs(); ok {
		_spec.SetField(accountqualitysnapshot.FieldMaxTtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTtftMs(); ok {
		_spec.AddField(accountqualitysnapshot.FieldMaxTtftMs, field.TypeInt, value)
	}
	if _u.mutation.MaxTtftMsCleared() {
		_spec.ClearField(accountqualitysnapshot.FieldMaxTtftMs, field.TypeInt)
	}
	_node = &AccountQualitySnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountqualitysnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
