// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/aicreditsnapshot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AICreditSnapshotDelete is the builder for deleting a AICreditSnapshot entity.
type AICreditSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *AICreditSnapshotMutation
}

// Where appends a list predicates to the AICreditSnapshotDelete builder.
func (_d *AICreditSnapshotDelete) Where(ps ...predicate.AICreditSnapshot) *AICreditSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AICreditSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AICreditSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AICreditSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aicreditsnapshot.Table, sqlgraph.NewFieldSpec(aicreditsnapshot.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AICreditSnapshotDeleteOne is the builder for deleting a single AICreditSnapshot entity.
type AICreditSnapshotDeleteOne struct {
	_d *AICreditSnapshotDelete
}

// Where appends a list predicates to the AICreditSnapshotDelete builder.
func (_d *AICreditSnapshotDeleteOne) Where(ps ...predicate.AICreditSnapshot) *AICreditSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AICreditSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aicreditsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AICreditSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
