// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imagechannelmonitor"
	"github.com/Wei-Shaw/sub2api/ent/imagechannelmonitorhistory"
)

// ImageChannelMonitorHistory is the model entity for the ImageChannelMonitorHistory schema.
type ImageChannelMonitorHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// MonitorID holds the value of the "monitor_id" field.
	MonitorID int64 `json:"monitor_id,omitempty"`
	// Status holds the value of the "status" field.
	Status imagechannelmonitorhistory.Status `json:"status,omitempty"`
	// HTTPStatus holds the value of the "http_status" field.
	HTTPStatus *int `json:"http_status,omitempty"`
	// APIHeaderMs holds the value of the "api_header_ms" field.
	APIHeaderMs *int `json:"api_header_ms,omitempty"`
	// APIBodyMs holds the value of the "api_body_ms" field.
	APIBodyMs *int `json:"api_body_ms,omitempty"`
	// APITotalMs holds the value of the "api_total_ms" field.
	APITotalMs *int `json:"api_total_ms,omitempty"`
	// JSONBytes holds the value of the "json_bytes" field.
	JSONBytes *int `json:"json_bytes,omitempty"`
	// HasURL holds the value of the "has_url" field.
	HasURL bool `json:"has_url,omitempty"`
	// HasB64JSON holds the value of the "has_b64_json" field.
	HasB64JSON bool `json:"has_b64_json,omitempty"`
	// ImageURLHost holds the value of the "image_url_host" field.
	ImageURLHost string `json:"image_url_host,omitempty"`
	// ImageFirstByteMs holds the value of the "image_first_byte_ms" field.
	ImageFirstByteMs *int `json:"image_first_byte_ms,omitempty"`
	// ImageDownloadMs holds the value of the "image_download_ms" field.
	ImageDownloadMs *int `json:"image_download_ms,omitempty"`
	// ImageBytes holds the value of the "image_bytes" field.
	ImageBytes *int64 `json:"image_bytes,omitempty"`
	// ImageContentType holds the value of the "image_content_type" field.
	ImageContentType string `json:"image_content_type,omitempty"`
	// ImageWidth holds the value of the "image_width" field.
	ImageWidth *int `json:"image_width,omitempty"`
	// ImageHeight holds the value of the "image_height" field.
	ImageHeight *int `json:"image_height,omitempty"`
	// ErrorStage holds the value of the "error_stage" field.
	ErrorStage string `json:"error_stage,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// CheckedAt holds the value of the "checked_at" field.
	CheckedAt time.Time `json:"checked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageChannelMonitorHistoryQuery when eager-loading is set.
	Edges        ImageChannelMonitorHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ImageChannelMonitorHistoryEdges holds the relations/edges for other nodes in the graph.
type ImageChannelMonitorHistoryEdges struct {
	// Monitor holds the value of the monitor edge.
	Monitor *ImageChannelMonitor `json:"monitor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MonitorOrErr returns the Monitor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageChannelMonitorHistoryEdges) MonitorOrErr() (*ImageChannelMonitor, error) {
	if e.Monitor != nil {
		return e.Monitor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: imagechannelmonitor.Label}
	}
	return nil, &NotLoadedError{edge: "monitor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageChannelMonitorHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagechannelmonitorhistory.FieldHasURL, imagechannelmonitorhistory.FieldHasB64JSON:
			values[i] = new(sql.NullBool)
		case imagechannelmonitorhistory.FieldID, imagechannelmonitorhistory.FieldMonitorID, imagechannelmonitorhistory.FieldHTTPStatus, imagechannelmonitorhistory.FieldAPIHeaderMs, imagechannelmonitorhistory.FieldAPIBodyMs, imagechannelmonitorhistory.FieldAPITotalMs, imagechannelmonitorhistory.FieldJSONBytes, imagechannelmonitorhistory.FieldImageFirstByteMs, imagechannelmonitorhistory.FieldImageDownloadMs, imagechannelmonitorhistory.FieldImageBytes, imagechannelmonitorhistory.FieldImageWidth, imagechannelmonitorhistory.FieldImageHeight:
			values[i] = new(sql.NullInt64)
		case imagechannelmonitorhistory.FieldStatus, imagechannelmonitorhistory.FieldImageURLHost, imagechannelmonitorhistory.FieldImageContentType, imagechannelmonitorhistory.FieldErrorStage, imagechannelmonitorhistory.FieldMessage:
			values[i] = new(sql.NullString)
		case imagechannelmonitorhistory.FieldCheckedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageChannelMonitorHistory fields.
func (_m *ImageChannelMonitorHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagechannelmonitorhistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imagechannelmonitorhistory.FieldMonitorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_id", values[i])
			} else if value.Valid {
				_m.MonitorID = value.Int64
			}
		case imagechannelmonitorhistory.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = imagechannelmonitorhistory.Status(value.String)
			}
		case imagechannelmonitorhistory.FieldHTTPStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_status", values[i])
			} else if value.Valid {
				_m.HTTPStatus = new(int)
				*_m.HTTPStatus = int(value.Int64)
			}
		case imagechannelmonitorhistory.FieldAPIHeaderMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_header_ms", values[i])
			} else if value.Valid {
				_m.APIHeaderMs = new(int)
				*_m.APIHeaderMs = int(value.Int64)
			}
		case imagechannelmonitorhistory.FieldAPIBodyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_body_ms", values[i])
			} else if value.Valid {
				_m.APIBodyMs = new(int)
				*_m.APIBodyMs = int(value.Int64)
			}
		case imagechannelmonitorhistory.FieldAPITotalMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_total_ms", values[i])
			} else if value.Valid {
				_m.APITotalMs = new(int)
				*_m.APITotalMs = int(value.Int64)
			}
		case imagechannelmonitorhistory.FieldJSONBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field json_bytes", values[i])
			} else if value.Valid {
				_m.JSONBytes = new(int)
				*_m.JSONBytes = int(value.Int64)
			}
		case imagechannelmonitorhistory.FieldHasURL:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_url", values[i])
			} else if value.Valid {
				_m.HasURL = value.Bool
			}
		case imagechannelmonitorhistory.FieldHasB64JSON:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_b64_json", values[i])
			} else if value.Valid {
				_m.HasB64JSON = value.Bool
			}
		case imagechannelmonitorhistory.FieldImageURLHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_url_host", values[i])
			} else if value.Valid {
				_m.ImageURLHost = value.String
			}
		case imagechannelmonitorhistory.FieldImageFirstByteMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_first_byte_ms", values[i])
			} else if value.Valid {
				_m.ImageFirstByteMs = new(int)
				*_m.ImageFirstByteMs = int(value.Int64)
			}
		case imagechannelmonitorhistory.FieldImageDownloadMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_download_ms", values[i])
			} else if value.Valid {
				_m.ImageDownloadMs = new(int)
				*_m.ImageDownloadMs = int(value.Int64)
			}
		case imagechannelmonitorhistory.FieldImageBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_bytes", values[i])
			} else if value.Valid {
				_m.ImageBytes = new(int64)
				*_m.ImageBytes = value.Int64
			}
		case imagechannelmonitorhistory.FieldImageContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_content_type", values[i])
			} else if value.Valid {
				_m.ImageContentType = value.String
			}
		case imagechannelmonitorhistory.FieldImageWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_width", values[i])
			} else if value.Valid {
				_m.ImageWidth = new(int)
				*_m.ImageWidth = int(value.Int64)
			}
		case imagechannelmonitorhistory.FieldImageHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_height", values[i])
			} else if value.Valid {
				_m.ImageHeight = new(int)
				*_m.ImageHeight = int(value.Int64)
			}
		case imagechannelmonitorhistory.FieldErrorStage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_stage", values[i])
			} else if value.Valid {
				_m.ErrorStage = value.String
			}
		case imagechannelmonitorhistory.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case imagechannelmonitorhistory.FieldCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_at", values[i])
			} else if value.Valid {
				_m.CheckedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageChannelMonitorHistory.
// This includes values selected through modifiers, order, etc.
func (_m *ImageChannelMonitorHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMonitor queries the "monitor" edge of the ImageChannelMonitorHistory entity.
func (_m *ImageChannelMonitorHistory) QueryMonitor() *ImageChannelMonitorQuery {
	return NewImageChannelMonitorHistoryClient(_m.config).QueryMonitor(_m)
}

// Update returns a builder for updating this ImageChannelMonitorHistory.
// Note that you need to call ImageChannelMonitorHistory.Unwrap() before calling this method if this ImageChannelMonitorHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageChannelMonitorHistory) Update() *ImageChannelMonitorHistoryUpdateOne {
	return NewImageChannelMonitorHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageChannelMonitorHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageChannelMonitorHistory) Unwrap() *ImageChannelMonitorHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageChannelMonitorHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageChannelMonitorHistory) String() string {
	var builder strings.Builder
	builder.WriteString("ImageChannelMonitorHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonitorID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.HTTPStatus; v != nil {
		builder.WriteString("http_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIHeaderMs; v != nil {
		builder.WriteString("api_header_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIBodyMs; v != nil {
		builder.WriteString("api_body_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APITotalMs; v != nil {
		builder.WriteString("api_total_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.JSONBytes; v != nil {
		builder.WriteString("json_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("has_url=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasURL))
	builder.WriteString(", ")
	builder.WriteString("has_b64_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasB64JSON))
	builder.WriteString(", ")
	builder.WriteString("image_url_host=")
	builder.WriteString(_m.ImageURLHost)
	builder.WriteString(", ")
	if v := _m.ImageFirstByteMs; v != nil {
		builder.WriteString("image_first_byte_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageDownloadMs; v != nil {
		builder.WriteString("image_download_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageBytes; v != nil {
		builder.WriteString("image_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("image_content_type=")
	builder.WriteString(_m.ImageContentType)
	builder.WriteString(", ")
	if v := _m.ImageWidth; v != nil {
		builder.WriteString("image_width=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ImageHeight; v != nil {
		builder.WriteString("image_height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("error_stage=")
	builder.WriteString(_m.ErrorStage)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("checked_at=")
	builder.WriteString(_m.CheckedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImageChannelMonitorHistories is a parsable slice of ImageChannelMonitorHistory.
type ImageChannelMonitorHistories []*ImageChannelMonitorHistory
