// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imagechannelmonitor"
)

// ImageChannelMonitor is the model entity for the ImageChannelMonitor schema.
type ImageChannelMonitor struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType imagechannelmonitor.SourceType `json:"source_type,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// APIKeyEncrypted holds the value of the "api_key_encrypted" field.
	APIKeyEncrypted string `json:"-"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// AccountName holds the value of the "account_name" field.
	AccountName string `json:"account_name,omitempty"`
	// ProxyID holds the value of the "proxy_id" field.
	ProxyID *int64 `json:"proxy_id,omitempty"`
	// ProxyName holds the value of the "proxy_name" field.
	ProxyName string `json:"proxy_name,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// Size holds the value of the "size" field.
	Size string `json:"size,omitempty"`
	// Quality holds the value of the "quality" field.
	Quality string `json:"quality,omitempty"`
	// N holds the value of the "n" field.
	N int `json:"n,omitempty"`
	// DownloadImage holds the value of the "download_image" field.
	DownloadImage bool `json:"download_image,omitempty"`
	// ResponseFormat holds the value of the "response_format" field.
	ResponseFormat string `json:"response_format,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// PublicVisible holds the value of the "public_visible" field.
	PublicVisible bool `json:"public_visible,omitempty"`
	// PublicName holds the value of the "public_name" field.
	PublicName string `json:"public_name,omitempty"`
	// IntervalSeconds holds the value of the "interval_seconds" field.
	IntervalSeconds int `json:"interval_seconds,omitempty"`
	// TimeoutSeconds holds the value of the "timeout_seconds" field.
	TimeoutSeconds int `json:"timeout_seconds,omitempty"`
	// LastCheckedAt holds the value of the "last_checked_at" field.
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageChannelMonitorQuery when eager-loading is set.
	Edges        ImageChannelMonitorEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ImageChannelMonitorEdges holds the relations/edges for other nodes in the graph.
type ImageChannelMonitorEdges struct {
	// Histories holds the value of the histories edge.
	Histories []*ImageChannelMonitorHistory `json:"histories,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HistoriesOrErr returns the Histories value or an error if the edge
// was not loaded in eager-loading.
func (e ImageChannelMonitorEdges) HistoriesOrErr() ([]*ImageChannelMonitorHistory, error) {
	if e.loadedTypes[0] {
		return e.Histories, nil
	}
	return nil, &NotLoadedError{edge: "histories"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageChannelMonitor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagechannelmonitor.FieldDownloadImage, imagechannelmonitor.FieldEnabled, imagechannelmonitor.FieldPublicVisible:
			values[i] = new(sql.NullBool)
		case imagechannelmonitor.FieldID, imagechannelmonitor.FieldAccountID, imagechannelmonitor.FieldProxyID, imagechannelmonitor.FieldN, imagechannelmonitor.FieldIntervalSeconds, imagechannelmonitor.FieldTimeoutSeconds, imagechannelmonitor.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case imagechannelmonitor.FieldName, imagechannelmonitor.FieldSourceType, imagechannelmonitor.FieldEndpoint, imagechannelmonitor.FieldAPIKeyEncrypted, imagechannelmonitor.FieldAccountName, imagechannelmonitor.FieldProxyName, imagechannelmonitor.FieldModel, imagechannelmonitor.FieldPrompt, imagechannelmonitor.FieldSize, imagechannelmonitor.FieldQuality, imagechannelmonitor.FieldResponseFormat, imagechannelmonitor.FieldPublicName:
			values[i] = new(sql.NullString)
		case imagechannelmonitor.FieldLastCheckedAt, imagechannelmonitor.FieldCreatedAt, imagechannelmonitor.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageChannelMonitor fields.
func (_m *ImageChannelMonitor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagechannelmonitor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imagechannelmonitor.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case imagechannelmonitor.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = imagechannelmonitor.SourceType(value.String)
			}
		case imagechannelmonitor.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case imagechannelmonitor.FieldAPIKeyEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_encrypted", values[i])
			} else if value.Valid {
				_m.APIKeyEncrypted = value.String
			}
		case imagechannelmonitor.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case imagechannelmonitor.FieldAccountName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_name", values[i])
			} else if value.Valid {
				_m.AccountName = value.String
			}
		case imagechannelmonitor.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = new(int64)
				*_m.ProxyID = value.Int64
			}
		case imagechannelmonitor.FieldProxyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_name", values[i])
			} else if value.Valid {
				_m.ProxyName = value.String
			}
		case imagechannelmonitor.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case imagechannelmonitor.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case imagechannelmonitor.FieldSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.String
			}
		case imagechannelmonitor.FieldQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality", values[i])
			} else if value.Valid {
				_m.Quality = value.String
			}
		case imagechannelmonitor.FieldN:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field n", values[i])
			} else if value.Valid {
				_m.N = int(value.Int64)
			}
		case imagechannelmonitor.FieldDownloadImage:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field download_image", values[i])
			} else if value.Valid {
				_m.DownloadImage = value.Bool
			}
		case imagechannelmonitor.FieldResponseFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_format", values[i])
			} else if value.Valid {
				_m.ResponseFormat = value.String
			}
		case imagechannelmonitor.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case imagechannelmonitor.FieldPublicVisible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field public_visible", values[i])
			} else if value.Valid {
				_m.PublicVisible = value.Bool
			}
		case imagechannelmonitor.FieldPublicName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_name", values[i])
			} else if value.Valid {
				_m.PublicName = value.String
			}
		case imagechannelmonitor.FieldIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interval_seconds", values[i])
			} else if value.Valid {
				_m.IntervalSeconds = int(value.Int64)
			}
		case imagechannelmonitor.FieldTimeoutSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_seconds", values[i])
			} else if value.Valid {
				_m.TimeoutSeconds = int(value.Int64)
			}
		case imagechannelmonitor.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = new(time.Time)
				*_m.LastCheckedAt = value.Time
			}
		case imagechannelmonitor.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case imagechannelmonitor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imagechannelmonitor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageChannelMonitor.
// This includes values selected through modifiers, order, etc.
func (_m *ImageChannelMonitor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHistories queries the "histories" edge of the ImageChannelMonitor entity.
func (_m *ImageChannelMonitor) QueryHistories() *ImageChannelMonitorHistoryQuery {
	return NewImageChannelMonitorClient(_m.config).QueryHistories(_m)
}

// Update returns a builder for updating this ImageChannelMonitor.
// Note that you need to call ImageChannelMonitor.Unwrap() before calling this method if this ImageChannelMonitor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageChannelMonitor) Update() *ImageChannelMonitorUpdateOne {
	return NewImageChannelMonitorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageChannelMonitor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageChannelMonitor) Unwrap() *ImageChannelMonitor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageChannelMonitor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageChannelMonitor) String() string {
	var builder strings.Builder
	builder.WriteString("ImageChannelMonitor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceType))
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("api_key_encrypted=<sensitive>")
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("account_name=")
	builder.WriteString(_m.AccountName)
	builder.WriteString(", ")
	if v := _m.ProxyID; v != nil {
		builder.WriteString("proxy_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("proxy_name=")
	builder.WriteString(_m.ProxyName)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(_m.Size)
	builder.WriteString(", ")
	builder.WriteString("quality=")
	builder.WriteString(_m.Quality)
	builder.WriteString(", ")
	builder.WriteString("n=")
	builder.WriteString(fmt.Sprintf("%v", _m.N))
	builder.WriteString(", ")
	builder.WriteString("download_image=")
	builder.WriteString(fmt.Sprintf("%v", _m.DownloadImage))
	builder.WriteString(", ")
	builder.WriteString("response_format=")
	builder.WriteString(_m.ResponseFormat)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("public_visible=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicVisible))
	builder.WriteString(", ")
	builder.WriteString("public_name=")
	builder.WriteString(_m.PublicName)
	builder.WriteString(", ")
	builder.WriteString("interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntervalSeconds))
	builder.WriteString(", ")
	builder.WriteString("timeout_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeoutSeconds))
	builder.WriteString(", ")
	if v := _m.LastCheckedAt; v != nil {
		builder.WriteString("last_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImageChannelMonitors is a parsable slice of ImageChannelMonitor.
type ImageChannelMonitors []*ImageChannelMonitor
