// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersmartscheduleaccount"
)

// UserSmartScheduleAccount is the model entity for the UserSmartScheduleAccount schema.
type UserSmartScheduleAccount struct {
	config `json:"-"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// MaxConcurrency holds the value of the "max_concurrency" field.
	MaxConcurrency *int `json:"max_concurrency,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserSmartScheduleAccountQuery when eager-loading is set.
	Edges        UserSmartScheduleAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserSmartScheduleAccountEdges holds the relations/edges for other nodes in the graph.
type UserSmartScheduleAccountEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSmartScheduleAccountEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSmartScheduleAccountEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserSmartScheduleAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersmartscheduleaccount.FieldAccountID, usersmartscheduleaccount.FieldUserID, usersmartscheduleaccount.FieldMaxConcurrency:
			values[i] = new(sql.NullInt64)
		case usersmartscheduleaccount.FieldPlatform:
			values[i] = new(sql.NullString)
		case usersmartscheduleaccount.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserSmartScheduleAccount fields.
func (_m *UserSmartScheduleAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersmartscheduleaccount.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case usersmartscheduleaccount.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usersmartscheduleaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usersmartscheduleaccount.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case usersmartscheduleaccount.FieldMaxConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_concurrency", values[i])
			} else if value.Valid {
				_m.MaxConcurrency = new(int)
				*_m.MaxConcurrency = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserSmartScheduleAccount.
// This includes values selected through modifiers, order, etc.
func (_m *UserSmartScheduleAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserSmartScheduleAccount entity.
func (_m *UserSmartScheduleAccount) QueryUser() *UserQuery {
	return NewUserSmartScheduleAccountClient(_m.config).QueryUser(_m)
}

// QueryAccount queries the "account" edge of the UserSmartScheduleAccount entity.
func (_m *UserSmartScheduleAccount) QueryAccount() *AccountQuery {
	return NewUserSmartScheduleAccountClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this UserSmartScheduleAccount.
// Note that you need to call UserSmartScheduleAccount.Unwrap() before calling this method if this UserSmartScheduleAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserSmartScheduleAccount) Update() *UserSmartScheduleAccountUpdateOne {
	return NewUserSmartScheduleAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserSmartScheduleAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserSmartScheduleAccount) Unwrap() *UserSmartScheduleAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserSmartScheduleAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserSmartScheduleAccount) String() string {
	var builder strings.Builder
	builder.WriteString("UserSmartScheduleAccount(")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	if v := _m.MaxConcurrency; v != nil {
		builder.WriteString("max_concurrency=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserSmartScheduleAccounts is a parsable slice of UserSmartScheduleAccount.
type UserSmartScheduleAccounts []*UserSmartScheduleAccount
