// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersmartschedulepolicy"
)

// UserSmartSchedulePolicyUpdate is the builder for updating UserSmartSchedulePolicy entities.
type UserSmartSchedulePolicyUpdate struct {
	config
	hooks    []Hook
	mutation *UserSmartSchedulePolicyMutation
}

// Where appends a list predicates to the UserSmartSchedulePolicyUpdate builder.
func (_u *UserSmartSchedulePolicyUpdate) Where(ps ...predicate.UserSmartSchedulePolicy) *UserSmartSchedulePolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSmartSchedulePolicyUpdate) SetUpdatedAt(v time.Time) *UserSmartSchedulePolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserSmartSchedulePolicyUpdate) SetUserID(v int64) *UserSmartSchedulePolicyUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdate) SetNillableUserID(v *int64) *UserSmartSchedulePolicyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UserSmartSchedulePolicyUpdate) SetPlatform(v string) *UserSmartSchedulePolicyUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdate) SetNillablePlatform(v *string) *UserSmartSchedulePolicyUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UserSmartSchedulePolicyUpdate) SetEnabled(v bool) *UserSmartSchedulePolicyUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdate) SetNillableEnabled(v *bool) *UserSmartSchedulePolicyUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field.
func (_u *UserSmartSchedulePolicyUpdate) SetQualityMaxP50TtftMs(v int) *UserSmartSchedulePolicyUpdate {
	_u.mutation.ResetQualityMaxP50TtftMs()
	_u.mutation.SetQualityMaxP50TtftMs(v)
	return _u
}

// SetNillableQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdate) SetNillableQualityMaxP50TtftMs(v *int) *UserSmartSchedulePolicyUpdate {
	if v != nil {
		_u.SetQualityMaxP50TtftMs(*v)
	}
	return _u
}

// AddQualityMaxP50TtftMs adds value to the "quality_max_p50_ttft_ms" field.
func (_u *UserSmartSchedulePolicyUpdate) AddQualityMaxP50TtftMs(v int) *UserSmartSchedulePolicyUpdate {
	_u.mutation.AddQualityMaxP50TtftMs(v)
	return _u
}

// ClearQualityMaxP50TtftMs clears the value of the "quality_max_p50_ttft_ms" field.
func (_u *UserSmartSchedulePolicyUpdate) ClearQualityMaxP50TtftMs() *UserSmartSchedulePolicyUpdate {
	_u.mutation.ClearQualityMaxP50TtftMs()
	return _u
}

// SetQualityMinSuccessRate sets the "quality_min_success_rate" field.
func (_u *UserSmartSchedulePolicyUpdate) SetQualityMinSuccessRate(v float64) *UserSmartSchedulePolicyUpdate {
	_u.mutation.ResetQualityMinSuccessRate()
	_u.mutation.SetQualityMinSuccessRate(v)
	return _u
}

// SetNillableQualityMinSuccessRate sets the "quality_min_success_rate" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdate) SetNillableQualityMinSuccessRate(v *float64) *UserSmartSchedulePolicyUpdate {
	if v != nil {
		_u.SetQualityMinSuccessRate(*v)
	}
	return _u
}

// AddQualityMinSuccessRate adds value to the "quality_min_success_rate" field.
func (_u *UserSmartSchedulePolicyUpdate) AddQualityMinSuccessRate(v float64) *UserSmartSchedulePolicyUpdate {
	_u.mutation.AddQualityMinSuccessRate(v)
	return _u
}

// ClearQualityMinSuccessRate clears the value of the "quality_min_success_rate" field.
func (_u *UserSmartSchedulePolicyUpdate) ClearQualityMinSuccessRate() *UserSmartSchedulePolicyUpdate {
	_u.mutation.ClearQualityMinSuccessRate()
	return _u
}

// SetQualityMinSuccessSamples sets the "quality_min_success_samples" field.
func (_u *UserSmartSchedulePolicyUpdate) SetQualityMinSuccessSamples(v int) *UserSmartSchedulePolicyUpdate {
	_u.mutation.ResetQualityMinSuccessSamples()
	_u.mutation.SetQualityMinSuccessSamples(v)
	return _u
}

// SetNillableQualityMinSuccessSamples sets the "quality_min_success_samples" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdate) SetNillableQualityMinSuccessSamples(v *int) *UserSmartSchedulePolicyUpdate {
	if v != nil {
		_u.SetQualityMinSuccessSamples(*v)
	}
	return _u
}

// AddQualityMinSuccessSamples adds value to the "quality_min_success_samples" field.
func (_u *UserSmartSchedulePolicyUpdate) AddQualityMinSuccessSamples(v int) *UserSmartSchedulePolicyUpdate {
	_u.mutation.AddQualityMinSuccessSamples(v)
	return _u
}

// ClearQualityMinSuccessSamples clears the value of the "quality_min_success_samples" field.
func (_u *UserSmartSchedulePolicyUpdate) ClearQualityMinSuccessSamples() *UserSmartSchedulePolicyUpdate {
	_u.mutation.ClearQualityMinSuccessSamples()
	return _u
}

// SetQualityMinTtftSamples sets the "quality_min_ttft_samples" field.
func (_u *UserSmartSchedulePolicyUpdate) SetQualityMinTtftSamples(v int) *UserSmartSchedulePolicyUpdate {
	_u.mutation.ResetQualityMinTtftSamples()
	_u.mutation.SetQualityMinTtftSamples(v)
	return _u
}

// SetNillableQualityMinTtftSamples sets the "quality_min_ttft_samples" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdate) SetNillableQualityMinTtftSamples(v *int) *UserSmartSchedulePolicyUpdate {
	if v != nil {
		_u.SetQualityMinTtftSamples(*v)
	}
	return _u
}

// AddQualityMinTtftSamples adds value to the "quality_min_ttft_samples" field.
func (_u *UserSmartSchedulePolicyUpdate) AddQualityMinTtftSamples(v int) *UserSmartSchedulePolicyUpdate {
	_u.mutation.AddQualityMinTtftSamples(v)
	return _u
}

// ClearQualityMinTtftSamples clears the value of the "quality_min_ttft_samples" field.
func (_u *UserSmartSchedulePolicyUpdate) ClearQualityMinTtftSamples() *UserSmartSchedulePolicyUpdate {
	_u.mutation.ClearQualityMinTtftSamples()
	return _u
}

// SetQualityCondition sets the "quality_condition" field.
func (_u *UserSmartSchedulePolicyUpdate) SetQualityCondition(v string) *UserSmartSchedulePolicyUpdate {
	_u.mutation.SetQualityCondition(v)
	return _u
}

// SetNillableQualityCondition sets the "quality_condition" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdate) SetNillableQualityCondition(v *string) *UserSmartSchedulePolicyUpdate {
	if v != nil {
		_u.SetQualityCondition(*v)
	}
	return _u
}

// ClearQualityCondition clears the value of the "quality_condition" field.
func (_u *UserSmartSchedulePolicyUpdate) ClearQualityCondition() *UserSmartSchedulePolicyUpdate {
	_u.mutation.ClearQualityCondition()
	return _u
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (_u *UserSmartSchedulePolicyUpdate) SetCooldownMinutes(v int) *UserSmartSchedulePolicyUpdate {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldown_minutes" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdate) SetNillableCooldownMinutes(v *int) *UserSmartSchedulePolicyUpdate {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldown_minutes" field.
func (_u *UserSmartSchedulePolicyUpdate) AddCooldownMinutes(v int) *UserSmartSchedulePolicyUpdate {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserSmartSchedulePolicyUpdate) SetUser(v *User) *UserSmartSchedulePolicyUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserSmartSchedulePolicyMutation object of the builder.
func (_u *UserSmartSchedulePolicyUpdate) Mutation() *UserSmartSchedulePolicyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserSmartSchedulePolicyUpdate) ClearUser() *UserSmartSchedulePolicyUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserSmartSchedulePolicyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSmartSchedulePolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserSmartSchedulePolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSmartSchedulePolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSmartSchedulePolicyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usersmartschedulepolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSmartSchedulePolicyUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := usersmartschedulepolicy.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UserSmartSchedulePolicy.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualityCondition(); ok {
		if err := usersmartschedulepolicy.QualityConditionValidator(v); err != nil {
			return &ValidationError{Name: "quality_condition", err: fmt.Errorf(`ent: validator failed for field "UserSmartSchedulePolicy.quality_condition": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSmartSchedulePolicy.user"`)
	}
	return nil
}

func (_u *UserSmartSchedulePolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersmartschedulepolicy.Table, usersmartschedulepolicy.Columns, sqlgraph.NewFieldSpec(usersmartschedulepolicy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QualityMaxP50TtftMs(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityMaxP50TtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMaxP50TtftMs(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldQualityMaxP50TtftMs, field.TypeInt, value)
	}
	if _u.mutation.QualityMaxP50TtftMsCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityMaxP50TtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMinSuccessRate(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityMinSuccessRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQualityMinSuccessRate(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldQualityMinSuccessRate, field.TypeFloat64, value)
	}
	if _u.mutation.QualityMinSuccessRateCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityMinSuccessRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QualityMinSuccessSamples(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityMinSuccessSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMinSuccessSamples(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldQualityMinSuccessSamples, field.TypeInt, value)
	}
	if _u.mutation.QualityMinSuccessSamplesCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityMinSuccessSamples, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMinTtftSamples(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityMinTtftSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMinTtftSamples(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldQualityMinTtftSamples, field.TypeInt, value)
	}
	if _u.mutation.QualityMinTtftSamplesCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityMinTtftSamples, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityCondition(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityCondition, field.TypeString, value)
	}
	if _u.mutation.QualityConditionCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityCondition, field.TypeString)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldCooldownMinutes, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersmartschedulepolicy.UserTable,
			Columns: []string{usersmartschedulepolicy.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersmartschedulepolicy.UserTable,
			Columns: []string{usersmartschedulepolicy.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersmartschedulepolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserSmartSchedulePolicyUpdateOne is the builder for updating a single UserSmartSchedulePolicy entity.
type UserSmartSchedulePolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSmartSchedulePolicyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetUpdatedAt(v time.Time) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetUserID(v int64) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdateOne) SetNillableUserID(v *int64) *UserSmartSchedulePolicyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetPlatform(v string) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdateOne) SetNillablePlatform(v *string) *UserSmartSchedulePolicyUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetEnabled(v bool) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdateOne) SetNillableEnabled(v *bool) *UserSmartSchedulePolicyUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetQualityMaxP50TtftMs(v int) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ResetQualityMaxP50TtftMs()
	_u.mutation.SetQualityMaxP50TtftMs(v)
	return _u
}

// SetNillableQualityMaxP50TtftMs sets the "quality_max_p50_ttft_ms" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdateOne) SetNillableQualityMaxP50TtftMs(v *int) *UserSmartSchedulePolicyUpdateOne {
	if v != nil {
		_u.SetQualityMaxP50TtftMs(*v)
	}
	return _u
}

// AddQualityMaxP50TtftMs adds value to the "quality_max_p50_ttft_ms" field.
func (_u *UserSmartSchedulePolicyUpdateOne) AddQualityMaxP50TtftMs(v int) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.AddQualityMaxP50TtftMs(v)
	return _u
}

// ClearQualityMaxP50TtftMs clears the value of the "quality_max_p50_ttft_ms" field.
func (_u *UserSmartSchedulePolicyUpdateOne) ClearQualityMaxP50TtftMs() *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ClearQualityMaxP50TtftMs()
	return _u
}

// SetQualityMinSuccessRate sets the "quality_min_success_rate" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetQualityMinSuccessRate(v float64) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ResetQualityMinSuccessRate()
	_u.mutation.SetQualityMinSuccessRate(v)
	return _u
}

// SetNillableQualityMinSuccessRate sets the "quality_min_success_rate" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdateOne) SetNillableQualityMinSuccessRate(v *float64) *UserSmartSchedulePolicyUpdateOne {
	if v != nil {
		_u.SetQualityMinSuccessRate(*v)
	}
	return _u
}

// AddQualityMinSuccessRate adds value to the "quality_min_success_rate" field.
func (_u *UserSmartSchedulePolicyUpdateOne) AddQualityMinSuccessRate(v float64) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.AddQualityMinSuccessRate(v)
	return _u
}

// ClearQualityMinSuccessRate clears the value of the "quality_min_success_rate" field.
func (_u *UserSmartSchedulePolicyUpdateOne) ClearQualityMinSuccessRate() *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ClearQualityMinSuccessRate()
	return _u
}

// SetQualityMinSuccessSamples sets the "quality_min_success_samples" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetQualityMinSuccessSamples(v int) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ResetQualityMinSuccessSamples()
	_u.mutation.SetQualityMinSuccessSamples(v)
	return _u
}

// SetNillableQualityMinSuccessSamples sets the "quality_min_success_samples" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdateOne) SetNillableQualityMinSuccessSamples(v *int) *UserSmartSchedulePolicyUpdateOne {
	if v != nil {
		_u.SetQualityMinSuccessSamples(*v)
	}
	return _u
}

// AddQualityMinSuccessSamples adds value to the "quality_min_success_samples" field.
func (_u *UserSmartSchedulePolicyUpdateOne) AddQualityMinSuccessSamples(v int) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.AddQualityMinSuccessSamples(v)
	return _u
}

// ClearQualityMinSuccessSamples clears the value of the "quality_min_success_samples" field.
func (_u *UserSmartSchedulePolicyUpdateOne) ClearQualityMinSuccessSamples() *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ClearQualityMinSuccessSamples()
	return _u
}

// SetQualityMinTtftSamples sets the "quality_min_ttft_samples" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetQualityMinTtftSamples(v int) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ResetQualityMinTtftSamples()
	_u.mutation.SetQualityMinTtftSamples(v)
	return _u
}

// SetNillableQualityMinTtftSamples sets the "quality_min_ttft_samples" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdateOne) SetNillableQualityMinTtftSamples(v *int) *UserSmartSchedulePolicyUpdateOne {
	if v != nil {
		_u.SetQualityMinTtftSamples(*v)
	}
	return _u
}

// AddQualityMinTtftSamples adds value to the "quality_min_ttft_samples" field.
func (_u *UserSmartSchedulePolicyUpdateOne) AddQualityMinTtftSamples(v int) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.AddQualityMinTtftSamples(v)
	return _u
}

// ClearQualityMinTtftSamples clears the value of the "quality_min_ttft_samples" field.
func (_u *UserSmartSchedulePolicyUpdateOne) ClearQualityMinTtftSamples() *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ClearQualityMinTtftSamples()
	return _u
}

// SetQualityCondition sets the "quality_condition" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetQualityCondition(v string) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.SetQualityCondition(v)
	return _u
}

// SetNillableQualityCondition sets the "quality_condition" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdateOne) SetNillableQualityCondition(v *string) *UserSmartSchedulePolicyUpdateOne {
	if v != nil {
		_u.SetQualityCondition(*v)
	}
	return _u
}

// ClearQualityCondition clears the value of the "quality_condition" field.
func (_u *UserSmartSchedulePolicyUpdateOne) ClearQualityCondition() *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ClearQualityCondition()
	return _u
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (_u *UserSmartSchedulePolicyUpdateOne) SetCooldownMinutes(v int) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldown_minutes" field if the given value is not nil.
func (_u *UserSmartSchedulePolicyUpdateOne) SetNillableCooldownMinutes(v *int) *UserSmartSchedulePolicyUpdateOne {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldown_minutes" field.
func (_u *UserSmartSchedulePolicyUpdateOne) AddCooldownMinutes(v int) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserSmartSchedulePolicyUpdateOne) SetUser(v *User) *UserSmartSchedulePolicyUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserSmartSchedulePolicyMutation object of the builder.
func (_u *UserSmartSchedulePolicyUpdateOne) Mutation() *UserSmartSchedulePolicyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserSmartSchedulePolicyUpdateOne) ClearUser() *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserSmartSchedulePolicyUpdate builder.
func (_u *UserSmartSchedulePolicyUpdateOne) Where(ps ...predicate.UserSmartSchedulePolicy) *UserSmartSchedulePolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserSmartSchedulePolicyUpdateOne) Select(field string, fields ...string) *UserSmartSchedulePolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserSmartSchedulePolicy entity.
func (_u *UserSmartSchedulePolicyUpdateOne) Save(ctx context.Context) (*UserSmartSchedulePolicy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSmartSchedulePolicyUpdateOne) SaveX(ctx context.Context) *UserSmartSchedulePolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserSmartSchedulePolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSmartSchedulePolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSmartSchedulePolicyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usersmartschedulepolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSmartSchedulePolicyUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := usersmartschedulepolicy.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UserSmartSchedulePolicy.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualityCondition(); ok {
		if err := usersmartschedulepolicy.QualityConditionValidator(v); err != nil {
			return &ValidationError{Name: "quality_condition", err: fmt.Errorf(`ent: validator failed for field "UserSmartSchedulePolicy.quality_condition": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSmartSchedulePolicy.user"`)
	}
	return nil
}

func (_u *UserSmartSchedulePolicyUpdateOne) sqlSave(ctx context.Context) (_node *UserSmartSchedulePolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersmartschedulepolicy.Table, usersmartschedulepolicy.Columns, sqlgraph.NewFieldSpec(usersmartschedulepolicy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSmartSchedulePolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersmartschedulepolicy.FieldID)
		for _, f := range fields {
			if !usersmartschedulepolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersmartschedulepolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QualityMaxP50TtftMs(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityMaxP50TtftMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMaxP50TtftMs(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldQualityMaxP50TtftMs, field.TypeInt, value)
	}
	if _u.mutation.QualityMaxP50TtftMsCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityMaxP50TtftMs, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMinSuccessRate(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityMinSuccessRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQualityMinSuccessRate(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldQualityMinSuccessRate, field.TypeFloat64, value)
	}
	if _u.mutation.QualityMinSuccessRateCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityMinSuccessRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.QualityMinSuccessSamples(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityMinSuccessSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMinSuccessSamples(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldQualityMinSuccessSamples, field.TypeInt, value)
	}
	if _u.mutation.QualityMinSuccessSamplesCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityMinSuccessSamples, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityMinTtftSamples(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityMinTtftSamples, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQualityMinTtftSamples(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldQualityMinTtftSamples, field.TypeInt, value)
	}
	if _u.mutation.QualityMinTtftSamplesCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityMinTtftSamples, field.TypeInt)
	}
	if value, ok := _u.mutation.QualityCondition(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldQualityCondition, field.TypeString, value)
	}
	if _u.mutation.QualityConditionCleared() {
		_spec.ClearField(usersmartschedulepolicy.FieldQualityCondition, field.TypeString)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(usersmartschedulepolicy.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(usersmartschedulepolicy.FieldCooldownMinutes, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersmartschedulepolicy.UserTable,
			Columns: []string{usersmartschedulepolicy.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersmartschedulepolicy.UserTable,
			Columns: []string{usersmartschedulepolicy.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserSmartSchedulePolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersmartschedulepolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
