#!/bin/bash
# =============================================================================
# Sub2API Safe Deployment Script
# =============================================================================
# Features:
#   - Pulls the GitHub Actions-built GHCR image for the main sub2api service
#   - Never runs docker build on the production host
#   - Records the previous GHCR image digest for rollback
#   - Auto-rolls back if health check fails after deploy
#   - Logs everything to /opt/sub2api/deploy.log
#   - Safe against SSH disconnections (use with: nohup bash update.sh &)
#   - Also updates sidecars by pulling their CI-built images
#
# Usage:
#   bash /opt/sub2api/update.sh              # normal deploy (sub2api plus sidecars if present)
#   bash /opt/sub2api/update.sh --rollback   # rollback sub2api to previous version
#   bash /opt/sub2api/update.sh --skip-a2    # deploy sub2api + invokeai, skip aiclient2api
#   bash /opt/sub2api/update.sh --skip-invokeai # deploy sub2api + aiclient2api, skip invokeai
#   bash /opt/sub2api/update.sh --only-a2    # deploy aiclient2api only
#   bash /opt/sub2api/update.sh --only-invokeai # deploy invokeai only
# =============================================================================

set -euo pipefail

COMPOSE_DIR="/opt/sub2api"
COMPOSE_OVERRIDE_FILE="${COMPOSE_DIR}/docker-compose.override.yml"
PREVIOUS_IMAGE_FILE="${COMPOSE_DIR}/.sub2api_previous_image"
SUB2API_IMAGE_NAME="${SUB2API_IMAGE:-ghcr.io/541968679/sub2api:latest}"
HEALTH_URL="http://localhost:8080/health"
HEALTH_RETRIES=5
HEALTH_INTERVAL=5
LOG_FILE="/opt/sub2api/deploy.log"

# AIClient2API sidecar image. Built by AIClient2API GitHub Actions and pulled here.
A2_IMAGE_NAME="${AICLIENT2API_IMAGE:-ghcr.io/541968679/aiclient2api:latest}"

# InvokeAI sidecar image. Built by InvokeAI GitHub Actions with GPU_DRIVER=cpu and pulled here.
INVOKEAI_IMAGE_NAME="${INVOKEAI_IMAGE:-ghcr.io/541968679/invokeai-sub2api:latest}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

health_check() {
    local retries=$1
    local interval=$2
    for i in $(seq 1 "$retries"); do
        if curl -sf -o /dev/null -m 5 "$HEALTH_URL"; then
            log "Health check passed (attempt $i/$retries)"
            return 0
        fi
        log "Health check attempt $i/$retries failed, waiting ${interval}s..."
        sleep "$interval"
    done
    return 1
}

ensure_sub2api_image_is_ghcr() {
    local image_ref="$1"
    if [[ "$image_ref" != ghcr.io/541968679/sub2api:* && "$image_ref" != ghcr.io/541968679/sub2api@sha256:* ]]; then
        log "ERROR: Refusing non-GHCR sub2api image: ${image_ref}"
        log "Set SUB2API_IMAGE to ghcr.io/541968679/sub2api:<tag> or a GHCR digest."
        return 1
    fi
}

ensure_compose_uses_sub2api_image() {
    local image_ref="$1"
    ensure_sub2api_image_is_ghcr "$image_ref"

    log "--- Ensuring compose uses ${image_ref} for sub2api ---"
    mkdir -p "$COMPOSE_DIR"
    if [ -f "$COMPOSE_OVERRIDE_FILE" ]; then
        if ! grep -Eq "Generated by deploy/update.sh|sub2api-custom:latest|ghcr.io/541968679/sub2api" "$COMPOSE_OVERRIDE_FILE"; then
            log "ERROR: Refusing to overwrite unrecognized compose override: $COMPOSE_OVERRIDE_FILE"
            log "Move custom override content into docker-compose.yml or update this script intentionally."
            return 1
        fi
    fi

    cat > "$COMPOSE_OVERRIDE_FILE" <<EOF
# Generated by deploy/update.sh.
# Keeps production on the GitHub Actions-built GHCR image.
services:
  sub2api:
    image: ${image_ref}
EOF

    local configured_image
    cd "$COMPOSE_DIR"
    configured_image="$(docker compose config | awk '
        $1 == "sub2api:" { in_service=1; next }
        in_service && /^[[:space:]]{2}[A-Za-z0-9_-]+:/ { exit }
        in_service && $1 == "image:" { print $2; exit }
    ')"
    if [ "$configured_image" != "$image_ref" ]; then
        log "ERROR: Compose config resolves sub2api image to '${configured_image}', expected '${image_ref}'"
        return 1
    fi
}

restart_sub2api() {
    cd "$COMPOSE_DIR"
    docker compose up -d --no-deps --force-recreate sub2api 2>&1 | tee -a "$LOG_FILE"
}

verify_running_image() {
    local expected_ref="$1"
    local expected_id running_id running_name
    expected_id="$(docker image inspect "$expected_ref" --format '{{.Id}}')"
    running_id="$(docker inspect sub2api --format '{{.Image}}')"
    running_name="$(docker inspect sub2api --format '{{.Config.Image}}')"

    if [ "$running_name" != "$expected_ref" ]; then
        log "ERROR: sub2api container image name is '${running_name}', expected '${expected_ref}'"
        return 1
    fi
    if [ "$running_id" != "$expected_id" ]; then
        log "ERROR: sub2api container image id is '${running_id}', expected '${expected_id}'"
        return 1
    fi
    log "Running image verified: ${running_name} (${running_id})"
}

cleanup_docker_disk() {
    log "--- Docker image cleanup (dangling images only) ---"
    docker image prune -f 2>&1 | tee -a "$LOG_FILE" || \
        log "WARN: docker image prune failed"

    log "--- Docker disk usage after cleanup ---"
    docker system df 2>&1 | tee -a "$LOG_FILE" || \
        log "WARN: docker system df failed"
}

current_sub2api_ghcr_digest() {
    if ! docker inspect sub2api >/dev/null 2>&1; then
        return 0
    fi

    local running_image_id
    running_image_id="$(docker inspect sub2api --format '{{.Image}}' 2>/dev/null || true)"
    if [ -z "$running_image_id" ]; then
        return 0
    fi

    docker image inspect "$running_image_id" --format '{{range .RepoDigests}}{{println .}}{{end}}' 2>/dev/null |
        grep '^ghcr.io/541968679/sub2api@sha256:' |
        head -n 1 || true
}

record_previous_sub2api_image() {
    local previous_ref
    previous_ref="$(current_sub2api_ghcr_digest)"
    if [ -n "$previous_ref" ]; then
        echo "$previous_ref" > "$PREVIOUS_IMAGE_FILE"
        log "Recorded previous sub2api image for rollback: $previous_ref"
    else
        rm -f "$PREVIOUS_IMAGE_FILE"
        log "WARN: No previous GHCR digest found for rollback"
    fi
}

do_rollback() {
    log "=== ROLLBACK: Restoring previous version ==="
    if [ ! -s "$PREVIOUS_IMAGE_FILE" ]; then
        log "ERROR: No previous GHCR image recorded at $PREVIOUS_IMAGE_FILE"
        return 1
    fi
    local previous_ref
    previous_ref="$(tr -d '\r\n' < "$PREVIOUS_IMAGE_FILE")"
    ensure_sub2api_image_is_ghcr "$previous_ref"
    ensure_compose_uses_sub2api_image "$previous_ref"
    docker compose pull sub2api 2>&1 | tee -a "$LOG_FILE"
    restart_sub2api
    log "Waiting for rollback health check..."
    sleep 8
    if health_check 3 5 && verify_running_image "$previous_ref"; then
        log "=== ROLLBACK SUCCESSFUL ==="
        docker compose ps
        return 0
    else
        log "=== ROLLBACK HEALTH CHECK FAILED — manual intervention required ==="
        return 1
    fi
}

do_deploy() {
    log "=============================================="
    log "=== Starting sub2api GHCR deployment ==="
    log "=============================================="

    record_previous_sub2api_image

    ensure_compose_uses_sub2api_image "$SUB2API_IMAGE_NAME"

    log "--- Pulling sub2api image: $SUB2API_IMAGE_NAME ---"
    if ! docker compose pull sub2api 2>&1 | tee -a "$LOG_FILE"; then
        log "ERROR: Pull failed! Production is still running the old container."
        return 1
    fi

    log "--- Restarting sub2api ---"
    restart_sub2api

    # Health/image check with auto-rollback.
    log "--- Health check (${HEALTH_RETRIES} attempts, ${HEALTH_INTERVAL}s interval) ---"
    sleep 5
    if health_check "$HEALTH_RETRIES" "$HEALTH_INTERVAL" && verify_running_image "$SUB2API_IMAGE_NAME"; then
        log "=== Deployment successful ==="
        docker compose ps
        cleanup_docker_disk
    else
        log "ERROR: Health check failed after deploy!"
        do_rollback
        return 1
    fi

    log "=============================================="
    log "=== Done ==="
    log "=============================================="
}

do_deploy_a2() {
    log "=============================================="
    log "=== Starting AIClient2API deployment ==="
    log "=============================================="

    cd "$COMPOSE_DIR"

    log "--- Pulling AIClient2API image: $A2_IMAGE_NAME ---"
    if ! docker compose pull aiclient2api 2>&1 | tee -a "$LOG_FILE"; then
        log "ERROR: AIClient2API image pull failed! Sidecar unchanged, sub2api unaffected."
        return 1
    fi

    log "--- Restarting aiclient2api container ---"
    docker compose up -d aiclient2api 2>&1 | tee -a "$LOG_FILE"

    sleep 5
    if docker compose ps aiclient2api | grep -q "Up"; then
        log "=== AIClient2API deployment successful ==="
    else
        log "ERROR: AIClient2API container did not reach Up state. Check: docker compose logs aiclient2api"
        return 1
    fi

    log "=============================================="
    log "=== AIClient2API Done ==="
    log "=============================================="
}

do_deploy_invokeai() {
    log "=============================================="
    log "=== Starting InvokeAI deployment ==="
    log "=============================================="

    cd "$COMPOSE_DIR"

    mkdir -p /opt/invokeai/root

    log "--- Pulling InvokeAI image: $INVOKEAI_IMAGE_NAME ---"
    if ! docker compose pull invokeai 2>&1 | tee -a "$LOG_FILE"; then
        log "ERROR: InvokeAI image pull failed! Sidecar unchanged, sub2api unaffected."
        return 1
    fi

    log "--- Restarting invokeai container ---"
    docker compose up -d invokeai 2>&1 | tee -a "$LOG_FILE"

    sleep 10
    if docker compose ps invokeai | grep -q "Up"; then
        log "=== InvokeAI deployment successful ==="
    else
        log "ERROR: InvokeAI container did not reach Up state. Check: docker compose logs invokeai"
        return 1
    fi

    log "=============================================="
    log "=== InvokeAI Done ==="
    log "=============================================="
}

# --- Main ---
DEPLOY_SUB2API=true
DEPLOY_A2=true
DEPLOY_INVOKEAI=true

for arg in "$@"; do
    case "$arg" in
        --rollback)
            do_rollback
            exit $?
            ;;
        --only-a2)
            DEPLOY_SUB2API=false
            DEPLOY_A2=true
            DEPLOY_INVOKEAI=false
            ;;
        --only-invokeai)
            DEPLOY_SUB2API=false
            DEPLOY_A2=false
            DEPLOY_INVOKEAI=true
            ;;
        --skip-a2)
            DEPLOY_A2=false
            ;;
        --skip-invokeai)
            DEPLOY_INVOKEAI=false
            ;;
        *)
            log "ERROR: Unknown argument: $arg"
            exit 2
            ;;
    esac
done

if [ "$DEPLOY_SUB2API" = true ]; then
    do_deploy
fi

if [ "$DEPLOY_A2" = true ]; then
    if [ "$DEPLOY_SUB2API" = true ]; then
        do_deploy_a2 || log "WARN: AIClient2API deploy failed but sub2api is running"
    else
        do_deploy_a2
    fi
fi

if [ "$DEPLOY_INVOKEAI" = true ]; then
    if [ "$DEPLOY_SUB2API" = true ]; then
        do_deploy_invokeai || log "WARN: InvokeAI deploy failed but sub2api is running"
    else
        do_deploy_invokeai
    fi
fi
