// Code generated by ent, DO NOT EDIT.

package imagechannelmonitor

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the imagechannelmonitor type in the database.
	Label = "image_channel_monitor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldAPIKeyEncrypted holds the string denoting the api_key_encrypted field in the database.
	FieldAPIKeyEncrypted = "api_key_encrypted"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountName holds the string denoting the account_name field in the database.
	FieldAccountName = "account_name"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldProxyName holds the string denoting the proxy_name field in the database.
	FieldProxyName = "proxy_name"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldQuality holds the string denoting the quality field in the database.
	FieldQuality = "quality"
	// FieldN holds the string denoting the n field in the database.
	FieldN = "n"
	// FieldDownloadImage holds the string denoting the download_image field in the database.
	FieldDownloadImage = "download_image"
	// FieldResponseFormat holds the string denoting the response_format field in the database.
	FieldResponseFormat = "response_format"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPublicVisible holds the string denoting the public_visible field in the database.
	FieldPublicVisible = "public_visible"
	// FieldPublicName holds the string denoting the public_name field in the database.
	FieldPublicName = "public_name"
	// FieldIntervalSeconds holds the string denoting the interval_seconds field in the database.
	FieldIntervalSeconds = "interval_seconds"
	// FieldTimeoutSeconds holds the string denoting the timeout_seconds field in the database.
	FieldTimeoutSeconds = "timeout_seconds"
	// FieldLastCheckedAt holds the string denoting the last_checked_at field in the database.
	FieldLastCheckedAt = "last_checked_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeHistories holds the string denoting the histories edge name in mutations.
	EdgeHistories = "histories"
	// Table holds the table name of the imagechannelmonitor in the database.
	Table = "image_channel_monitors"
	// HistoriesTable is the table that holds the histories relation/edge.
	HistoriesTable = "image_channel_monitor_histories"
	// HistoriesInverseTable is the table name for the ImageChannelMonitorHistory entity.
	// It exists in this package in order to avoid circular dependency with the "imagechannelmonitorhistory" package.
	HistoriesInverseTable = "image_channel_monitor_histories"
	// HistoriesColumn is the table column denoting the histories relation/edge.
	HistoriesColumn = "monitor_id"
)

// Columns holds all SQL columns for imagechannelmonitor fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSourceType,
	FieldEndpoint,
	FieldAPIKeyEncrypted,
	FieldAccountID,
	FieldAccountName,
	FieldProxyID,
	FieldProxyName,
	FieldModel,
	FieldPrompt,
	FieldSize,
	FieldQuality,
	FieldN,
	FieldDownloadImage,
	FieldResponseFormat,
	FieldEnabled,
	FieldPublicVisible,
	FieldPublicName,
	FieldIntervalSeconds,
	FieldTimeoutSeconds,
	FieldLastCheckedAt,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// DefaultAPIKeyEncrypted holds the default value on creation for the "api_key_encrypted" field.
	DefaultAPIKeyEncrypted string
	// DefaultAccountName holds the default value on creation for the "account_name" field.
	DefaultAccountName string
	// AccountNameValidator is a validator for the "account_name" field. It is called by the builders before save.
	AccountNameValidator func(string) error
	// DefaultProxyName holds the default value on creation for the "proxy_name" field.
	DefaultProxyName string
	// ProxyNameValidator is a validator for the "proxy_name" field. It is called by the builders before save.
	ProxyNameValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	PromptValidator func(string) error
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize string
	// SizeValidator is a validator for the "size" field. It is called by the builders before save.
	SizeValidator func(string) error
	// DefaultQuality holds the default value on creation for the "quality" field.
	DefaultQuality string
	// QualityValidator is a validator for the "quality" field. It is called by the builders before save.
	QualityValidator func(string) error
	// DefaultN holds the default value on creation for the "n" field.
	DefaultN int
	// NValidator is a validator for the "n" field. It is called by the builders before save.
	NValidator func(int) error
	// DefaultDownloadImage holds the default value on creation for the "download_image" field.
	DefaultDownloadImage bool
	// DefaultResponseFormat holds the default value on creation for the "response_format" field.
	DefaultResponseFormat string
	// ResponseFormatValidator is a validator for the "response_format" field. It is called by the builders before save.
	ResponseFormatValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultPublicVisible holds the default value on creation for the "public_visible" field.
	DefaultPublicVisible bool
	// DefaultPublicName holds the default value on creation for the "public_name" field.
	DefaultPublicName string
	// PublicNameValidator is a validator for the "public_name" field. It is called by the builders before save.
	PublicNameValidator func(string) error
	// DefaultIntervalSeconds holds the default value on creation for the "interval_seconds" field.
	DefaultIntervalSeconds int
	// IntervalSecondsValidator is a validator for the "interval_seconds" field. It is called by the builders before save.
	IntervalSecondsValidator func(int) error
	// DefaultTimeoutSeconds holds the default value on creation for the "timeout_seconds" field.
	DefaultTimeoutSeconds int
	// TimeoutSecondsValidator is a validator for the "timeout_seconds" field. It is called by the builders before save.
	TimeoutSecondsValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// SourceType defines the type for the "source_type" enum field.
type SourceType string

// SourceTypeCustom is the default value of the SourceType enum.
const DefaultSourceType = SourceTypeCustom

// SourceType values.
const (
	SourceTypeCustom  SourceType = "custom"
	SourceTypeAccount SourceType = "account"
)

func (st SourceType) String() string {
	return string(st)
}

// SourceTypeValidator is a validator for the "source_type" field enum values. It is called by the builders before save.
func SourceTypeValidator(st SourceType) error {
	switch st {
	case SourceTypeCustom, SourceTypeAccount:
		return nil
	default:
		return fmt.Errorf("imagechannelmonitor: invalid enum value for source_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the ImageChannelMonitor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByAPIKeyEncrypted orders the results by the api_key_encrypted field.
func ByAPIKeyEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyEncrypted, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountName orders the results by the account_name field.
func ByAccountName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountName, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// ByProxyName orders the results by the proxy_name field.
func ByProxyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyName, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByQuality orders the results by the quality field.
func ByQuality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuality, opts...).ToFunc()
}

// ByN orders the results by the n field.
func ByN(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldN, opts...).ToFunc()
}

// ByDownloadImage orders the results by the download_image field.
func ByDownloadImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadImage, opts...).ToFunc()
}

// ByResponseFormat orders the results by the response_format field.
func ByResponseFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseFormat, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPublicVisible orders the results by the public_visible field.
func ByPublicVisible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicVisible, opts...).ToFunc()
}

// ByPublicName orders the results by the public_name field.
func ByPublicName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicName, opts...).ToFunc()
}

// ByIntervalSeconds orders the results by the interval_seconds field.
func ByIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalSeconds, opts...).ToFunc()
}

// ByTimeoutSeconds orders the results by the timeout_seconds field.
func ByTimeoutSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutSeconds, opts...).ToFunc()
}

// ByLastCheckedAt orders the results by the last_checked_at field.
func ByLastCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByHistoriesCount orders the results by histories count.
func ByHistoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHistoriesStep(), opts...)
	}
}

// ByHistories orders the results by histories terms.
func ByHistories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHistoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newHistoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HistoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HistoriesTable, HistoriesColumn),
	)
}
