// Code generated by ent, DO NOT EDIT.

package imagechannelmonitor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldName, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldEndpoint, v))
}

// APIKeyEncrypted applies equality check predicate on the "api_key_encrypted" field. It's identical to APIKeyEncryptedEQ.
func APIKeyEncrypted(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldAPIKeyEncrypted, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldAccountID, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldAccountName, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldProxyID, v))
}

// ProxyName applies equality check predicate on the "proxy_name" field. It's identical to ProxyNameEQ.
func ProxyName(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldProxyName, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldModel, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldPrompt, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldSize, v))
}

// Quality applies equality check predicate on the "quality" field. It's identical to QualityEQ.
func Quality(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldQuality, v))
}

// N applies equality check predicate on the "n" field. It's identical to NEQ.
func N(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldN, v))
}

// DownloadImage applies equality check predicate on the "download_image" field. It's identical to DownloadImageEQ.
func DownloadImage(v bool) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldDownloadImage, v))
}

// ResponseFormat applies equality check predicate on the "response_format" field. It's identical to ResponseFormatEQ.
func ResponseFormat(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldResponseFormat, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldEnabled, v))
}

// PublicVisible applies equality check predicate on the "public_visible" field. It's identical to PublicVisibleEQ.
func PublicVisible(v bool) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldPublicVisible, v))
}

// PublicName applies equality check predicate on the "public_name" field. It's identical to PublicNameEQ.
func PublicName(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldPublicName, v))
}

// IntervalSeconds applies equality check predicate on the "interval_seconds" field. It's identical to IntervalSecondsEQ.
func IntervalSeconds(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldIntervalSeconds, v))
}

// TimeoutSeconds applies equality check predicate on the "timeout_seconds" field. It's identical to TimeoutSecondsEQ.
func TimeoutSeconds(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldTimeoutSeconds, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldLastCheckedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldName, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v SourceType) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v SourceType) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...SourceType) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...SourceType) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldSourceType, vs...))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointIsNil applies the IsNil predicate on the "endpoint" field.
func EndpointIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldEndpoint))
}

// EndpointNotNil applies the NotNil predicate on the "endpoint" field.
func EndpointNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldEndpoint))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldEndpoint, v))
}

// APIKeyEncryptedEQ applies the EQ predicate on the "api_key_encrypted" field.
func APIKeyEncryptedEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedNEQ applies the NEQ predicate on the "api_key_encrypted" field.
func APIKeyEncryptedNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedIn applies the In predicate on the "api_key_encrypted" field.
func APIKeyEncryptedIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldAPIKeyEncrypted, vs...))
}

// APIKeyEncryptedNotIn applies the NotIn predicate on the "api_key_encrypted" field.
func APIKeyEncryptedNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldAPIKeyEncrypted, vs...))
}

// APIKeyEncryptedGT applies the GT predicate on the "api_key_encrypted" field.
func APIKeyEncryptedGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedGTE applies the GTE predicate on the "api_key_encrypted" field.
func APIKeyEncryptedGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedLT applies the LT predicate on the "api_key_encrypted" field.
func APIKeyEncryptedLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedLTE applies the LTE predicate on the "api_key_encrypted" field.
func APIKeyEncryptedLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedContains applies the Contains predicate on the "api_key_encrypted" field.
func APIKeyEncryptedContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedHasPrefix applies the HasPrefix predicate on the "api_key_encrypted" field.
func APIKeyEncryptedHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedHasSuffix applies the HasSuffix predicate on the "api_key_encrypted" field.
func APIKeyEncryptedHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedIsNil applies the IsNil predicate on the "api_key_encrypted" field.
func APIKeyEncryptedIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldAPIKeyEncrypted))
}

// APIKeyEncryptedNotNil applies the NotNil predicate on the "api_key_encrypted" field.
func APIKeyEncryptedNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldAPIKeyEncrypted))
}

// APIKeyEncryptedEqualFold applies the EqualFold predicate on the "api_key_encrypted" field.
func APIKeyEncryptedEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedContainsFold applies the ContainsFold predicate on the "api_key_encrypted" field.
func APIKeyEncryptedContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldAPIKeyEncrypted, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldAccountID))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameIsNil applies the IsNil predicate on the "account_name" field.
func AccountNameIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldAccountName))
}

// AccountNameNotNil applies the NotNil predicate on the "account_name" field.
func AccountNameNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldAccountName))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldAccountName, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDGT applies the GT predicate on the "proxy_id" field.
func ProxyIDGT(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldProxyID, v))
}

// ProxyIDGTE applies the GTE predicate on the "proxy_id" field.
func ProxyIDGTE(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldProxyID, v))
}

// ProxyIDLT applies the LT predicate on the "proxy_id" field.
func ProxyIDLT(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldProxyID, v))
}

// ProxyIDLTE applies the LTE predicate on the "proxy_id" field.
func ProxyIDLTE(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldProxyID, v))
}

// ProxyIDIsNil applies the IsNil predicate on the "proxy_id" field.
func ProxyIDIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldProxyID))
}

// ProxyIDNotNil applies the NotNil predicate on the "proxy_id" field.
func ProxyIDNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldProxyID))
}

// ProxyNameEQ applies the EQ predicate on the "proxy_name" field.
func ProxyNameEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldProxyName, v))
}

// ProxyNameNEQ applies the NEQ predicate on the "proxy_name" field.
func ProxyNameNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldProxyName, v))
}

// ProxyNameIn applies the In predicate on the "proxy_name" field.
func ProxyNameIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldProxyName, vs...))
}

// ProxyNameNotIn applies the NotIn predicate on the "proxy_name" field.
func ProxyNameNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldProxyName, vs...))
}

// ProxyNameGT applies the GT predicate on the "proxy_name" field.
func ProxyNameGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldProxyName, v))
}

// ProxyNameGTE applies the GTE predicate on the "proxy_name" field.
func ProxyNameGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldProxyName, v))
}

// ProxyNameLT applies the LT predicate on the "proxy_name" field.
func ProxyNameLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldProxyName, v))
}

// ProxyNameLTE applies the LTE predicate on the "proxy_name" field.
func ProxyNameLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldProxyName, v))
}

// ProxyNameContains applies the Contains predicate on the "proxy_name" field.
func ProxyNameContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldProxyName, v))
}

// ProxyNameHasPrefix applies the HasPrefix predicate on the "proxy_name" field.
func ProxyNameHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldProxyName, v))
}

// ProxyNameHasSuffix applies the HasSuffix predicate on the "proxy_name" field.
func ProxyNameHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldProxyName, v))
}

// ProxyNameIsNil applies the IsNil predicate on the "proxy_name" field.
func ProxyNameIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldProxyName))
}

// ProxyNameNotNil applies the NotNil predicate on the "proxy_name" field.
func ProxyNameNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldProxyName))
}

// ProxyNameEqualFold applies the EqualFold predicate on the "proxy_name" field.
func ProxyNameEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldProxyName, v))
}

// ProxyNameContainsFold applies the ContainsFold predicate on the "proxy_name" field.
func ProxyNameContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldProxyName, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldModel, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldPrompt, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldSize, v))
}

// SizeContains applies the Contains predicate on the "size" field.
func SizeContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldSize, v))
}

// SizeHasPrefix applies the HasPrefix predicate on the "size" field.
func SizeHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldSize, v))
}

// SizeHasSuffix applies the HasSuffix predicate on the "size" field.
func SizeHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldSize))
}

// SizeEqualFold applies the EqualFold predicate on the "size" field.
func SizeEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldSize, v))
}

// SizeContainsFold applies the ContainsFold predicate on the "size" field.
func SizeContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldSize, v))
}

// QualityEQ applies the EQ predicate on the "quality" field.
func QualityEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldQuality, v))
}

// QualityNEQ applies the NEQ predicate on the "quality" field.
func QualityNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldQuality, v))
}

// QualityIn applies the In predicate on the "quality" field.
func QualityIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldQuality, vs...))
}

// QualityNotIn applies the NotIn predicate on the "quality" field.
func QualityNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldQuality, vs...))
}

// QualityGT applies the GT predicate on the "quality" field.
func QualityGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldQuality, v))
}

// QualityGTE applies the GTE predicate on the "quality" field.
func QualityGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldQuality, v))
}

// QualityLT applies the LT predicate on the "quality" field.
func QualityLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldQuality, v))
}

// QualityLTE applies the LTE predicate on the "quality" field.
func QualityLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldQuality, v))
}

// QualityContains applies the Contains predicate on the "quality" field.
func QualityContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldQuality, v))
}

// QualityHasPrefix applies the HasPrefix predicate on the "quality" field.
func QualityHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldQuality, v))
}

// QualityHasSuffix applies the HasSuffix predicate on the "quality" field.
func QualityHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldQuality, v))
}

// QualityIsNil applies the IsNil predicate on the "quality" field.
func QualityIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldQuality))
}

// QualityNotNil applies the NotNil predicate on the "quality" field.
func QualityNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldQuality))
}

// QualityEqualFold applies the EqualFold predicate on the "quality" field.
func QualityEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldQuality, v))
}

// QualityContainsFold applies the ContainsFold predicate on the "quality" field.
func QualityContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldQuality, v))
}

// NEQ applies the EQ predicate on the "n" field.
func NEQ(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldN, v))
}

// NNEQ applies the NEQ predicate on the "n" field.
func NNEQ(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldN, v))
}

// NIn applies the In predicate on the "n" field.
func NIn(vs ...int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldN, vs...))
}

// NNotIn applies the NotIn predicate on the "n" field.
func NNotIn(vs ...int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldN, vs...))
}

// NGT applies the GT predicate on the "n" field.
func NGT(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldN, v))
}

// NGTE applies the GTE predicate on the "n" field.
func NGTE(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldN, v))
}

// NLT applies the LT predicate on the "n" field.
func NLT(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldN, v))
}

// NLTE applies the LTE predicate on the "n" field.
func NLTE(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldN, v))
}

// DownloadImageEQ applies the EQ predicate on the "download_image" field.
func DownloadImageEQ(v bool) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldDownloadImage, v))
}

// DownloadImageNEQ applies the NEQ predicate on the "download_image" field.
func DownloadImageNEQ(v bool) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldDownloadImage, v))
}

// ResponseFormatEQ applies the EQ predicate on the "response_format" field.
func ResponseFormatEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldResponseFormat, v))
}

// ResponseFormatNEQ applies the NEQ predicate on the "response_format" field.
func ResponseFormatNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldResponseFormat, v))
}

// ResponseFormatIn applies the In predicate on the "response_format" field.
func ResponseFormatIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldResponseFormat, vs...))
}

// ResponseFormatNotIn applies the NotIn predicate on the "response_format" field.
func ResponseFormatNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldResponseFormat, vs...))
}

// ResponseFormatGT applies the GT predicate on the "response_format" field.
func ResponseFormatGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldResponseFormat, v))
}

// ResponseFormatGTE applies the GTE predicate on the "response_format" field.
func ResponseFormatGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldResponseFormat, v))
}

// ResponseFormatLT applies the LT predicate on the "response_format" field.
func ResponseFormatLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldResponseFormat, v))
}

// ResponseFormatLTE applies the LTE predicate on the "response_format" field.
func ResponseFormatLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldResponseFormat, v))
}

// ResponseFormatContains applies the Contains predicate on the "response_format" field.
func ResponseFormatContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldResponseFormat, v))
}

// ResponseFormatHasPrefix applies the HasPrefix predicate on the "response_format" field.
func ResponseFormatHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldResponseFormat, v))
}

// ResponseFormatHasSuffix applies the HasSuffix predicate on the "response_format" field.
func ResponseFormatHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldResponseFormat, v))
}

// ResponseFormatIsNil applies the IsNil predicate on the "response_format" field.
func ResponseFormatIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldResponseFormat))
}

// ResponseFormatNotNil applies the NotNil predicate on the "response_format" field.
func ResponseFormatNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldResponseFormat))
}

// ResponseFormatEqualFold applies the EqualFold predicate on the "response_format" field.
func ResponseFormatEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldResponseFormat, v))
}

// ResponseFormatContainsFold applies the ContainsFold predicate on the "response_format" field.
func ResponseFormatContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldResponseFormat, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldEnabled, v))
}

// PublicVisibleEQ applies the EQ predicate on the "public_visible" field.
func PublicVisibleEQ(v bool) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldPublicVisible, v))
}

// PublicVisibleNEQ applies the NEQ predicate on the "public_visible" field.
func PublicVisibleNEQ(v bool) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldPublicVisible, v))
}

// PublicNameEQ applies the EQ predicate on the "public_name" field.
func PublicNameEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldPublicName, v))
}

// PublicNameNEQ applies the NEQ predicate on the "public_name" field.
func PublicNameNEQ(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldPublicName, v))
}

// PublicNameIn applies the In predicate on the "public_name" field.
func PublicNameIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldPublicName, vs...))
}

// PublicNameNotIn applies the NotIn predicate on the "public_name" field.
func PublicNameNotIn(vs ...string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldPublicName, vs...))
}

// PublicNameGT applies the GT predicate on the "public_name" field.
func PublicNameGT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldPublicName, v))
}

// PublicNameGTE applies the GTE predicate on the "public_name" field.
func PublicNameGTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldPublicName, v))
}

// PublicNameLT applies the LT predicate on the "public_name" field.
func PublicNameLT(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldPublicName, v))
}

// PublicNameLTE applies the LTE predicate on the "public_name" field.
func PublicNameLTE(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldPublicName, v))
}

// PublicNameContains applies the Contains predicate on the "public_name" field.
func PublicNameContains(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContains(FieldPublicName, v))
}

// PublicNameHasPrefix applies the HasPrefix predicate on the "public_name" field.
func PublicNameHasPrefix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasPrefix(FieldPublicName, v))
}

// PublicNameHasSuffix applies the HasSuffix predicate on the "public_name" field.
func PublicNameHasSuffix(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldHasSuffix(FieldPublicName, v))
}

// PublicNameIsNil applies the IsNil predicate on the "public_name" field.
func PublicNameIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldPublicName))
}

// PublicNameNotNil applies the NotNil predicate on the "public_name" field.
func PublicNameNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldPublicName))
}

// PublicNameEqualFold applies the EqualFold predicate on the "public_name" field.
func PublicNameEqualFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEqualFold(FieldPublicName, v))
}

// PublicNameContainsFold applies the ContainsFold predicate on the "public_name" field.
func PublicNameContainsFold(v string) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldContainsFold(FieldPublicName, v))
}

// IntervalSecondsEQ applies the EQ predicate on the "interval_seconds" field.
func IntervalSecondsEQ(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsNEQ applies the NEQ predicate on the "interval_seconds" field.
func IntervalSecondsNEQ(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsIn applies the In predicate on the "interval_seconds" field.
func IntervalSecondsIn(vs ...int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsNotIn applies the NotIn predicate on the "interval_seconds" field.
func IntervalSecondsNotIn(vs ...int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsGT applies the GT predicate on the "interval_seconds" field.
func IntervalSecondsGT(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldIntervalSeconds, v))
}

// IntervalSecondsGTE applies the GTE predicate on the "interval_seconds" field.
func IntervalSecondsGTE(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldIntervalSeconds, v))
}

// IntervalSecondsLT applies the LT predicate on the "interval_seconds" field.
func IntervalSecondsLT(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldIntervalSeconds, v))
}

// IntervalSecondsLTE applies the LTE predicate on the "interval_seconds" field.
func IntervalSecondsLTE(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldIntervalSeconds, v))
}

// TimeoutSecondsEQ applies the EQ predicate on the "timeout_seconds" field.
func TimeoutSecondsEQ(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldTimeoutSeconds, v))
}

// TimeoutSecondsNEQ applies the NEQ predicate on the "timeout_seconds" field.
func TimeoutSecondsNEQ(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldTimeoutSeconds, v))
}

// TimeoutSecondsIn applies the In predicate on the "timeout_seconds" field.
func TimeoutSecondsIn(vs ...int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldTimeoutSeconds, vs...))
}

// TimeoutSecondsNotIn applies the NotIn predicate on the "timeout_seconds" field.
func TimeoutSecondsNotIn(vs ...int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldTimeoutSeconds, vs...))
}

// TimeoutSecondsGT applies the GT predicate on the "timeout_seconds" field.
func TimeoutSecondsGT(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldTimeoutSeconds, v))
}

// TimeoutSecondsGTE applies the GTE predicate on the "timeout_seconds" field.
func TimeoutSecondsGTE(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldTimeoutSeconds, v))
}

// TimeoutSecondsLT applies the LT predicate on the "timeout_seconds" field.
func TimeoutSecondsLT(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldTimeoutSeconds, v))
}

// TimeoutSecondsLTE applies the LTE predicate on the "timeout_seconds" field.
func TimeoutSecondsLTE(v int) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldTimeoutSeconds, v))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotNull(FieldLastCheckedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasHistories applies the HasEdge predicate on the "histories" edge.
func HasHistories() predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HistoriesTable, HistoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHistoriesWith applies the HasEdge predicate on the "histories" edge with a given conditions (other predicates).
func HasHistoriesWith(preds ...predicate.ImageChannelMonitorHistory) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(func(s *sql.Selector) {
		step := newHistoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageChannelMonitor) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageChannelMonitor) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageChannelMonitor) predicate.ImageChannelMonitor {
	return predicate.ImageChannelMonitor(sql.NotPredicates(p))
}
