// Code generated by ent, DO NOT EDIT.

package imagechannelmonitorhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldID, id))
}

// MonitorID applies equality check predicate on the "monitor_id" field. It's identical to MonitorIDEQ.
func MonitorID(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldMonitorID, v))
}

// HTTPStatus applies equality check predicate on the "http_status" field. It's identical to HTTPStatusEQ.
func HTTPStatus(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldHTTPStatus, v))
}

// APIHeaderMs applies equality check predicate on the "api_header_ms" field. It's identical to APIHeaderMsEQ.
func APIHeaderMs(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldAPIHeaderMs, v))
}

// APIBodyMs applies equality check predicate on the "api_body_ms" field. It's identical to APIBodyMsEQ.
func APIBodyMs(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldAPIBodyMs, v))
}

// APITotalMs applies equality check predicate on the "api_total_ms" field. It's identical to APITotalMsEQ.
func APITotalMs(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldAPITotalMs, v))
}

// JSONBytes applies equality check predicate on the "json_bytes" field. It's identical to JSONBytesEQ.
func JSONBytes(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldJSONBytes, v))
}

// HasURL applies equality check predicate on the "has_url" field. It's identical to HasURLEQ.
func HasURL(v bool) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldHasURL, v))
}

// HasB64JSON applies equality check predicate on the "has_b64_json" field. It's identical to HasB64JSONEQ.
func HasB64JSON(v bool) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldHasB64JSON, v))
}

// ImageURLHost applies equality check predicate on the "image_url_host" field. It's identical to ImageURLHostEQ.
func ImageURLHost(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageURLHost, v))
}

// ImageFirstByteMs applies equality check predicate on the "image_first_byte_ms" field. It's identical to ImageFirstByteMsEQ.
func ImageFirstByteMs(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageFirstByteMs, v))
}

// ImageDownloadMs applies equality check predicate on the "image_download_ms" field. It's identical to ImageDownloadMsEQ.
func ImageDownloadMs(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageDownloadMs, v))
}

// ImageBytes applies equality check predicate on the "image_bytes" field. It's identical to ImageBytesEQ.
func ImageBytes(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageBytes, v))
}

// ImageContentType applies equality check predicate on the "image_content_type" field. It's identical to ImageContentTypeEQ.
func ImageContentType(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageContentType, v))
}

// ImageWidth applies equality check predicate on the "image_width" field. It's identical to ImageWidthEQ.
func ImageWidth(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageWidth, v))
}

// ImageHeight applies equality check predicate on the "image_height" field. It's identical to ImageHeightEQ.
func ImageHeight(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageHeight, v))
}

// ErrorStage applies equality check predicate on the "error_stage" field. It's identical to ErrorStageEQ.
func ErrorStage(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldErrorStage, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldMessage, v))
}

// CheckedAt applies equality check predicate on the "checked_at" field. It's identical to CheckedAtEQ.
func CheckedAt(v time.Time) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldCheckedAt, v))
}

// MonitorIDEQ applies the EQ predicate on the "monitor_id" field.
func MonitorIDEQ(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldMonitorID, v))
}

// MonitorIDNEQ applies the NEQ predicate on the "monitor_id" field.
func MonitorIDNEQ(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldMonitorID, v))
}

// MonitorIDIn applies the In predicate on the "monitor_id" field.
func MonitorIDIn(vs ...int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldMonitorID, vs...))
}

// MonitorIDNotIn applies the NotIn predicate on the "monitor_id" field.
func MonitorIDNotIn(vs ...int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldMonitorID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldStatus, vs...))
}

// HTTPStatusEQ applies the EQ predicate on the "http_status" field.
func HTTPStatusEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldHTTPStatus, v))
}

// HTTPStatusNEQ applies the NEQ predicate on the "http_status" field.
func HTTPStatusNEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldHTTPStatus, v))
}

// HTTPStatusIn applies the In predicate on the "http_status" field.
func HTTPStatusIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldHTTPStatus, vs...))
}

// HTTPStatusNotIn applies the NotIn predicate on the "http_status" field.
func HTTPStatusNotIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldHTTPStatus, vs...))
}

// HTTPStatusGT applies the GT predicate on the "http_status" field.
func HTTPStatusGT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldHTTPStatus, v))
}

// HTTPStatusGTE applies the GTE predicate on the "http_status" field.
func HTTPStatusGTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldHTTPStatus, v))
}

// HTTPStatusLT applies the LT predicate on the "http_status" field.
func HTTPStatusLT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldHTTPStatus, v))
}

// HTTPStatusLTE applies the LTE predicate on the "http_status" field.
func HTTPStatusLTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldHTTPStatus, v))
}

// HTTPStatusIsNil applies the IsNil predicate on the "http_status" field.
func HTTPStatusIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldHTTPStatus))
}

// HTTPStatusNotNil applies the NotNil predicate on the "http_status" field.
func HTTPStatusNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldHTTPStatus))
}

// APIHeaderMsEQ applies the EQ predicate on the "api_header_ms" field.
func APIHeaderMsEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldAPIHeaderMs, v))
}

// APIHeaderMsNEQ applies the NEQ predicate on the "api_header_ms" field.
func APIHeaderMsNEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldAPIHeaderMs, v))
}

// APIHeaderMsIn applies the In predicate on the "api_header_ms" field.
func APIHeaderMsIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldAPIHeaderMs, vs...))
}

// APIHeaderMsNotIn applies the NotIn predicate on the "api_header_ms" field.
func APIHeaderMsNotIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldAPIHeaderMs, vs...))
}

// APIHeaderMsGT applies the GT predicate on the "api_header_ms" field.
func APIHeaderMsGT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldAPIHeaderMs, v))
}

// APIHeaderMsGTE applies the GTE predicate on the "api_header_ms" field.
func APIHeaderMsGTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldAPIHeaderMs, v))
}

// APIHeaderMsLT applies the LT predicate on the "api_header_ms" field.
func APIHeaderMsLT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldAPIHeaderMs, v))
}

// APIHeaderMsLTE applies the LTE predicate on the "api_header_ms" field.
func APIHeaderMsLTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldAPIHeaderMs, v))
}

// APIHeaderMsIsNil applies the IsNil predicate on the "api_header_ms" field.
func APIHeaderMsIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldAPIHeaderMs))
}

// APIHeaderMsNotNil applies the NotNil predicate on the "api_header_ms" field.
func APIHeaderMsNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldAPIHeaderMs))
}

// APIBodyMsEQ applies the EQ predicate on the "api_body_ms" field.
func APIBodyMsEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldAPIBodyMs, v))
}

// APIBodyMsNEQ applies the NEQ predicate on the "api_body_ms" field.
func APIBodyMsNEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldAPIBodyMs, v))
}

// APIBodyMsIn applies the In predicate on the "api_body_ms" field.
func APIBodyMsIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldAPIBodyMs, vs...))
}

// APIBodyMsNotIn applies the NotIn predicate on the "api_body_ms" field.
func APIBodyMsNotIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldAPIBodyMs, vs...))
}

// APIBodyMsGT applies the GT predicate on the "api_body_ms" field.
func APIBodyMsGT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldAPIBodyMs, v))
}

// APIBodyMsGTE applies the GTE predicate on the "api_body_ms" field.
func APIBodyMsGTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldAPIBodyMs, v))
}

// APIBodyMsLT applies the LT predicate on the "api_body_ms" field.
func APIBodyMsLT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldAPIBodyMs, v))
}

// APIBodyMsLTE applies the LTE predicate on the "api_body_ms" field.
func APIBodyMsLTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldAPIBodyMs, v))
}

// APIBodyMsIsNil applies the IsNil predicate on the "api_body_ms" field.
func APIBodyMsIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldAPIBodyMs))
}

// APIBodyMsNotNil applies the NotNil predicate on the "api_body_ms" field.
func APIBodyMsNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldAPIBodyMs))
}

// APITotalMsEQ applies the EQ predicate on the "api_total_ms" field.
func APITotalMsEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldAPITotalMs, v))
}

// APITotalMsNEQ applies the NEQ predicate on the "api_total_ms" field.
func APITotalMsNEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldAPITotalMs, v))
}

// APITotalMsIn applies the In predicate on the "api_total_ms" field.
func APITotalMsIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldAPITotalMs, vs...))
}

// APITotalMsNotIn applies the NotIn predicate on the "api_total_ms" field.
func APITotalMsNotIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldAPITotalMs, vs...))
}

// APITotalMsGT applies the GT predicate on the "api_total_ms" field.
func APITotalMsGT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldAPITotalMs, v))
}

// APITotalMsGTE applies the GTE predicate on the "api_total_ms" field.
func APITotalMsGTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldAPITotalMs, v))
}

// APITotalMsLT applies the LT predicate on the "api_total_ms" field.
func APITotalMsLT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldAPITotalMs, v))
}

// APITotalMsLTE applies the LTE predicate on the "api_total_ms" field.
func APITotalMsLTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldAPITotalMs, v))
}

// APITotalMsIsNil applies the IsNil predicate on the "api_total_ms" field.
func APITotalMsIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldAPITotalMs))
}

// APITotalMsNotNil applies the NotNil predicate on the "api_total_ms" field.
func APITotalMsNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldAPITotalMs))
}

// JSONBytesEQ applies the EQ predicate on the "json_bytes" field.
func JSONBytesEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldJSONBytes, v))
}

// JSONBytesNEQ applies the NEQ predicate on the "json_bytes" field.
func JSONBytesNEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldJSONBytes, v))
}

// JSONBytesIn applies the In predicate on the "json_bytes" field.
func JSONBytesIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldJSONBytes, vs...))
}

// JSONBytesNotIn applies the NotIn predicate on the "json_bytes" field.
func JSONBytesNotIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldJSONBytes, vs...))
}

// JSONBytesGT applies the GT predicate on the "json_bytes" field.
func JSONBytesGT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldJSONBytes, v))
}

// JSONBytesGTE applies the GTE predicate on the "json_bytes" field.
func JSONBytesGTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldJSONBytes, v))
}

// JSONBytesLT applies the LT predicate on the "json_bytes" field.
func JSONBytesLT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldJSONBytes, v))
}

// JSONBytesLTE applies the LTE predicate on the "json_bytes" field.
func JSONBytesLTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldJSONBytes, v))
}

// JSONBytesIsNil applies the IsNil predicate on the "json_bytes" field.
func JSONBytesIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldJSONBytes))
}

// JSONBytesNotNil applies the NotNil predicate on the "json_bytes" field.
func JSONBytesNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldJSONBytes))
}

// HasURLEQ applies the EQ predicate on the "has_url" field.
func HasURLEQ(v bool) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldHasURL, v))
}

// HasURLNEQ applies the NEQ predicate on the "has_url" field.
func HasURLNEQ(v bool) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldHasURL, v))
}

// HasB64JSONEQ applies the EQ predicate on the "has_b64_json" field.
func HasB64JSONEQ(v bool) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldHasB64JSON, v))
}

// HasB64JSONNEQ applies the NEQ predicate on the "has_b64_json" field.
func HasB64JSONNEQ(v bool) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldHasB64JSON, v))
}

// ImageURLHostEQ applies the EQ predicate on the "image_url_host" field.
func ImageURLHostEQ(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageURLHost, v))
}

// ImageURLHostNEQ applies the NEQ predicate on the "image_url_host" field.
func ImageURLHostNEQ(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldImageURLHost, v))
}

// ImageURLHostIn applies the In predicate on the "image_url_host" field.
func ImageURLHostIn(vs ...string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldImageURLHost, vs...))
}

// ImageURLHostNotIn applies the NotIn predicate on the "image_url_host" field.
func ImageURLHostNotIn(vs ...string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldImageURLHost, vs...))
}

// ImageURLHostGT applies the GT predicate on the "image_url_host" field.
func ImageURLHostGT(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldImageURLHost, v))
}

// ImageURLHostGTE applies the GTE predicate on the "image_url_host" field.
func ImageURLHostGTE(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldImageURLHost, v))
}

// ImageURLHostLT applies the LT predicate on the "image_url_host" field.
func ImageURLHostLT(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldImageURLHost, v))
}

// ImageURLHostLTE applies the LTE predicate on the "image_url_host" field.
func ImageURLHostLTE(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldImageURLHost, v))
}

// ImageURLHostContains applies the Contains predicate on the "image_url_host" field.
func ImageURLHostContains(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldContains(FieldImageURLHost, v))
}

// ImageURLHostHasPrefix applies the HasPrefix predicate on the "image_url_host" field.
func ImageURLHostHasPrefix(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldHasPrefix(FieldImageURLHost, v))
}

// ImageURLHostHasSuffix applies the HasSuffix predicate on the "image_url_host" field.
func ImageURLHostHasSuffix(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldHasSuffix(FieldImageURLHost, v))
}

// ImageURLHostIsNil applies the IsNil predicate on the "image_url_host" field.
func ImageURLHostIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldImageURLHost))
}

// ImageURLHostNotNil applies the NotNil predicate on the "image_url_host" field.
func ImageURLHostNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldImageURLHost))
}

// ImageURLHostEqualFold applies the EqualFold predicate on the "image_url_host" field.
func ImageURLHostEqualFold(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEqualFold(FieldImageURLHost, v))
}

// ImageURLHostContainsFold applies the ContainsFold predicate on the "image_url_host" field.
func ImageURLHostContainsFold(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldContainsFold(FieldImageURLHost, v))
}

// ImageFirstByteMsEQ applies the EQ predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageFirstByteMs, v))
}

// ImageFirstByteMsNEQ applies the NEQ predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsNEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldImageFirstByteMs, v))
}

// ImageFirstByteMsIn applies the In predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldImageFirstByteMs, vs...))
}

// ImageFirstByteMsNotIn applies the NotIn predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsNotIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldImageFirstByteMs, vs...))
}

// ImageFirstByteMsGT applies the GT predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsGT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldImageFirstByteMs, v))
}

// ImageFirstByteMsGTE applies the GTE predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsGTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldImageFirstByteMs, v))
}

// ImageFirstByteMsLT applies the LT predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsLT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldImageFirstByteMs, v))
}

// ImageFirstByteMsLTE applies the LTE predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsLTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldImageFirstByteMs, v))
}

// ImageFirstByteMsIsNil applies the IsNil predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldImageFirstByteMs))
}

// ImageFirstByteMsNotNil applies the NotNil predicate on the "image_first_byte_ms" field.
func ImageFirstByteMsNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldImageFirstByteMs))
}

// ImageDownloadMsEQ applies the EQ predicate on the "image_download_ms" field.
func ImageDownloadMsEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageDownloadMs, v))
}

// ImageDownloadMsNEQ applies the NEQ predicate on the "image_download_ms" field.
func ImageDownloadMsNEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldImageDownloadMs, v))
}

// ImageDownloadMsIn applies the In predicate on the "image_download_ms" field.
func ImageDownloadMsIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldImageDownloadMs, vs...))
}

// ImageDownloadMsNotIn applies the NotIn predicate on the "image_download_ms" field.
func ImageDownloadMsNotIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldImageDownloadMs, vs...))
}

// ImageDownloadMsGT applies the GT predicate on the "image_download_ms" field.
func ImageDownloadMsGT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldImageDownloadMs, v))
}

// ImageDownloadMsGTE applies the GTE predicate on the "image_download_ms" field.
func ImageDownloadMsGTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldImageDownloadMs, v))
}

// ImageDownloadMsLT applies the LT predicate on the "image_download_ms" field.
func ImageDownloadMsLT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldImageDownloadMs, v))
}

// ImageDownloadMsLTE applies the LTE predicate on the "image_download_ms" field.
func ImageDownloadMsLTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldImageDownloadMs, v))
}

// ImageDownloadMsIsNil applies the IsNil predicate on the "image_download_ms" field.
func ImageDownloadMsIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldImageDownloadMs))
}

// ImageDownloadMsNotNil applies the NotNil predicate on the "image_download_ms" field.
func ImageDownloadMsNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldImageDownloadMs))
}

// ImageBytesEQ applies the EQ predicate on the "image_bytes" field.
func ImageBytesEQ(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageBytes, v))
}

// ImageBytesNEQ applies the NEQ predicate on the "image_bytes" field.
func ImageBytesNEQ(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldImageBytes, v))
}

// ImageBytesIn applies the In predicate on the "image_bytes" field.
func ImageBytesIn(vs ...int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldImageBytes, vs...))
}

// ImageBytesNotIn applies the NotIn predicate on the "image_bytes" field.
func ImageBytesNotIn(vs ...int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldImageBytes, vs...))
}

// ImageBytesGT applies the GT predicate on the "image_bytes" field.
func ImageBytesGT(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldImageBytes, v))
}

// ImageBytesGTE applies the GTE predicate on the "image_bytes" field.
func ImageBytesGTE(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldImageBytes, v))
}

// ImageBytesLT applies the LT predicate on the "image_bytes" field.
func ImageBytesLT(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldImageBytes, v))
}

// ImageBytesLTE applies the LTE predicate on the "image_bytes" field.
func ImageBytesLTE(v int64) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldImageBytes, v))
}

// ImageBytesIsNil applies the IsNil predicate on the "image_bytes" field.
func ImageBytesIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldImageBytes))
}

// ImageBytesNotNil applies the NotNil predicate on the "image_bytes" field.
func ImageBytesNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldImageBytes))
}

// ImageContentTypeEQ applies the EQ predicate on the "image_content_type" field.
func ImageContentTypeEQ(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageContentType, v))
}

// ImageContentTypeNEQ applies the NEQ predicate on the "image_content_type" field.
func ImageContentTypeNEQ(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldImageContentType, v))
}

// ImageContentTypeIn applies the In predicate on the "image_content_type" field.
func ImageContentTypeIn(vs ...string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldImageContentType, vs...))
}

// ImageContentTypeNotIn applies the NotIn predicate on the "image_content_type" field.
func ImageContentTypeNotIn(vs ...string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldImageContentType, vs...))
}

// ImageContentTypeGT applies the GT predicate on the "image_content_type" field.
func ImageContentTypeGT(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldImageContentType, v))
}

// ImageContentTypeGTE applies the GTE predicate on the "image_content_type" field.
func ImageContentTypeGTE(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldImageContentType, v))
}

// ImageContentTypeLT applies the LT predicate on the "image_content_type" field.
func ImageContentTypeLT(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldImageContentType, v))
}

// ImageContentTypeLTE applies the LTE predicate on the "image_content_type" field.
func ImageContentTypeLTE(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldImageContentType, v))
}

// ImageContentTypeContains applies the Contains predicate on the "image_content_type" field.
func ImageContentTypeContains(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldContains(FieldImageContentType, v))
}

// ImageContentTypeHasPrefix applies the HasPrefix predicate on the "image_content_type" field.
func ImageContentTypeHasPrefix(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldHasPrefix(FieldImageContentType, v))
}

// ImageContentTypeHasSuffix applies the HasSuffix predicate on the "image_content_type" field.
func ImageContentTypeHasSuffix(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldHasSuffix(FieldImageContentType, v))
}

// ImageContentTypeIsNil applies the IsNil predicate on the "image_content_type" field.
func ImageContentTypeIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldImageContentType))
}

// ImageContentTypeNotNil applies the NotNil predicate on the "image_content_type" field.
func ImageContentTypeNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldImageContentType))
}

// ImageContentTypeEqualFold applies the EqualFold predicate on the "image_content_type" field.
func ImageContentTypeEqualFold(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEqualFold(FieldImageContentType, v))
}

// ImageContentTypeContainsFold applies the ContainsFold predicate on the "image_content_type" field.
func ImageContentTypeContainsFold(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldContainsFold(FieldImageContentType, v))
}

// ImageWidthEQ applies the EQ predicate on the "image_width" field.
func ImageWidthEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageWidth, v))
}

// ImageWidthNEQ applies the NEQ predicate on the "image_width" field.
func ImageWidthNEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldImageWidth, v))
}

// ImageWidthIn applies the In predicate on the "image_width" field.
func ImageWidthIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldImageWidth, vs...))
}

// ImageWidthNotIn applies the NotIn predicate on the "image_width" field.
func ImageWidthNotIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldImageWidth, vs...))
}

// ImageWidthGT applies the GT predicate on the "image_width" field.
func ImageWidthGT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldImageWidth, v))
}

// ImageWidthGTE applies the GTE predicate on the "image_width" field.
func ImageWidthGTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldImageWidth, v))
}

// ImageWidthLT applies the LT predicate on the "image_width" field.
func ImageWidthLT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldImageWidth, v))
}

// ImageWidthLTE applies the LTE predicate on the "image_width" field.
func ImageWidthLTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldImageWidth, v))
}

// ImageWidthIsNil applies the IsNil predicate on the "image_width" field.
func ImageWidthIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldImageWidth))
}

// ImageWidthNotNil applies the NotNil predicate on the "image_width" field.
func ImageWidthNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldImageWidth))
}

// ImageHeightEQ applies the EQ predicate on the "image_height" field.
func ImageHeightEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldImageHeight, v))
}

// ImageHeightNEQ applies the NEQ predicate on the "image_height" field.
func ImageHeightNEQ(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldImageHeight, v))
}

// ImageHeightIn applies the In predicate on the "image_height" field.
func ImageHeightIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldImageHeight, vs...))
}

// ImageHeightNotIn applies the NotIn predicate on the "image_height" field.
func ImageHeightNotIn(vs ...int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldImageHeight, vs...))
}

// ImageHeightGT applies the GT predicate on the "image_height" field.
func ImageHeightGT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldImageHeight, v))
}

// ImageHeightGTE applies the GTE predicate on the "image_height" field.
func ImageHeightGTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldImageHeight, v))
}

// ImageHeightLT applies the LT predicate on the "image_height" field.
func ImageHeightLT(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldImageHeight, v))
}

// ImageHeightLTE applies the LTE predicate on the "image_height" field.
func ImageHeightLTE(v int) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldImageHeight, v))
}

// ImageHeightIsNil applies the IsNil predicate on the "image_height" field.
func ImageHeightIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldImageHeight))
}

// ImageHeightNotNil applies the NotNil predicate on the "image_height" field.
func ImageHeightNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldImageHeight))
}

// ErrorStageEQ applies the EQ predicate on the "error_stage" field.
func ErrorStageEQ(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldErrorStage, v))
}

// ErrorStageNEQ applies the NEQ predicate on the "error_stage" field.
func ErrorStageNEQ(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldErrorStage, v))
}

// ErrorStageIn applies the In predicate on the "error_stage" field.
func ErrorStageIn(vs ...string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldErrorStage, vs...))
}

// ErrorStageNotIn applies the NotIn predicate on the "error_stage" field.
func ErrorStageNotIn(vs ...string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldErrorStage, vs...))
}

// ErrorStageGT applies the GT predicate on the "error_stage" field.
func ErrorStageGT(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldErrorStage, v))
}

// ErrorStageGTE applies the GTE predicate on the "error_stage" field.
func ErrorStageGTE(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldErrorStage, v))
}

// ErrorStageLT applies the LT predicate on the "error_stage" field.
func ErrorStageLT(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldErrorStage, v))
}

// ErrorStageLTE applies the LTE predicate on the "error_stage" field.
func ErrorStageLTE(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldErrorStage, v))
}

// ErrorStageContains applies the Contains predicate on the "error_stage" field.
func ErrorStageContains(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldContains(FieldErrorStage, v))
}

// ErrorStageHasPrefix applies the HasPrefix predicate on the "error_stage" field.
func ErrorStageHasPrefix(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldHasPrefix(FieldErrorStage, v))
}

// ErrorStageHasSuffix applies the HasSuffix predicate on the "error_stage" field.
func ErrorStageHasSuffix(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldHasSuffix(FieldErrorStage, v))
}

// ErrorStageIsNil applies the IsNil predicate on the "error_stage" field.
func ErrorStageIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldErrorStage))
}

// ErrorStageNotNil applies the NotNil predicate on the "error_stage" field.
func ErrorStageNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldErrorStage))
}

// ErrorStageEqualFold applies the EqualFold predicate on the "error_stage" field.
func ErrorStageEqualFold(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEqualFold(FieldErrorStage, v))
}

// ErrorStageContainsFold applies the ContainsFold predicate on the "error_stage" field.
func ErrorStageContainsFold(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldContainsFold(FieldErrorStage, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldContainsFold(FieldMessage, v))
}

// CheckedAtEQ applies the EQ predicate on the "checked_at" field.
func CheckedAtEQ(v time.Time) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldEQ(FieldCheckedAt, v))
}

// CheckedAtNEQ applies the NEQ predicate on the "checked_at" field.
func CheckedAtNEQ(v time.Time) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNEQ(FieldCheckedAt, v))
}

// CheckedAtIn applies the In predicate on the "checked_at" field.
func CheckedAtIn(vs ...time.Time) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldIn(FieldCheckedAt, vs...))
}

// CheckedAtNotIn applies the NotIn predicate on the "checked_at" field.
func CheckedAtNotIn(vs ...time.Time) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldNotIn(FieldCheckedAt, vs...))
}

// CheckedAtGT applies the GT predicate on the "checked_at" field.
func CheckedAtGT(v time.Time) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGT(FieldCheckedAt, v))
}

// CheckedAtGTE applies the GTE predicate on the "checked_at" field.
func CheckedAtGTE(v time.Time) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldGTE(FieldCheckedAt, v))
}

// CheckedAtLT applies the LT predicate on the "checked_at" field.
func CheckedAtLT(v time.Time) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLT(FieldCheckedAt, v))
}

// CheckedAtLTE applies the LTE predicate on the "checked_at" field.
func CheckedAtLTE(v time.Time) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.FieldLTE(FieldCheckedAt, v))
}

// HasMonitor applies the HasEdge predicate on the "monitor" edge.
func HasMonitor() predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MonitorTable, MonitorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMonitorWith applies the HasEdge predicate on the "monitor" edge with a given conditions (other predicates).
func HasMonitorWith(preds ...predicate.ImageChannelMonitor) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(func(s *sql.Selector) {
		step := newMonitorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageChannelMonitorHistory) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageChannelMonitorHistory) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageChannelMonitorHistory) predicate.ImageChannelMonitorHistory {
	return predicate.ImageChannelMonitorHistory(sql.NotPredicates(p))
}
