// Code generated by ent, DO NOT EDIT.

package accountqualitysnapshot

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountqualitysnapshot type in the database.
	Label = "account_quality_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// FieldWindowSeconds holds the string denoting the window_seconds field in the database.
	FieldWindowSeconds = "window_seconds"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldErrorCount holds the string denoting the error_count field in the database.
	FieldErrorCount = "error_count"
	// FieldTtftSamples holds the string denoting the ttft_samples field in the database.
	FieldTtftSamples = "ttft_samples"
	// FieldSuccessRate holds the string denoting the success_rate field in the database.
	FieldSuccessRate = "success_rate"
	// FieldAvgTtftMs holds the string denoting the avg_ttft_ms field in the database.
	FieldAvgTtftMs = "avg_ttft_ms"
	// FieldP50TtftMs holds the string denoting the p50_ttft_ms field in the database.
	FieldP50TtftMs = "p50_ttft_ms"
	// FieldP95TtftMs holds the string denoting the p95_ttft_ms field in the database.
	FieldP95TtftMs = "p95_ttft_ms"
	// FieldMaxTtftMs holds the string denoting the max_ttft_ms field in the database.
	FieldMaxTtftMs = "max_ttft_ms"
	// Table holds the table name of the accountqualitysnapshot in the database.
	Table = "account_quality_snapshots"
)

// Columns holds all SQL columns for accountqualitysnapshot fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldCapturedAt,
	FieldWindowSeconds,
	FieldSuccessCount,
	FieldErrorCount,
	FieldTtftSamples,
	FieldSuccessRate,
	FieldAvgTtftMs,
	FieldP50TtftMs,
	FieldP95TtftMs,
	FieldMaxTtftMs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultWindowSeconds holds the default value on creation for the "window_seconds" field.
	DefaultWindowSeconds int
	// DefaultSuccessCount holds the default value on creation for the "success_count" field.
	DefaultSuccessCount int64
	// DefaultErrorCount holds the default value on creation for the "error_count" field.
	DefaultErrorCount int64
	// DefaultTtftSamples holds the default value on creation for the "ttft_samples" field.
	DefaultTtftSamples int64
)

// OrderOption defines the ordering options for the AccountQualitySnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// ByWindowSeconds orders the results by the window_seconds field.
func ByWindowSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowSeconds, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByErrorCount orders the results by the error_count field.
func ByErrorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCount, opts...).ToFunc()
}

// ByTtftSamples orders the results by the ttft_samples field.
func ByTtftSamples(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTtftSamples, opts...).ToFunc()
}

// BySuccessRate orders the results by the success_rate field.
func BySuccessRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessRate, opts...).ToFunc()
}

// ByAvgTtftMs orders the results by the avg_ttft_ms field.
func ByAvgTtftMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgTtftMs, opts...).ToFunc()
}

// ByP50TtftMs orders the results by the p50_ttft_ms field.
func ByP50TtftMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldP50TtftMs, opts...).ToFunc()
}

// ByP95TtftMs orders the results by the p95_ttft_ms field.
func ByP95TtftMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldP95TtftMs, opts...).ToFunc()
}

// ByMaxTtftMs orders the results by the max_ttft_ms field.
func ByMaxTtftMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxTtftMs, opts...).ToFunc()
}
