// Code generated by ent, DO NOT EDIT.

package accountqualitysnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldAccountID, v))
}

// CapturedAt applies equality check predicate on the "captured_at" field. It's identical to CapturedAtEQ.
func CapturedAt(v time.Time) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldCapturedAt, v))
}

// WindowSeconds applies equality check predicate on the "window_seconds" field. It's identical to WindowSecondsEQ.
func WindowSeconds(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldWindowSeconds, v))
}

// SuccessCount applies equality check predicate on the "success_count" field. It's identical to SuccessCountEQ.
func SuccessCount(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldSuccessCount, v))
}

// ErrorCount applies equality check predicate on the "error_count" field. It's identical to ErrorCountEQ.
func ErrorCount(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldErrorCount, v))
}

// TtftSamples applies equality check predicate on the "ttft_samples" field. It's identical to TtftSamplesEQ.
func TtftSamples(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldTtftSamples, v))
}

// SuccessRate applies equality check predicate on the "success_rate" field. It's identical to SuccessRateEQ.
func SuccessRate(v float64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldSuccessRate, v))
}

// AvgTtftMs applies equality check predicate on the "avg_ttft_ms" field. It's identical to AvgTtftMsEQ.
func AvgTtftMs(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldAvgTtftMs, v))
}

// P50TtftMs applies equality check predicate on the "p50_ttft_ms" field. It's identical to P50TtftMsEQ.
func P50TtftMs(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldP50TtftMs, v))
}

// P95TtftMs applies equality check predicate on the "p95_ttft_ms" field. It's identical to P95TtftMsEQ.
func P95TtftMs(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldP95TtftMs, v))
}

// MaxTtftMs applies equality check predicate on the "max_ttft_ms" field. It's identical to MaxTtftMsEQ.
func MaxTtftMs(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldMaxTtftMs, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldAccountID, v))
}

// CapturedAtEQ applies the EQ predicate on the "captured_at" field.
func CapturedAtEQ(v time.Time) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldCapturedAt, v))
}

// CapturedAtNEQ applies the NEQ predicate on the "captured_at" field.
func CapturedAtNEQ(v time.Time) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldCapturedAt, v))
}

// CapturedAtIn applies the In predicate on the "captured_at" field.
func CapturedAtIn(vs ...time.Time) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldCapturedAt, vs...))
}

// CapturedAtNotIn applies the NotIn predicate on the "captured_at" field.
func CapturedAtNotIn(vs ...time.Time) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldCapturedAt, vs...))
}

// CapturedAtGT applies the GT predicate on the "captured_at" field.
func CapturedAtGT(v time.Time) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldCapturedAt, v))
}

// CapturedAtGTE applies the GTE predicate on the "captured_at" field.
func CapturedAtGTE(v time.Time) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldCapturedAt, v))
}

// CapturedAtLT applies the LT predicate on the "captured_at" field.
func CapturedAtLT(v time.Time) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldCapturedAt, v))
}

// CapturedAtLTE applies the LTE predicate on the "captured_at" field.
func CapturedAtLTE(v time.Time) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldCapturedAt, v))
}

// WindowSecondsEQ applies the EQ predicate on the "window_seconds" field.
func WindowSecondsEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldWindowSeconds, v))
}

// WindowSecondsNEQ applies the NEQ predicate on the "window_seconds" field.
func WindowSecondsNEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldWindowSeconds, v))
}

// WindowSecondsIn applies the In predicate on the "window_seconds" field.
func WindowSecondsIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldWindowSeconds, vs...))
}

// WindowSecondsNotIn applies the NotIn predicate on the "window_seconds" field.
func WindowSecondsNotIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldWindowSeconds, vs...))
}

// WindowSecondsGT applies the GT predicate on the "window_seconds" field.
func WindowSecondsGT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldWindowSeconds, v))
}

// WindowSecondsGTE applies the GTE predicate on the "window_seconds" field.
func WindowSecondsGTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldWindowSeconds, v))
}

// WindowSecondsLT applies the LT predicate on the "window_seconds" field.
func WindowSecondsLT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldWindowSeconds, v))
}

// WindowSecondsLTE applies the LTE predicate on the "window_seconds" field.
func WindowSecondsLTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldWindowSeconds, v))
}

// SuccessCountEQ applies the EQ predicate on the "success_count" field.
func SuccessCountEQ(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldSuccessCount, v))
}

// SuccessCountNEQ applies the NEQ predicate on the "success_count" field.
func SuccessCountNEQ(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldSuccessCount, v))
}

// SuccessCountIn applies the In predicate on the "success_count" field.
func SuccessCountIn(vs ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldSuccessCount, vs...))
}

// SuccessCountNotIn applies the NotIn predicate on the "success_count" field.
func SuccessCountNotIn(vs ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldSuccessCount, vs...))
}

// SuccessCountGT applies the GT predicate on the "success_count" field.
func SuccessCountGT(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldSuccessCount, v))
}

// SuccessCountGTE applies the GTE predicate on the "success_count" field.
func SuccessCountGTE(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldSuccessCount, v))
}

// SuccessCountLT applies the LT predicate on the "success_count" field.
func SuccessCountLT(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldSuccessCount, v))
}

// SuccessCountLTE applies the LTE predicate on the "success_count" field.
func SuccessCountLTE(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldSuccessCount, v))
}

// ErrorCountEQ applies the EQ predicate on the "error_count" field.
func ErrorCountEQ(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldErrorCount, v))
}

// ErrorCountNEQ applies the NEQ predicate on the "error_count" field.
func ErrorCountNEQ(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldErrorCount, v))
}

// ErrorCountIn applies the In predicate on the "error_count" field.
func ErrorCountIn(vs ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldErrorCount, vs...))
}

// ErrorCountNotIn applies the NotIn predicate on the "error_count" field.
func ErrorCountNotIn(vs ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldErrorCount, vs...))
}

// ErrorCountGT applies the GT predicate on the "error_count" field.
func ErrorCountGT(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldErrorCount, v))
}

// ErrorCountGTE applies the GTE predicate on the "error_count" field.
func ErrorCountGTE(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldErrorCount, v))
}

// ErrorCountLT applies the LT predicate on the "error_count" field.
func ErrorCountLT(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldErrorCount, v))
}

// ErrorCountLTE applies the LTE predicate on the "error_count" field.
func ErrorCountLTE(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldErrorCount, v))
}

// TtftSamplesEQ applies the EQ predicate on the "ttft_samples" field.
func TtftSamplesEQ(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldTtftSamples, v))
}

// TtftSamplesNEQ applies the NEQ predicate on the "ttft_samples" field.
func TtftSamplesNEQ(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldTtftSamples, v))
}

// TtftSamplesIn applies the In predicate on the "ttft_samples" field.
func TtftSamplesIn(vs ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldTtftSamples, vs...))
}

// TtftSamplesNotIn applies the NotIn predicate on the "ttft_samples" field.
func TtftSamplesNotIn(vs ...int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldTtftSamples, vs...))
}

// TtftSamplesGT applies the GT predicate on the "ttft_samples" field.
func TtftSamplesGT(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldTtftSamples, v))
}

// TtftSamplesGTE applies the GTE predicate on the "ttft_samples" field.
func TtftSamplesGTE(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldTtftSamples, v))
}

// TtftSamplesLT applies the LT predicate on the "ttft_samples" field.
func TtftSamplesLT(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldTtftSamples, v))
}

// TtftSamplesLTE applies the LTE predicate on the "ttft_samples" field.
func TtftSamplesLTE(v int64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldTtftSamples, v))
}

// SuccessRateEQ applies the EQ predicate on the "success_rate" field.
func SuccessRateEQ(v float64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldSuccessRate, v))
}

// SuccessRateNEQ applies the NEQ predicate on the "success_rate" field.
func SuccessRateNEQ(v float64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldSuccessRate, v))
}

// SuccessRateIn applies the In predicate on the "success_rate" field.
func SuccessRateIn(vs ...float64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldSuccessRate, vs...))
}

// SuccessRateNotIn applies the NotIn predicate on the "success_rate" field.
func SuccessRateNotIn(vs ...float64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldSuccessRate, vs...))
}

// SuccessRateGT applies the GT predicate on the "success_rate" field.
func SuccessRateGT(v float64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldSuccessRate, v))
}

// SuccessRateGTE applies the GTE predicate on the "success_rate" field.
func SuccessRateGTE(v float64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldSuccessRate, v))
}

// SuccessRateLT applies the LT predicate on the "success_rate" field.
func SuccessRateLT(v float64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldSuccessRate, v))
}

// SuccessRateLTE applies the LTE predicate on the "success_rate" field.
func SuccessRateLTE(v float64) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldSuccessRate, v))
}

// SuccessRateIsNil applies the IsNil predicate on the "success_rate" field.
func SuccessRateIsNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIsNull(FieldSuccessRate))
}

// SuccessRateNotNil applies the NotNil predicate on the "success_rate" field.
func SuccessRateNotNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotNull(FieldSuccessRate))
}

// AvgTtftMsEQ applies the EQ predicate on the "avg_ttft_ms" field.
func AvgTtftMsEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldAvgTtftMs, v))
}

// AvgTtftMsNEQ applies the NEQ predicate on the "avg_ttft_ms" field.
func AvgTtftMsNEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldAvgTtftMs, v))
}

// AvgTtftMsIn applies the In predicate on the "avg_ttft_ms" field.
func AvgTtftMsIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldAvgTtftMs, vs...))
}

// AvgTtftMsNotIn applies the NotIn predicate on the "avg_ttft_ms" field.
func AvgTtftMsNotIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldAvgTtftMs, vs...))
}

// AvgTtftMsGT applies the GT predicate on the "avg_ttft_ms" field.
func AvgTtftMsGT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldAvgTtftMs, v))
}

// AvgTtftMsGTE applies the GTE predicate on the "avg_ttft_ms" field.
func AvgTtftMsGTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldAvgTtftMs, v))
}

// AvgTtftMsLT applies the LT predicate on the "avg_ttft_ms" field.
func AvgTtftMsLT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldAvgTtftMs, v))
}

// AvgTtftMsLTE applies the LTE predicate on the "avg_ttft_ms" field.
func AvgTtftMsLTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldAvgTtftMs, v))
}

// AvgTtftMsIsNil applies the IsNil predicate on the "avg_ttft_ms" field.
func AvgTtftMsIsNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIsNull(FieldAvgTtftMs))
}

// AvgTtftMsNotNil applies the NotNil predicate on the "avg_ttft_ms" field.
func AvgTtftMsNotNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotNull(FieldAvgTtftMs))
}

// P50TtftMsEQ applies the EQ predicate on the "p50_ttft_ms" field.
func P50TtftMsEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldP50TtftMs, v))
}

// P50TtftMsNEQ applies the NEQ predicate on the "p50_ttft_ms" field.
func P50TtftMsNEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldP50TtftMs, v))
}

// P50TtftMsIn applies the In predicate on the "p50_ttft_ms" field.
func P50TtftMsIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldP50TtftMs, vs...))
}

// P50TtftMsNotIn applies the NotIn predicate on the "p50_ttft_ms" field.
func P50TtftMsNotIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldP50TtftMs, vs...))
}

// P50TtftMsGT applies the GT predicate on the "p50_ttft_ms" field.
func P50TtftMsGT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldP50TtftMs, v))
}

// P50TtftMsGTE applies the GTE predicate on the "p50_ttft_ms" field.
func P50TtftMsGTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldP50TtftMs, v))
}

// P50TtftMsLT applies the LT predicate on the "p50_ttft_ms" field.
func P50TtftMsLT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldP50TtftMs, v))
}

// P50TtftMsLTE applies the LTE predicate on the "p50_ttft_ms" field.
func P50TtftMsLTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldP50TtftMs, v))
}

// P50TtftMsIsNil applies the IsNil predicate on the "p50_ttft_ms" field.
func P50TtftMsIsNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIsNull(FieldP50TtftMs))
}

// P50TtftMsNotNil applies the NotNil predicate on the "p50_ttft_ms" field.
func P50TtftMsNotNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotNull(FieldP50TtftMs))
}

// P95TtftMsEQ applies the EQ predicate on the "p95_ttft_ms" field.
func P95TtftMsEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldP95TtftMs, v))
}

// P95TtftMsNEQ applies the NEQ predicate on the "p95_ttft_ms" field.
func P95TtftMsNEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldP95TtftMs, v))
}

// P95TtftMsIn applies the In predicate on the "p95_ttft_ms" field.
func P95TtftMsIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldP95TtftMs, vs...))
}

// P95TtftMsNotIn applies the NotIn predicate on the "p95_ttft_ms" field.
func P95TtftMsNotIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldP95TtftMs, vs...))
}

// P95TtftMsGT applies the GT predicate on the "p95_ttft_ms" field.
func P95TtftMsGT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldP95TtftMs, v))
}

// P95TtftMsGTE applies the GTE predicate on the "p95_ttft_ms" field.
func P95TtftMsGTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldP95TtftMs, v))
}

// P95TtftMsLT applies the LT predicate on the "p95_ttft_ms" field.
func P95TtftMsLT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldP95TtftMs, v))
}

// P95TtftMsLTE applies the LTE predicate on the "p95_ttft_ms" field.
func P95TtftMsLTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldP95TtftMs, v))
}

// P95TtftMsIsNil applies the IsNil predicate on the "p95_ttft_ms" field.
func P95TtftMsIsNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIsNull(FieldP95TtftMs))
}

// P95TtftMsNotNil applies the NotNil predicate on the "p95_ttft_ms" field.
func P95TtftMsNotNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotNull(FieldP95TtftMs))
}

// MaxTtftMsEQ applies the EQ predicate on the "max_ttft_ms" field.
func MaxTtftMsEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldEQ(FieldMaxTtftMs, v))
}

// MaxTtftMsNEQ applies the NEQ predicate on the "max_ttft_ms" field.
func MaxTtftMsNEQ(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNEQ(FieldMaxTtftMs, v))
}

// MaxTtftMsIn applies the In predicate on the "max_ttft_ms" field.
func MaxTtftMsIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIn(FieldMaxTtftMs, vs...))
}

// MaxTtftMsNotIn applies the NotIn predicate on the "max_ttft_ms" field.
func MaxTtftMsNotIn(vs ...int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotIn(FieldMaxTtftMs, vs...))
}

// MaxTtftMsGT applies the GT predicate on the "max_ttft_ms" field.
func MaxTtftMsGT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGT(FieldMaxTtftMs, v))
}

// MaxTtftMsGTE applies the GTE predicate on the "max_ttft_ms" field.
func MaxTtftMsGTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldGTE(FieldMaxTtftMs, v))
}

// MaxTtftMsLT applies the LT predicate on the "max_ttft_ms" field.
func MaxTtftMsLT(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLT(FieldMaxTtftMs, v))
}

// MaxTtftMsLTE applies the LTE predicate on the "max_ttft_ms" field.
func MaxTtftMsLTE(v int) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldLTE(FieldMaxTtftMs, v))
}

// MaxTtftMsIsNil applies the IsNil predicate on the "max_ttft_ms" field.
func MaxTtftMsIsNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldIsNull(FieldMaxTtftMs))
}

// MaxTtftMsNotNil applies the NotNil predicate on the "max_ttft_ms" field.
func MaxTtftMsNotNil() predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.FieldNotNull(FieldMaxTtftMs))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountQualitySnapshot) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountQualitySnapshot) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountQualitySnapshot) predicate.AccountQualitySnapshot {
	return predicate.AccountQualitySnapshot(sql.NotPredicates(p))
}
