// Code generated by ent, DO NOT EDIT.

package accountscheduleuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldAccountID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldCreatedAt, v))
}

// Allow applies equality check predicate on the "allow" field. It's identical to AllowEQ.
func Allow(v bool) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldAllow, v))
}

// Deny applies equality check predicate on the "deny" field. It's identical to DenyEQ.
func Deny(v bool) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldDeny, v))
}

// MaxConcurrency applies equality check predicate on the "max_concurrency" field. It's identical to MaxConcurrencyEQ.
func MaxConcurrency(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldMaxConcurrency, v))
}

// QualityMaxP50TtftMs applies equality check predicate on the "quality_max_p50_ttft_ms" field. It's identical to QualityMaxP50TtftMsEQ.
func QualityMaxP50TtftMs(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityMaxP50TtftMs, v))
}

// QualityMinSuccessRate applies equality check predicate on the "quality_min_success_rate" field. It's identical to QualityMinSuccessRateEQ.
func QualityMinSuccessRate(v float64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityMinSuccessRate, v))
}

// QualityMinSuccessSamples applies equality check predicate on the "quality_min_success_samples" field. It's identical to QualityMinSuccessSamplesEQ.
func QualityMinSuccessSamples(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityMinSuccessSamples, v))
}

// QualityMinTtftSamples applies equality check predicate on the "quality_min_ttft_samples" field. It's identical to QualityMinTtftSamplesEQ.
func QualityMinTtftSamples(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityMinTtftSamples, v))
}

// QualityCondition applies equality check predicate on the "quality_condition" field. It's identical to QualityConditionEQ.
func QualityCondition(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityCondition, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotIn(FieldAccountID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotIn(FieldUserID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLTE(FieldCreatedAt, v))
}

// AllowEQ applies the EQ predicate on the "allow" field.
func AllowEQ(v bool) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldAllow, v))
}

// AllowNEQ applies the NEQ predicate on the "allow" field.
func AllowNEQ(v bool) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldAllow, v))
}

// DenyEQ applies the EQ predicate on the "deny" field.
func DenyEQ(v bool) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldDeny, v))
}

// DenyNEQ applies the NEQ predicate on the "deny" field.
func DenyNEQ(v bool) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldDeny, v))
}

// MaxConcurrencyEQ applies the EQ predicate on the "max_concurrency" field.
func MaxConcurrencyEQ(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyNEQ applies the NEQ predicate on the "max_concurrency" field.
func MaxConcurrencyNEQ(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyIn applies the In predicate on the "max_concurrency" field.
func MaxConcurrencyIn(vs ...int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyNotIn applies the NotIn predicate on the "max_concurrency" field.
func MaxConcurrencyNotIn(vs ...int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyGT applies the GT predicate on the "max_concurrency" field.
func MaxConcurrencyGT(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGT(FieldMaxConcurrency, v))
}

// MaxConcurrencyGTE applies the GTE predicate on the "max_concurrency" field.
func MaxConcurrencyGTE(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyLT applies the LT predicate on the "max_concurrency" field.
func MaxConcurrencyLT(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLT(FieldMaxConcurrency, v))
}

// MaxConcurrencyLTE applies the LTE predicate on the "max_concurrency" field.
func MaxConcurrencyLTE(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyIsNil applies the IsNil predicate on the "max_concurrency" field.
func MaxConcurrencyIsNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIsNull(FieldMaxConcurrency))
}

// MaxConcurrencyNotNil applies the NotNil predicate on the "max_concurrency" field.
func MaxConcurrencyNotNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotNull(FieldMaxConcurrency))
}

// QualityMaxP50TtftMsEQ applies the EQ predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsEQ(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityMaxP50TtftMs, v))
}

// QualityMaxP50TtftMsNEQ applies the NEQ predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsNEQ(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldQualityMaxP50TtftMs, v))
}

// QualityMaxP50TtftMsIn applies the In predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsIn(vs ...int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIn(FieldQualityMaxP50TtftMs, vs...))
}

// QualityMaxP50TtftMsNotIn applies the NotIn predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsNotIn(vs ...int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotIn(FieldQualityMaxP50TtftMs, vs...))
}

// QualityMaxP50TtftMsGT applies the GT predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsGT(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGT(FieldQualityMaxP50TtftMs, v))
}

// QualityMaxP50TtftMsGTE applies the GTE predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsGTE(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGTE(FieldQualityMaxP50TtftMs, v))
}

// QualityMaxP50TtftMsLT applies the LT predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsLT(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLT(FieldQualityMaxP50TtftMs, v))
}

// QualityMaxP50TtftMsLTE applies the LTE predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsLTE(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLTE(FieldQualityMaxP50TtftMs, v))
}

// QualityMaxP50TtftMsIsNil applies the IsNil predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsIsNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIsNull(FieldQualityMaxP50TtftMs))
}

// QualityMaxP50TtftMsNotNil applies the NotNil predicate on the "quality_max_p50_ttft_ms" field.
func QualityMaxP50TtftMsNotNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotNull(FieldQualityMaxP50TtftMs))
}

// QualityMinSuccessRateEQ applies the EQ predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateEQ(v float64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityMinSuccessRate, v))
}

// QualityMinSuccessRateNEQ applies the NEQ predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateNEQ(v float64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldQualityMinSuccessRate, v))
}

// QualityMinSuccessRateIn applies the In predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateIn(vs ...float64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIn(FieldQualityMinSuccessRate, vs...))
}

// QualityMinSuccessRateNotIn applies the NotIn predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateNotIn(vs ...float64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotIn(FieldQualityMinSuccessRate, vs...))
}

// QualityMinSuccessRateGT applies the GT predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateGT(v float64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGT(FieldQualityMinSuccessRate, v))
}

// QualityMinSuccessRateGTE applies the GTE predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateGTE(v float64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGTE(FieldQualityMinSuccessRate, v))
}

// QualityMinSuccessRateLT applies the LT predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateLT(v float64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLT(FieldQualityMinSuccessRate, v))
}

// QualityMinSuccessRateLTE applies the LTE predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateLTE(v float64) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLTE(FieldQualityMinSuccessRate, v))
}

// QualityMinSuccessRateIsNil applies the IsNil predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateIsNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIsNull(FieldQualityMinSuccessRate))
}

// QualityMinSuccessRateNotNil applies the NotNil predicate on the "quality_min_success_rate" field.
func QualityMinSuccessRateNotNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotNull(FieldQualityMinSuccessRate))
}

// QualityMinSuccessSamplesEQ applies the EQ predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesEQ(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityMinSuccessSamples, v))
}

// QualityMinSuccessSamplesNEQ applies the NEQ predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesNEQ(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldQualityMinSuccessSamples, v))
}

// QualityMinSuccessSamplesIn applies the In predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesIn(vs ...int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIn(FieldQualityMinSuccessSamples, vs...))
}

// QualityMinSuccessSamplesNotIn applies the NotIn predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesNotIn(vs ...int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotIn(FieldQualityMinSuccessSamples, vs...))
}

// QualityMinSuccessSamplesGT applies the GT predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesGT(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGT(FieldQualityMinSuccessSamples, v))
}

// QualityMinSuccessSamplesGTE applies the GTE predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesGTE(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGTE(FieldQualityMinSuccessSamples, v))
}

// QualityMinSuccessSamplesLT applies the LT predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesLT(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLT(FieldQualityMinSuccessSamples, v))
}

// QualityMinSuccessSamplesLTE applies the LTE predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesLTE(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLTE(FieldQualityMinSuccessSamples, v))
}

// QualityMinSuccessSamplesIsNil applies the IsNil predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesIsNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIsNull(FieldQualityMinSuccessSamples))
}

// QualityMinSuccessSamplesNotNil applies the NotNil predicate on the "quality_min_success_samples" field.
func QualityMinSuccessSamplesNotNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotNull(FieldQualityMinSuccessSamples))
}

// QualityMinTtftSamplesEQ applies the EQ predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesEQ(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityMinTtftSamples, v))
}

// QualityMinTtftSamplesNEQ applies the NEQ predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesNEQ(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldQualityMinTtftSamples, v))
}

// QualityMinTtftSamplesIn applies the In predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesIn(vs ...int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIn(FieldQualityMinTtftSamples, vs...))
}

// QualityMinTtftSamplesNotIn applies the NotIn predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesNotIn(vs ...int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotIn(FieldQualityMinTtftSamples, vs...))
}

// QualityMinTtftSamplesGT applies the GT predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesGT(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGT(FieldQualityMinTtftSamples, v))
}

// QualityMinTtftSamplesGTE applies the GTE predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesGTE(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGTE(FieldQualityMinTtftSamples, v))
}

// QualityMinTtftSamplesLT applies the LT predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesLT(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLT(FieldQualityMinTtftSamples, v))
}

// QualityMinTtftSamplesLTE applies the LTE predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesLTE(v int) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLTE(FieldQualityMinTtftSamples, v))
}

// QualityMinTtftSamplesIsNil applies the IsNil predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesIsNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIsNull(FieldQualityMinTtftSamples))
}

// QualityMinTtftSamplesNotNil applies the NotNil predicate on the "quality_min_ttft_samples" field.
func QualityMinTtftSamplesNotNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotNull(FieldQualityMinTtftSamples))
}

// QualityConditionEQ applies the EQ predicate on the "quality_condition" field.
func QualityConditionEQ(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEQ(FieldQualityCondition, v))
}

// QualityConditionNEQ applies the NEQ predicate on the "quality_condition" field.
func QualityConditionNEQ(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNEQ(FieldQualityCondition, v))
}

// QualityConditionIn applies the In predicate on the "quality_condition" field.
func QualityConditionIn(vs ...string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIn(FieldQualityCondition, vs...))
}

// QualityConditionNotIn applies the NotIn predicate on the "quality_condition" field.
func QualityConditionNotIn(vs ...string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotIn(FieldQualityCondition, vs...))
}

// QualityConditionGT applies the GT predicate on the "quality_condition" field.
func QualityConditionGT(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGT(FieldQualityCondition, v))
}

// QualityConditionGTE applies the GTE predicate on the "quality_condition" field.
func QualityConditionGTE(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldGTE(FieldQualityCondition, v))
}

// QualityConditionLT applies the LT predicate on the "quality_condition" field.
func QualityConditionLT(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLT(FieldQualityCondition, v))
}

// QualityConditionLTE applies the LTE predicate on the "quality_condition" field.
func QualityConditionLTE(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldLTE(FieldQualityCondition, v))
}

// QualityConditionContains applies the Contains predicate on the "quality_condition" field.
func QualityConditionContains(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldContains(FieldQualityCondition, v))
}

// QualityConditionHasPrefix applies the HasPrefix predicate on the "quality_condition" field.
func QualityConditionHasPrefix(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldHasPrefix(FieldQualityCondition, v))
}

// QualityConditionHasSuffix applies the HasSuffix predicate on the "quality_condition" field.
func QualityConditionHasSuffix(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldHasSuffix(FieldQualityCondition, v))
}

// QualityConditionIsNil applies the IsNil predicate on the "quality_condition" field.
func QualityConditionIsNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldIsNull(FieldQualityCondition))
}

// QualityConditionNotNil applies the NotNil predicate on the "quality_condition" field.
func QualityConditionNotNil() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldNotNull(FieldQualityCondition))
}

// QualityConditionEqualFold applies the EqualFold predicate on the "quality_condition" field.
func QualityConditionEqualFold(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldEqualFold(FieldQualityCondition, v))
}

// QualityConditionContainsFold applies the ContainsFold predicate on the "quality_condition" field.
func QualityConditionContainsFold(v string) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.FieldContainsFold(FieldQualityCondition, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, AccountColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, UserColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountScheduleUser) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountScheduleUser) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountScheduleUser) predicate.AccountScheduleUser {
	return predicate.AccountScheduleUser(sql.NotPredicates(p))
}
